// NOTE: This file was auto-generated by splitting progress_output.rs.
// Do not edit directly.

use indicatif::{InMemoryTerm, MultiProgress, ProgressBar, ProgressDrawTarget, ProgressStyle};
use mediapm_utils::progress::{
    DimensionSource, ProgressGroup, TestDimensionSource, TestTimeSource, TimeSource, TrackedHandle,
};
use std::sync::Arc;

use super::common::*;

#[test]
fn color_active_child_text() {
    let (mp, term) = mk_with_size(2, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .build_with_overall();
    let child = group.add_bar(5, "child");
    child.set_position(0);
    group.tick();
    let contents = term.contents();
    let lines: Vec<&str> = contents.lines().collect();
    // H=2, capacity=2+overall → line[0]=child, line[1]=overall, no blanks
    assert_eq!(lines.len(), 2, "expected 2 visible lines");
    let child_line = lines[0];
    let overall_line = lines[1];
    // Label visible
    assert!(child_line.contains("child"), "child label: {child_line:?}");
    assert!(overall_line.contains("overall"), "overall label: {overall_line:?}");
    // Count/total values correct
    assert!(child_line.contains("0/5"), "child count/total 0/5: {child_line:?}");
    assert!(overall_line.contains("0/1"), "overall count/total 0/1: {overall_line:?}");
    // Rate visible for active child
    assert!(
        child_line.contains("/d") || child_line.contains("/s"),
        "rate units in active child: {child_line:?}"
    );
    // Elapsed visible
    assert!(child_line.contains("0s"), "elapsed '0s': {child_line:?}");
    // No brackets on active bar
    assert!(!child_line.contains("[F]"), "no [F] in active child: {child_line:?}");
    assert!(!child_line.contains("[A]"), "no [A] in active child: {child_line:?}");
    assert!(!child_line.contains("[S]"), "no [S] in active child: {child_line:?}");
}

/// Failed bar: [F] bracket shown, values correct.
#[test]
fn color_failed_bracket_text() {
    let (mp, term) = mk_with_size(2, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .build_with_overall();
    let child = group.add_bar(5, "child");
    group.tick();
    child.finish_error();
    group.tick();
    let contents = term.contents();
    let lines: Vec<&str> = contents.lines().collect();
    assert_eq!(lines.len(), 2, "expected 2 visible lines");
    let child_line = lines[0];
    // [F] bracket visible
    assert!(child_line.contains("[F]"), "failed bar should show [F] bracket: {child_line:?}");
    // Count/total correct
    assert!(child_line.contains("0/5"), "failed bar count/total: {child_line:?}");
    // No yellow bracket
    assert!(!child_line.contains("[A]"), "no [A] on failed: {child_line:?}");
}

/// Abandoned bar: [A] bracket shown, values correct.
#[test]
fn color_abandoned_bracket_text() {
    let (mp, term) = mk_with_size(2, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .build_with_overall();
    let child = group.add_bar(5, "child");
    group.tick();
    child.abandon();
    group.tick();
    let contents = term.contents();
    let lines: Vec<&str> = contents.lines().collect();
    assert_eq!(lines.len(), 2, "expected 2 visible lines");
    let child_line = lines[0];
    // [A] bracket visible
    assert!(child_line.contains("[A]"), "abandoned bar should show [A] bracket: {child_line:?}");
    // Count/total correct
    assert!(child_line.contains("0/5"), "abandoned bar count/total: {child_line:?}");
    // No red bracket
    assert!(!child_line.contains("[F]"), "no [F] on abandoned: {child_line:?}");
}

/// Success bar: full count/total, no brackets.
#[test]
fn color_success_text() {
    let (mp, term) = mk_with_size(2, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .build_with_overall();
    let child = group.add_bar(5, "child");
    child.set_position(5);
    group.tick();
    child.finish_success();
    group.tick();
    let contents = term.contents();
    let lines: Vec<&str> = contents.lines().collect();
    assert_eq!(lines.len(), 2, "expected 2 visible lines");
    let child_line = lines[0];
    // Full count/total
    assert!(child_line.contains("5/5"), "success bar full count/total: {child_line:?}");
    // No brackets
    assert!(!child_line.contains("[F]"), "no [F] on success: {child_line:?}");
    assert!(!child_line.contains("[A]"), "no [A] on success: {child_line:?}");
    assert!(!child_line.contains("[S]"), "no [S] on success: {child_line:?}");
}

/// Finished bar (via `finish()`): full count/total, no [S] bracket.
#[test]
fn color_finished_text() {
    let (mp, term) = mk_with_size(2, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .build_with_overall();
    let child = group.add_bar(5, "child");
    child.set_position(5);
    group.tick();
    child.finish();
    group.tick();
    let contents = term.contents();
    let lines: Vec<&str> = contents.lines().collect();
    assert_eq!(lines.len(), 2, "expected 2 visible lines");
    let child_line = lines[0];
    // Full count/total
    assert!(child_line.contains("5/5"), "finished bar full count/total: {child_line:?}");
    // No brackets
    assert!(!child_line.contains("[S]"), "no [S] on finished: {child_line:?}");
}

/// No [S] or [=] brackets appear anywhere in the output.
#[test]
fn color_no_success_brackets() {
    let (mp, term) = mk_with_size(2, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .build_with_overall();
    let child = group.add_bar(5, "child");
    group.tick();
    child.finish_success();
    group.tick();
    let contents = term.contents();
    // No [S] or [=] anywhere in the output
    assert!(!contents.contains("[S]"), "[S] bracket must not appear in output");
    assert!(!contents.contains("[=]"), "[=] bracket must not appear in output");
}
