// NOTE: This file was auto-generated by splitting progress_output.rs.
// Do not edit directly.

use indicatif::{InMemoryTerm, MultiProgress, ProgressBar, ProgressDrawTarget, ProgressStyle};
use mediapm_utils::progress::{
    DimensionSource, ProgressGroup, TestDimensionSource, TestTimeSource, TimeSource, TrackedHandle,
};
use std::sync::Arc;

use super::common::*;

#[test]
fn parallel_worker_finish_error_other_continues() {
    let (mp, term) = mk_with_size(5, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(5)
        .with_overall("overall", 10)
        .build_with_overall();

    let a = group.add_bar(5, "worker-a");
    let b = group.add_bar(5, "worker-b");

    a.advance(3);
    b.advance(2);
    group.tick();

    // worker-a finishes with error, worker-b continues
    a.finish_error();
    b.advance(1);
    group.tick();

    let contents = term.contents();
    let lines: Vec<&str> = contents.lines().collect();
    for (_i, _line) in lines.iter().enumerate() {}
    // Capacity 5 with overall: children at [2, 3], overall at [4] — 5 lines
    // Chronological: worker-a (first) at slot[2], worker-b (second) at slot[3].
    assert_eq!(lines.len(), 5, "5 lines — 2 children + 2 blanks + overall");
    assert!(lines[2].contains("worker-a"), "worker-a visible at line 2: {0}", lines[2]);
    assert!(lines[2].contains("[F]"), "worker-a shows error: {0}", lines[2]);
    assert!(lines[3].contains("worker-b"), "worker-b visible at line 3: {0}", lines[3]);
    assert!(lines[3].contains("3/5"), "worker-b shows 3/5: {0}", lines[3]);
    assert!(!lines[3].contains("crash"), "worker-b must not show error: {0}", lines[3]);
    assert!(lines[4].contains("overall"), "overall visible: {0}", lines[4]);
}

// ── Consumer simulation: sequential tool sync with recycling ────────────

#[test]
fn consumer_sync_too_many_tools_recycles() {
    let (mp, term) = mk_with_size(4, 80);
    let group = ProgressGroup::builder().with_multi_progress(mp).capacity(4).build(); // capacity 4, no overall

    // 8 sequential tools on capacity 4 — first 4 get display slots,
    // remaining 4 recycle finished slots.
    for i in 0..8 {
        let tool = group.add_bar(1, &format!("tool{i}"));
        tool.advance(1);
        tool.finish_success();
        group.tick();
    }

    let contents = term.contents();
    let lines: Vec<&str> = contents.lines().collect();
    for (_i, _line) in lines.iter().enumerate() {}
    // 4 bars visible (capacity 4, no overall). Only the last 4 tool slots
    // show in the terminal (tools 4–7, since 0–3 were recycled).
    assert_eq!(lines.len(), 4, "4 lines — all slots filled");
    // Verify at least some of the visible bars show our tools
    // The exact content depends on which finished bars are recycled first
    assert!(lines.iter().any(|l| l.contains("1/1")), "at least one bar shows 1/1: {lines:?}");
}

// ── Retention: finished bars keep their final state ─────────────────────

#[test]
fn retention_finished_bar_keeps_final_msg() {
    let (mp, term) = mk_with_size(4, 80);
    let group = ProgressGroup::builder().with_multi_progress(mp).capacity(4).build();

    let a = group.add_bar(2, "alpha");
    a.advance(2);
    a.finish_success();
    group.tick();

    let b = group.add_bar(3, "beta");
    b.advance(3);
    b.finish_success();
    group.tick();

    let contents = term.contents();
    let lines: Vec<&str> = contents.lines().collect();
    for (_i, _line) in lines.iter().enumerate() {}
    // 4 slots, no overall → 4 lines. Both finished bars retain success status.
    assert!(lines.len() >= 2, "at least 2 lines: {lines:?}");
    assert!(
        lines.iter().any(|l| l.contains("2/2") || l.contains("3/3")),
        "bars show position: {lines:?}"
    );
    assert!(lines.iter().any(|l| l.contains("alpha")), "bar alpha visible: {lines:?}");
    assert!(lines.iter().any(|l| l.contains("beta")), "bar beta visible: {lines:?}");
}

#[test]
fn retention_finished_bar_persists_across_new_work() {
    let (mp, term) = mk_with_size(4, 80);
    let group = ProgressGroup::builder().with_multi_progress(mp).capacity(4).build();

    // Slot 0: finished bar
    let a = group.add_bar(1, "alpha");
    a.advance(1);
    a.finish_success();
    group.tick();

    // Slot 1: active bar alongside the finished one
    let _b = group.add_bar(5, "beta");
    let contents = term.contents();
    let lines: Vec<&str> = contents.lines().collect();
    for (_i, _line) in lines.iter().enumerate() {}
    // 4 slots → 4 lines. Finished bar (1/1) visible alongside active beta.
    assert!(lines.len() >= 2, "at least 2 lines: {lines:?}");
    assert!(lines.iter().any(|l| l.contains("1/1")), "line shows finished alpha at 1/1: {lines:?}");
    assert!(lines.iter().any(|l| l.contains("beta")), "line shows active 'beta': {lines:?}");
}

#[test]
fn retention_multiple_finished_bars() {
    let (mp, term) = mk_with_size(4, 80);
    let group = ProgressGroup::builder().with_multi_progress(mp).capacity(4).build();

    for (i, _msg) in ["first", "second", "third", "fourth"].iter().enumerate() {
        let h = group.add_bar(1, &format!("task{i}"));
        h.advance(1);
        h.finish_success();
        group.tick();
    }

    let contents = term.contents();
    let lines: Vec<&str> = contents.lines().collect();
    for (_i, _line) in lines.iter().enumerate() {}
    // 4 slots, all finished → 4 lines, each with its task name.
    assert_eq!(lines.len(), 4, "4 lines — all 4 finished bars visible");
    for (i, _msg) in ["first", "second", "third", "fourth"].iter().enumerate() {
        let task_name = format!("task{i}");
        assert!(
            lines.iter().any(|l| l.contains(&task_name)),
            "a bar shows '{task_name}': {lines:?}"
        );
    }
}

// ── Consumer simulation: materializer with parallel workers ─────────────

#[test]
fn consumer_materializer_single_bar_parallel_workers() {
    let (mp, term) = mk_with_size(4, 80);
    let group = ProgressGroup::builder().with_multi_progress(mp).capacity(4).build();

    // Simulate a materializer dispatcher: parallel workers tracked
    // as a single progress bar.
    let total_work: u64 = 100;
    let pb = group.add_bar(total_work, "materializing");

    // Advance in chunks (simulating parallel workers reporting)
    for chunk in [30u64, 30, 30, 10] {
        pb.advance(chunk);
        group.tick();
    }
    pb.finish_success();
    group.tick();

    let contents = term.contents();
    let lines: Vec<&str> = contents.lines().collect();
    for (_i, _line) in lines.iter().enumerate() {}
    assert!(lines.len() >= 1, "at least 1 line: {lines:?}");
    assert!(lines.iter().any(|l| l.contains("100/100")), "shows 100/100: {lines:?}");
}

// ═════════════════════════════════════════════════════════════════════════════
// Phase 1: Exact-output regression tests
// ═════════════════════════════════════════════════════════════════════════════

/// Exact output match for parallel workers with finish_error + active.
///
/// Uses TestTimeSource for deterministic rate and elapsed values.
#[test]
fn exact_consumer_parallel_worker_output() {
    let (mp, term, ts) = mk_with_size_and_ts(5, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(5)
        .with_overall("overall", 10)
        .with_time_source(ts.clone() as Arc<dyn TimeSource>)
        .build_with_overall();

    let a = group.add_bar(5, "worker-a");
    let b = group.add_bar(5, "worker-b");

    a.advance(3);
    b.advance(2);
    ts.advance(std::time::Duration::from_secs(1));
    group.tick();

    a.finish_error();
    b.advance(1);
    ts.advance(std::time::Duration::from_secs(1));
    group.tick();

    assert_eq!(
        term.contents(),
        concat!(
            "\n",
            "\n",
            "⠏              [F] worker-a ████████████░░░░░░░░░  3/5 1s\n",
            "⠧                  worker-b ████████████░░░░░░░░░  3/5 2s 17/m 7s\n",
            "⠼                   overall ░░░░░░░░░░░░░░░░░░░░░  0/10 2s 0/d",
        )
    );
}

/// Exact output match for sequential tool sync with slot recycling.
#[test]
fn exact_consumer_sync_too_many_tools_recycles() {
    let (mp, term) = mk_with_size(4, 80);
    let group = ProgressGroup::builder().with_multi_progress(mp).capacity(4).build();

    for i in 0..8 {
        let tool = group.add_bar(1, &format!("tool{i}"));
        tool.advance(1);
        tool.finish_success();
        group.tick();
    }

    assert_eq!(
        term.contents(),
        concat!(
            "⠴                     tool4 █████████████████████  1/1 0s\n",
            "⠦                     tool5 █████████████████████  1/1 0s\n",
            "⠏                     tool6 █████████████████████  1/1 0s\n",
            "⠏                     tool7 █████████████████████  1/1 0s",
        )
    );
}

/// Exact output match for retention of finished bars (sequential add/completion).
#[test]
fn exact_consumer_retention_finished_bar() {
    let (mp, term) = mk_with_size(4, 80);
    let group = ProgressGroup::builder().with_multi_progress(mp).capacity(4).build();

    let a = group.add_bar(2, "alpha");
    a.advance(2);
    a.finish_success();
    group.tick();

    let b = group.add_bar(3, "beta");
    b.advance(3);
    b.finish_success();
    group.tick();

    assert_eq!(
        term.contents(),
        concat!(
            "\n",
            "\n",
            "⠏                     alpha █████████████████████  2/2 0s\n",
            "⠏                      beta █████████████████████  3/3 0s",
        )
    );
}

/// Exact output match for multiple finished bars filling all slots.
#[test]
fn exact_consumer_retention_multiple_finished() {
    let (mp, term) = mk_with_size(4, 80);
    let group = ProgressGroup::builder().with_multi_progress(mp).capacity(4).build();

    for (i, _msg) in ["first", "second", "third", "fourth"].iter().enumerate() {
        let h = group.add_bar(1, &format!("task{i}"));
        h.advance(1);
        h.finish_success();
        group.tick();
    }

    assert_eq!(
        term.contents(),
        concat!(
            "⠙                     task0 █████████████████████  1/1 0s\n",
            "⠹                     task1 █████████████████████  1/1 0s\n",
            "⠏                     task2 █████████████████████  1/1 0s\n",
            "⠏                     task3 █████████████████████  1/1 0s",
        )
    );
}
