// NOTE: This file was auto-generated by splitting progress_output.rs.
// Do not edit directly.

use indicatif::{InMemoryTerm, MultiProgress, ProgressBar, ProgressDrawTarget, ProgressStyle};
use mediapm_utils::progress::{
    DimensionSource, ProgressGroup, TestDimensionSource, TestTimeSource, TimeSource, TrackedHandle,
};
use std::sync::Arc;

use crate::common::*;

#[test]
fn rate_stable_on_stale_ticks() {
    let (mp, term) = mk_with_size(2, 80);
    let time_source = Arc::new(TestTimeSource::new());
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .with_time_source(time_source.clone())
        .build_with_overall();
    let child = group.add_bar(1000, "test");
    // Advance a significant amount so the initial rate is clearly non-zero.
    child.set_position(500);
    group.tick();
    time_source.advance(std::time::Duration::from_millis(60));
    let after_progress = term.contents();
    assert!(
        after_progress.contains("500/1.0k"),
        "count/total visible after advance: {after_progress:?}"
    );
    // Rate must be shown for active bars.
    assert!(
        after_progress.contains("/s")
            || after_progress.contains("k/s")
            || after_progress.contains("M/s")
            || after_progress.contains("/m")
            || after_progress.contains("/h")
            || after_progress.contains("/d"),
        "rate must appear after progress: {after_progress:?}"
    );

    // Now tick 20× with realistic ticker-interval delays.
    for _ in 0..20 {
        time_source.advance(std::time::Duration::from_millis(50));
        group.tick();
    }

    let after_stale = term.contents();
    // Rate must still be present (must not have decayed to empty).
    assert!(
        after_stale.contains("/s")
            || after_stale.contains("k/s")
            || after_stale.contains("M/s")
            || after_stale.contains("/m")
            || after_stale.contains("/h")
            || after_stale.contains("/d"),
        "rate must survive stale ticks: {after_stale:?}"
    );
    // Count/total unchanged.
    assert!(
        after_stale.contains("500/1.0k"),
        "count/total unchanged after stale ticks: {after_stale:?}"
    );
}

/// Active bar: rate updates when more progress is made.
///
/// Advance → tick → capture rate, then advance more → tick → verify rate
/// has changed (not stuck at old value).
#[test]
fn rate_updates_on_progress() {
    let (mp, term) = mk_with_size(2, 80);
    let time_source = Arc::new(TestTimeSource::new());
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .with_time_source(time_source.clone())
        .build_with_overall();
    let child = group.add_bar(2000, "test");
    child.set_position(10);
    time_source.advance(std::time::Duration::from_millis(2));
    group.tick();
    time_source.advance(std::time::Duration::from_millis(60));
    let after_small = term.contents();

    // Advance much more.
    child.set_position(1500);
    group.tick();
    time_source.advance(std::time::Duration::from_millis(60));
    let after_large = term.contents();

    // Both must show rate.
    assert!(
        after_small.contains("/s") || after_small.contains("k/s") || after_small.contains("M/s"),
        "rate after small progress: {after_small:?}"
    );
    assert!(
        after_large.contains("/s") || after_large.contains("k/s") || after_large.contains("M/s"),
        "rate after large progress: {after_large:?}"
    );
    // The two outputs should differ because position changed significantly.
    // (The spinner may also differ, but that's fine — we just need *some* change
    // rather than identical frozen output.)
    assert_ne!(after_small, after_large, "rate/progress must differ between 10 and 1500");
}

/// Active bar: rate is always shown even with zero progress.
#[test]
fn rate_always_shown() {
    let (mp, term) = mk_with_size(2, 80);
    let time_source = Arc::new(TestTimeSource::new());
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .with_time_source(time_source.clone())
        .build_with_overall();
    let _child = group.add_bar(100, "idle");
    // No progress made — bar is still active.
    group.tick();
    time_source.advance(std::time::Duration::from_millis(60));
    let contents = term.contents();
    // Rate must appear even with zero progress.
    assert!(
        contents.contains("/s")
            || contents.contains("k/s")
            || contents.contains("M/s")
            || contents.contains("/m")
            || contents.contains("/h")
            || contents.contains("/d"),
        "rate must appear even on idle active bar: {contents:?}"
    );
}
