// NOTE: This file was auto-generated by splitting progress_output.rs.
// Do not edit directly.

use indicatif::{InMemoryTerm, MultiProgress, ProgressBar, ProgressDrawTarget, ProgressStyle};
use mediapm_utils::progress::{
    DimensionSource, ProgressGroup, TestDimensionSource, TestTimeSource, TimeSource, TrackedHandle,
};
use std::sync::Arc;

use crate::common::*;

#[test]
fn resize_width_wide_to_narrow_changes_output() {
    let dims = Arc::new(TestDimensionSource::new((H, 80)));
    let (mp, term) = mk_with_size(H, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(5)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(false)
        .build_with_overall();
    let contents_wide = term.contents();
    for (_i, _line) in contents_wide.lines().enumerate() {}

    dims.set((H, 40));
    group.tick();
    let contents_narrow = term.contents();
    for (_i, _line) in contents_narrow.lines().enumerate() {}

    // Content should differ after resize (different bar templates).
    assert_ne!(contents_wide, contents_narrow, "output changes after width resize");
}

#[test]
fn resize_width_narrow_to_wide_restores_content() {
    let dims = Arc::new(TestDimensionSource::new((H, 40)));
    let (mp, term) = mk_with_size(H, 40);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(5)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(false)
        .build_with_overall();
    let contents_narrow = term.contents();
    for (_i, _line) in contents_narrow.lines().enumerate() {}

    dims.set((H, 80));
    group.tick();
    let contents_wide = term.contents();
    for (_i, _line) in contents_wide.lines().enumerate() {}
    assert_ne!(contents_narrow, contents_wide, "output changes after width resize");
}

#[test]
fn resize_width_noop_same_width_no_change() {
    let dims = Arc::new(TestDimensionSource::new((H, W)));
    let (mp, term, ts) = mk_with_size_and_ts(H, W);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(5)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .with_time_source(ts.clone() as Arc<dyn TimeSource>)
        .dynamic_height(false)
        .build_with_overall();
    let before = term.contents();
    let before_lines = before.lines().count();
    // (no elapsed assertion before tick — elapsed is injected on tick, and
    //  we haven't ticked since constructor.)

    dims.set((H, W));
    group.tick();
    let after = term.contents();
    let after_lines = after.lines().count();
    // Same width → same number of lines, same bar template structure.
    // Content differs slightly because the spinner animates between ticks.
    assert_eq!(before_lines, after_lines, "same line count after noop width resize");
    assert!(after.contains("overall"), "overall visible after");
    assert!(after.contains("0/10"), "overall shows 0/10 after");
    assert!(after.contains("0s"), "time after");
}

#[test]
fn resize_height_grow_adds_slots() {
    let dims = Arc::new(TestDimensionSource::new((4, 80)));
    let (mp, term) = mk_with_size(6, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(4)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(true)
        .build_with_overall();
    {
        let _c1 = group.add_bar(7, "fetch");
        group.tick();
    }
    let before = term.contents();
    for (_i, _line) in before.lines().enumerate() {}
    let before_count = before.lines().count();

    dims.set((6, 80));
    group.tick();
    let after = term.contents();
    for (_i, _line) in after.lines().enumerate() {}
    let after_count = after.lines().count();
    assert!(after_count > before_count, "more lines after height growth");
}

#[test]
fn resize_height_shrink_removes_slots() {
    let dims = Arc::new(TestDimensionSource::new((6, 80)));
    let (mp, term) = mk_with_size(6, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(6)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(true)
        .build_with_overall();
    let _c1 = group.add_bar(7, "fetch");
    group.tick();

    let before_count = term.contents().lines().count();

    dims.set((4, 80));
    group.tick();
    let after_count = term.contents().lines().count();
    assert!(after_count < before_count, "fewer lines after height shrink");
}

#[test]
fn resize_height_shrink_protects_overall() {
    let dims = Arc::new(TestDimensionSource::new((6, 80)));
    let (mp, term) = mk_with_size(6, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(6)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(true)
        .build_with_overall();
    let _c1 = group.add_bar(7, "fetch");
    group.tick();
    let before = term.contents();
    for (_i, _line) in before.lines().enumerate() {}
    assert!(before.lines().any(|l| l.contains("overall")), "overall visible before resize");

    dims.set((4, 80));
    group.tick();
    let after = term.contents();
    for (_i, _line) in after.lines().enumerate() {}
    assert!(after.lines().any(|l| l.contains("overall")), "overall still visible after shrink");
}

#[test]
fn resize_height_grow_detached_reappear() {
    let dims = Arc::new(TestDimensionSource::new((4, 80)));
    let (mp, term) = mk_with_size(6, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(4)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(true)
        .build_with_overall();
    let _c1 = group.add_bar(7, "fetch");
    group.tick();

    dims.set((6, 80));
    group.tick();
    let after = term.contents();
    for (_i, _line) in after.lines().enumerate() {}
    assert!(after.lines().any(|l| l.contains("fetch")), "child still visible after growth");
    assert!(after.lines().any(|l| l.contains("overall")), "overall visible after growth");
}

#[test]
fn resize_height_clamps_at_min_slots() {
    let dims = Arc::new(TestDimensionSource::new((6, 80)));
    let (mp, term) = mk_with_size(6, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(6)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(true)
        .build_with_overall();
    let _c1 = group.add_bar(7, "fetch");
    group.tick();
    let _before_count = term.contents().lines().count();

    // Shrink to height=1 → only 1 line (overall), bar evicted to orphaned.
    dims.set((1, 80));
    group.tick();
    let after = term.contents();
    let after_count = after.lines().count();
    assert_eq!(after_count, 1, "exactly 1 line at H=1 (overall only)");
    assert!(after.contains("overall"), "overall visible at H=1");
    assert!(!after.contains("fetch"), "child evicted at H=1");
}

#[test]
fn resize_height_clamps_at_max_slots() {
    let dims = Arc::new(TestDimensionSource::new((4, 80)));
    let (mp, term) = mk_with_size(10, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(4)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(true)
        .build_with_overall();
    let _c1 = group.add_bar(7, "fetch");
    group.tick();

    // Grow to huge height → should clamp at MAX_SLOTS=200.
    dims.set((999, 80));
    group.tick();
    let after_count = term.contents().lines().count();
    // Should not have 999 lines — clamped to MAX_SLOTS.
    assert!(after_count <= 200, "at most 200 lines after extreme growth (got {after_count})");
}

#[test]
fn resize_both_dimensions() {
    let dims = Arc::new(TestDimensionSource::new((4, 80)));
    let (mp, term) = mk_with_size(6, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(4)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(true)
        .build_with_overall();
    let _c1 = group.add_bar(7, "fetch");
    group.tick();
    let before = term.contents();

    // Change both width and height at once.
    dims.set((6, 40));
    group.tick();
    let after = term.contents();
    for (_i, _line) in before.lines().enumerate() {}
    for (_i, _line) in after.lines().enumerate() {}
    assert_ne!(before, after, "output changes when both dimensions change");
}

#[test]
fn resize_then_restore_original() {
    let dims = Arc::new(TestDimensionSource::new((4, 80)));
    let (mp, term) = mk_with_size(6, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(4)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(true)
        .build_with_overall();
    let _c1 = group.add_bar(7, "fetch");
    group.tick();
    let original = term.contents();

    // Grow.
    dims.set((6, 40));
    group.tick();
    // Restore.
    dims.set((4, 80));
    group.tick();
    let restored = term.contents();
    assert_eq!(
        restored.lines().count(),
        original.lines().count(),
        "restored line count matches original"
    );
    assert!(restored.contains("overall"), "overall visible after restore");
    assert!(restored.contains("fetch"), "child visible after restore");
}

/// Shrink then grow back — verifies that a shrink–grow cycle preserves the
/// line count and both tracked bars remain visible.
#[test]
fn resize_height_shrink_then_grow_restores_line_count() {
    let dims = Arc::new(TestDimensionSource::new((6, 80)));
    let (mp, term) = mk_with_size(6, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(6)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(true)
        .build_with_overall();
    let _c1 = group.add_bar(7, "fetch");
    group.tick();
    let original_count = term.contents().lines().count();
    assert!(original_count >= 6, "at least 6 lines at H=6");

    // Shrink to H=4.
    dims.set((4, 80));
    group.tick();
    let shrunken_count = term.contents().lines().count();
    assert!(
        shrunken_count < original_count,
        "fewer lines after shrink (was {original_count}, now {shrunken_count})"
    );

    // Grow back to H=6.
    dims.set((6, 80));
    group.tick();
    let restored = term.contents();
    assert_eq!(restored.lines().count(), original_count, "restored line count matches original");
    assert!(restored.contains("overall"), "overall visible after cycle");
    assert!(restored.contains("fetch"), "child visible after cycle");
}

/// Shrink to H=3 — verifies that the render-slot count matches the
/// terminal height (3: 2 active bars + overall) and all tracked bars
/// remain visible.
#[test]
fn resize_height_partial_shrink_keeps_active_bars() {
    let dims = Arc::new(TestDimensionSource::new((6, 80)));
    let (mp, term) = mk_with_size(6, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(6)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(true)
        .build_with_overall();
    let _c1 = group.add_bar(7, "fetch1");
    let _c2 = group.add_bar(5, "fetch2");
    group.tick();

    // H=3 → 3 lines (2 active + overall, drained 3 blanks with 1 eviction).
    dims.set((3, 80));
    group.tick();
    let after = term.contents();
    for (_i, _line) in after.lines().enumerate() {}
    assert_eq!(after.lines().count(), 3, "3 lines at H=3");
    assert!(after.contains("overall"), "overall visible");
    assert!(after.contains("fetch1"), "fetch1 visible");
    assert!(after.contains("fetch2"), "fetch2 visible");
}

/// Attach a bar, shrink, then attach another bar — verifies that
/// interleaving attach with resize works correctly.
#[test]
fn resize_height_with_interleaved_attach() {
    let dims = Arc::new(TestDimensionSource::new((5, 80)));
    let (mp, term) = mk_with_size(5, 80);
    let group = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(5)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(true)
        .build();
    let _alpha = group.add_bar(10, "alpha");

    // Start with 5 lines (no overall bar).
    let before_count = term.contents().lines().count();
    assert!(before_count >= 5, "at least 5 lines at H=5");

    // Shrink to H=4 (removes 1 blank at top).
    dims.set((4, 80));
    group.tick();
    let after_shrink = term.contents();
    assert!(after_shrink.lines().count() < before_count, "fewer lines after shrink");
    assert!(after_shrink.contains("alpha"), "alpha visible after shrink");
    group.tick();

    // Attach a second bar.
    let _beta = group.add_bar(5, "beta");
    group.tick();
    let after_attach = term.contents();
    // Line count should stay at 4 (H=4).
    assert_eq!(after_attach.lines().count(), 4, "still 4 lines after attaching beta");
    assert!(after_attach.contains("alpha"), "alpha visible after attach");
    assert!(after_attach.contains("beta"), "beta visible after attach");
}

/// Shrink from H=5 to H=1 then grow back — verifies that eviction and
/// reattachment preserve chronological order across the full range.
#[test]
fn resize_height_sequence_with_three_bars() {
    let dims = Arc::new(TestDimensionSource::new((5, 80)));
    let (mp, term) = mk_with_size(5, 80);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(5)
        .with_overall("overall", 10)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(true)
        .build_with_overall();
    // Add in order: bar3 (oldest), bar2, bar1 (newest).
    let _bar3 = group.add_bar(7, "bar 3");
    let _bar2 = group.add_bar(5, "bar 2");
    let _bar1 = group.add_bar(3, "bar 1");
    group.tick();

    // H=5 → (empty), (bar 3), (bar 2), (bar 1), (overall)
    let h5 = term.contents();
    for (_i, _line) in h5.lines().enumerate() {}
    assert_eq!(h5.lines().count(), 5);
    assert!(h5.contains("bar 3"), "bar 3 visible at H=5");
    assert!(h5.contains("bar 2"), "bar 2 visible at H=5");
    assert!(h5.contains("bar 1"), "bar 1 visible at H=5");
    assert!(h5.contains("overall"), "overall visible at H=5");

    // H=4 → (bar 3), (bar 2), (bar 1), (overall) — empty slot removed
    dims.set((4, 80));
    group.tick();
    let h4 = term.contents();
    for (_i, _line) in h4.lines().enumerate() {}
    assert_eq!(h4.lines().count(), 4);
    assert!(h4.contains("bar 3"));
    assert!(h4.contains("bar 2"));
    assert!(h4.contains("bar 1"));
    assert!(h4.contains("overall"));

    // H=3 → (bar 2), (bar 1), (overall) — bar 3 evicted
    dims.set((3, 80));
    group.tick();
    let h3 = term.contents();
    for (_i, _line) in h3.lines().enumerate() {}
    assert_eq!(h3.lines().count(), 3);
    assert!(!h3.contains("bar 3"), "bar 3 evicted at H=3");
    assert!(h3.contains("bar 2"));
    assert!(h3.contains("bar 1"));
    assert!(h3.contains("overall"));

    // H=2 → (bar 1), (overall) — bar 2 evicted
    dims.set((2, 80));
    group.tick();
    let h2 = term.contents();
    for (_i, _line) in h2.lines().enumerate() {}
    assert_eq!(h2.lines().count(), 2);
    assert!(!h2.contains("bar 3"), "bar 3 still evicted at H=2");
    assert!(!h2.contains("bar 2"), "bar 2 evicted at H=2");
    assert!(h2.contains("bar 1"));
    assert!(h2.contains("overall"));

    // H=1 → (overall) — bar 1 evicted
    dims.set((1, 80));
    group.tick();
    let h1 = term.contents();
    for (_i, _line) in h1.lines().enumerate() {}
    assert_eq!(h1.lines().count(), 1);
    assert!(!h1.contains("bar 3"));
    assert!(!h1.contains("bar 2"));
    assert!(!h1.contains("bar 1"));
    assert!(h1.contains("overall"));

    // Grow back to H=4 → bar 3, bar 2, bar 1, overall (reattach in order).
    // (pop_back LIFO preserves chronological order after prepend-at-0.)
    dims.set((4, 80));
    group.tick();
    let h4_restored = term.contents();
    for (_i, _line) in h4_restored.lines().enumerate() {}
    assert_eq!(h4_restored.lines().count(), 4);
    assert!(h4_restored.contains("bar 3"), "bar 3 reappears on growth");
    assert!(h4_restored.contains("bar 2"), "bar 2 reappears on growth");
    assert!(h4_restored.contains("bar 1"), "bar 1 reappears on growth");
    assert!(h4_restored.contains("overall"));
}

/// Shrink from H=4 to H=1 (no overall bar) — verifies eviction and
/// reattachment work correctly without an overall bar.
#[test]
fn resize_height_sequence_without_overall() {
    let dims = Arc::new(TestDimensionSource::new((4, 80)));
    let (mp, term) = mk_with_size(4, 80);
    let group = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(4)
        .with_dim_source(Arc::clone(&dims) as Arc<dyn DimensionSource>)
        .dynamic_height(true)
        .build();
    let _bar2 = group.add_bar(5, "bar 2");
    let _bar1 = group.add_bar(3, "bar 1");

    // H=4 → (empty), (empty), (bar 2), (bar 1)
    let h4 = term.contents();
    for (_i, _line) in h4.lines().enumerate() {}
    assert_eq!(h4.lines().count(), 4);
    assert!(h4.contains("bar 2"), "bar 2 visible at H=4");
    assert!(h4.contains("bar 1"), "bar 1 visible at H=4");

    // H=3 → (empty), (bar 2), (bar 1) — blank removed
    dims.set((3, 80));
    group.tick();
    let h3 = term.contents();
    for (_i, _line) in h3.lines().enumerate() {}
    assert_eq!(h3.lines().count(), 3);
    assert!(h3.contains("bar 2"));
    assert!(h3.contains("bar 1"));

    // H=2 → (bar 2), (bar 1) — blank removed, all active
    dims.set((2, 80));
    group.tick();
    let h2 = term.contents();
    for (_i, _line) in h2.lines().enumerate() {}
    assert_eq!(h2.lines().count(), 2);
    assert!(h2.contains("bar 2"));
    assert!(h2.contains("bar 1"));

    // H=1 → (bar 1) — bar 2 evicted
    dims.set((1, 80));
    group.tick();
    let h1 = term.contents();
    for (_i, _line) in h1.lines().enumerate() {}
    assert_eq!(h1.lines().count(), 1);
    assert!(!h1.contains("bar 2"), "bar 2 evicted at H=1");
    assert!(h1.contains("bar 1"), "bar 1 still visible at H=1");

    // Grow back to H=3 → bar 2, bar 1 (reattach in order)
    dims.set((3, 80));
    group.tick();
    let h3_restored = term.contents();
    for (_i, _line) in h3_restored.lines().enumerate() {}
    assert_eq!(h3_restored.lines().count(), 3);
    assert!(h3_restored.contains("bar 2"), "bar 2 reappears on growth");
    assert!(h3_restored.contains("bar 1"), "bar 1 reappears on growth");
}
