// NOTE: This file was auto-generated by splitting progress_output.rs.
// Do not edit directly.

use indicatif::{InMemoryTerm, MultiProgress, ProgressBar, ProgressDrawTarget, ProgressStyle};
use mediapm_utils::progress::{
    DimensionSource, ProgressGroup, TestDimensionSource, TestTimeSource, TimeSource, TrackedHandle,
};
use std::sync::Arc;

use super::common::*;

#[test]
fn narrow_terminal_single_bar() {
    let (mp, term) = mk_with_size(24, 10);
    let pb = ProgressBar::new(4);
    pb.set_style(style_from(TN));
    pb.set_prefix("overall".to_string());
    let pb = mp.add(pb);
    pb.tick();
    assert_eq!(term.contents(), concat!(" overall\n", "0/4"));
}

#[test]
fn narrow_terminal_two_lines() {
    let (mp, term) = mk_with_size(24, 10);
    let o = ProgressBar::new(5);
    o.set_style(style_from(TN));
    o.set_prefix("overall".to_string());
    let c = ProgressBar::new(3);
    c.set_style(style_from(TN));
    c.set_prefix("tool1".to_string());
    let o = mp.add(o);
    let c = mp.insert_before(&o, c);
    c.tick();
    o.tick();
    assert_eq!(term.contents(), concat!("   tool1\n", "0/3\n", " overall\n", "0/5"),);
}

#[test]
fn wide_terminal_single_bar() {
    let (mp, term) = mk_with_size(24, 120);
    let pb = add_bar(&mp, 4, "overall");
    pb.tick();
    assert_eq!(
        term.contents(),
        concat!(
            " overall [00:00:00] ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/4",
        )
    );
}

#[test]
fn wide_terminal_two_lines() {
    let (mp, term) = mk_with_size(24, 120);
    let o = add_bar(&mp, 4, "overall");
    let c = ins_bar(&mp, &o, 2, "tool1");
    c.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "   tool1 [00:00:00] ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/2\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/4",
        )
    );
}

// ── Extreme height ───────────────────────────────────────────────────────────

#[test]
fn tall_terminal() {
    let (mp, term) = mk_with_size(50, 40);
    let o = add_bar(&mp, 3, "overall");
    let a = ins_bar(&mp, &o, 5, "tool-a");
    let b = ins_bar(&mp, &o, 3, "tool-b");
    a.tick();
    b.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "  tool-a [00:00:00] ░░░░░░░░░░░░░░░ 0/5\n",
            "  tool-b [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░░ 0/3",
        ),
    );
}

#[test]
fn short_terminal_two_lines() {
    let (mp, term) = mk_with_size(3, 40);
    let o = add_bar(&mp, 4, "overall");
    let c = ins_bar(&mp, &o, 2, "tool1");
    c.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "   tool1 [00:00:00] ░░░░░░░░░░░░░░░ 0/2\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░░ 0/4",
        ),
    );
}

#[test]
fn short_terminal_three_lines() {
    let (mp, term) = mk_with_size(3, 40);
    let o = add_bar(&mp, 3, "overall");
    let a = ins_bar(&mp, &o, 5, "tool-a");
    let b = ins_bar(&mp, &o, 3, "tool-b");
    a.tick();
    b.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "  tool-a [00:00:00] ░░░░░░░░░░░░░░░ 0/5\n",
            "  tool-b [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░░ 0/3",
        ),
    );
}

// ── Overflow ─────────────────────────────────────────────────────────────────

#[test]
fn overflow_h3_5children() {
    let (mp, term) = mk_with_size(3, 40);
    let o = add_bar(&mp, 10, "overall");
    let mut kids = Vec::new();
    for i in 0..5 {
        let p = format!("child{i}");
        let c = ins_bar(&mp, &o, 3, &p);
        c.tick();
        kids.push(c);
    }
    o.tick();
    // At H=3: first 3 children visible (child0, child1, child2).
    assert_eq!(
        term.contents(),
        concat!(
            "  child0 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child1 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child2 [00:00:00] ░░░░░░░░░░░░░░░ 0/3",
        ),
    );
}

#[test]
fn overflow_h3_5children_clear_last() {
    let (mp, term) = mk_with_size(3, 40);
    let o = add_bar(&mp, 10, "overall");
    let mut kids = Vec::new();
    for i in 0..5 {
        let p = format!("child{i}");
        let c = ins_bar(&mp, &o, 3, &p);
        c.tick();
        kids.push(c);
    }
    o.tick();
    // At H=3: first 3 children visible (child0, child1, child2).
    assert_eq!(
        term.contents(),
        concat!(
            "  child0 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child1 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child2 [00:00:00] ░░░░░░░░░░░░░░░ 0/3",
        ),
        "3 lines visible at H=3",
    );
    // Clear the last created child (child4, not visible at H=3).
    kids[4].finish_and_clear();
    kids[4].tick();
    o.tick();
    // Still only 3 lines.
    assert_eq!(
        term.contents(),
        concat!(
            "  child0 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child1 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child2 [00:00:00] ░░░░░░░░░░░░░░░ 0/3",
        ),
        "still 3 lines visible after clear",
    );
}

#[test]
fn overflow_h3_10children() {
    let (mp, term) = mk_with_size(3, 40);
    let o = add_bar(&mp, 10, "overall");
    let mut kids = Vec::new();
    for i in 0..10 {
        let p = format!("child{i}");
        let c = ins_bar(&mp, &o, 3, &p);
        c.tick();
        kids.push(c);
    }
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "  child0 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child1 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child2 [00:00:00] ░░░░░░░░░░░░░░░ 0/3",
        ),
    );
}

#[test]
fn overflow_h4_6children_finish_clear_all() {
    let (mp, term) = mk_with_size(4, 40);
    let o = add_bar(&mp, 10, "overall");
    let mut kids = Vec::new();
    for i in 0..6 {
        let p = format!("child{i}");
        let c = ins_bar(&mp, &o, 3, &p);
        c.tick();
        kids.push(c);
    }
    o.tick();
    // At H=4: first 4 children visible.
    assert_eq!(
        term.contents(),
        concat!(
            "  child0 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child1 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child2 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child3 [00:00:00] ░░░░░░░░░░░░░░░ 0/3",
        ),
    );
    // Clear children that were past the visible window.
    kids[4].finish_and_clear();
    kids[5].finish_and_clear();
    kids[4].tick();
    kids[5].tick();
    o.tick();
    // Still 4 lines.
    assert_eq!(
        term.contents(),
        concat!(
            "  child0 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child1 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child2 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child3 [00:00:00] ░░░░░░░░░░░░░░░ 0/3",
        ),
    );
}

// ── Combined stress ──────────────────────────────────────────────────────────

#[test]
fn overflow_with_spinner() {
    let (mp, term) = mk_with_size(3, 40);
    let o = add_bar(&mp, 10, "overall");
    o.set_style(spinner_style());
    let mut kids = Vec::new();
    for i in 0..5 {
        let p = format!("child{i}");
        let c = ins_bar(&mp, &o, 3, &p);
        c.set_style(spinner_style());
        c.tick();
        kids.push(c);
    }
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "⠙   child0 [00:00:00] ░░░░░░░░░░░░░ 0/3\n",
            "⠙   child1 [00:00:00] ░░░░░░░░░░░░░ 0/3\n",
            "⠙   child2 [00:00:00] ░░░░░░░░░░░░░ 0/3",
        ),
    );
}

#[test]
fn worker_surge_with_overflow() {
    let (mp, term) = mk_with_size(3, 40);
    let o = add_bar(&mp, 10, "overall");
    let mut kids = Vec::new();
    for i in 0..5 {
        let p = format!("child{i}");
        let c = ins_bar(&mp, &o, 3, &p);
        c.tick();
        kids.push(c);
    }
    o.tick();
    // At H=3: first 3 children visible.
    assert_eq!(
        term.contents(),
        concat!(
            "  child0 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child1 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child2 [00:00:00] ░░░░░░░░░░░░░░░ 0/3",
        ),
    );
    // Surge: add 5 more children.
    for i in 5..10 {
        let p = format!("child{i}");
        let c = ins_bar(&mp, &o, 3, &p);
        c.tick();
        kids.push(c);
    }
    o.tick();
    // Still only 3 lines visible.
    assert_eq!(
        term.contents(),
        concat!(
            "  child0 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child1 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  child2 [00:00:00] ░░░░░░░░░░░░░░░ 0/3",
        ),
    );
}

// ═════════════════════════════════════════════════════════════════════════════
// Phase 7: Terminal edge-case exact-output tests
// ═════════════════════════════════════════════════════════════════════════════

/// Exact output: very narrow terminal (W=5) wraps each line.
#[test]
fn terminal_exact_very_narrow_single_bar() {
    let (mp, term) = mk_with_size(24, 5);
    let pb = add_bar(&mp, 4, "test");
    pb.tick();
    assert_eq!(term.contents(), concat!("    t\n", "est [\n", "00:00\n", ":00]\n", " 0/4",),);
}

/// Exact output: child+overall at W=5 wraps across 10 short lines.
#[test]
fn terminal_exact_very_narrow_two_lines() {
    let (mp, term) = mk_with_size(24, 5);
    let o = add_bar(&mp, 5, "overall");
    let c = ins_bar(&mp, &o, 3, "tool1");
    c.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "   to\n", "ol1 [\n", "00:00\n", ":00]\n", " 0/3\n", " over\n", "all [\n", "00:00\n",
            ":00]\n", " 0/5",
        ),
    );
}

/// Exact output: H=1 shows a single non-wrapped progress bar line.
#[test]
fn terminal_exact_h1_single_bar() {
    let (mp, term) = mk_with_size(1, 40);
    let pb = add_bar(&mp, 4, "test");
    pb.tick();
    assert_eq!(term.contents(), concat!("    test [00:00:00] ░░░░░░░░░░░░░░░ 0/4"),);
}

/// Exact output: H=2 with 2 children + overall shows only 1 line (overall off-screen).
#[test]
fn terminal_exact_h2_no_overall_two_children() {
    let (mp, term) = mk_with_size(2, 40);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .with_ticker_enabled(false)
        .build_with_overall();
    let _c1 = group.add_bar(3, "alpha");
    let _c2 = group.add_bar(3, "beta");
    group.tick();
    assert_eq!(term.contents(), concat!("⠹                          alpha   0/3 0\ns 0/d"),);
}

/// Exact output: H=2 with 3 children + overall shows only 1 line.
#[test]
fn terminal_exact_h2_no_overall_overflow() {
    let (mp, term) = mk_with_size(2, 40);
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .with_ticker_enabled(false)
        .build_with_overall();
    let _c1 = group.add_bar(3, "alpha");
    let _c2 = group.add_bar(3, "beta");
    let _c3 = group.add_bar(3, "gamma");
    group.tick();
    assert_eq!(term.contents(), concat!("⠹                          alpha   0/3 0\ns 0/d"),);
}
