// NOTE: This file was auto-generated by splitting progress_output.rs.
// Do not edit directly.

use indicatif::{InMemoryTerm, MultiProgress, ProgressBar, ProgressDrawTarget, ProgressStyle};
use mediapm_utils::progress::{
    DimensionSource, ProgressGroup, TestDimensionSource, TestTimeSource, TimeSource, TrackedHandle,
};
use std::sync::Arc;

use super::common::*;

#[test]
fn transition_finish_without_clear() {
    let (mp, term) = mk();
    let o = add_bar(&mp, 5, "overall");
    let c = ins_bar(&mp, &o, 2, "tool1");
    c.tick();
    o.tick();
    c.finish();
    c.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "   tool1 [00:00:00] ███████████████ 2/2\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░░ 0/5",
        ),
    );
}

#[test]
fn transition_abandon_child() {
    let (mp, term) = mk();
    let o = add_bar(&mp, 5, "overall");
    let c = ins_bar(&mp, &o, 2, "tool1");
    c.inc(1);
    c.tick();
    o.tick();
    c.abandon_with_message("failed");
    c.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "   tool1 [00:00:00] ████░░░░░ 1/2 failed\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░░ 0/5",
        ),
    );
}

#[test]
fn transition_two_children_both_finish() {
    let (mp, term) = mk();
    let o = add_bar(&mp, 5, "overall");
    let a = ins_bar(&mp, &o, 3, "tool-a");
    let b = ins_bar(&mp, &o, 2, "tool-b");
    a.inc(3);
    b.inc(2);
    a.tick();
    b.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "  tool-a [00:00:00] ███████████████ 3/3\n",
            "  tool-b [00:00:00] ███████████████ 2/2\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░░ 0/5",
        ),
    );
}

#[test]
fn transition_child_progress_then_clear() {
    let (mp, term) = mk();
    let o = add_bar(&mp, 5, "overall");
    let child1 = ins_bar(&mp, &o, 2, "tool1");
    child1.inc(2);
    child1.finish_and_clear();
    child1.tick();
    o.tick();
    drop(child1);
    o.inc(2);
    let child2 = ins_bar(&mp, &o, 3, "tool2");
    child2.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "   tool2 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            " overall [00:00:00] ██████░░░░░░░░░ 2/5",
        ),
    );
}

#[test]
fn transition_abandon_and_reset() {
    let (mp, term) = mk();
    let o = add_bar(&mp, 5, "overall");
    let c = ins_bar(&mp, &o, 5, "tool1");
    c.inc(3);
    c.abandon_with_message("failed");
    c.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "   tool1 [00:00:00] █████░░░░ 3/5 failed\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░░ 0/5",
        ),
    );
    c.reset();
    c.set_message("");
    c.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "   tool1 [00:00:00] ░░░░░░░░░░░░░░░ 0/5\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░░ 0/5",
        ),
    );
}

#[test]
fn transition_out_of_order_clear() {
    let (mp, term) = mk();
    let o = add_bar(&mp, 5, "overall");
    let a = ins_bar(&mp, &o, 2, "tool-a");
    let b = ins_bar(&mp, &o, 2, "tool-b");
    let c = ins_bar(&mp, &o, 2, "tool-c");
    a.tick();
    b.tick();
    c.tick();
    o.tick();
    b.finish_and_clear();
    b.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "  tool-a [00:00:00] ░░░░░░░░░░░░░░░ 0/2\n",
            "  tool-c [00:00:00] ░░░░░░░░░░░░░░░ 0/2\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░░ 0/5",
        ),
    );
}

#[test]
fn transition_child_abandoned_new_child() {
    let (mp, term) = mk();
    let o = add_bar(&mp, 5, "overall");
    let c = ins_bar(&mp, &o, 2, "tool1");
    c.inc(1);
    c.abandon_with_message("failed");
    c.tick();
    o.tick();
    c.finish_and_clear();
    c.tick();
    o.tick();
    drop(c);
    let c2 = ins_bar(&mp, &o, 2, "tool2");
    c2.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "   tool2 [00:00:00] ░░░░░░░░░░░░░░░ 0/2\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░░ 0/5",
        ),
    );
}

#[test]
fn transition_two_children_one_finishes_one_clears() {
    let (mp, term) = mk();
    let o = add_bar(&mp, 5, "overall");
    let a = ins_bar(&mp, &o, 3, "tool-a");
    let b = ins_bar(&mp, &o, 2, "tool-b");
    a.inc(3);
    a.finish();
    b.finish_and_clear();
    a.tick();
    b.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "  tool-a [00:00:00] ███████████████ 3/3\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░░ 0/5",
        ),
    );
}

// ═════════════════════════════════════════════════════════════════════════════
// Phase 5: Lifecycle exact-output tests
// ═════════════════════════════════════════════════════════════════════════════

/// Exact output: child finishes with error, overall unchanged.
#[test]
fn transition_exact_finish_error_with_overall() {
    let term = InMemoryTerm::new(2, 80);
    let target = ProgressDrawTarget::term_like(Box::new(term.clone()));
    let mp = MultiProgress::with_draw_target(target);
    let ts = Arc::new(TestTimeSource::new());
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .with_time_source(ts.clone() as Arc<dyn TimeSource>)
        .build_with_overall();
    let child = group.add_bar(5, "child");
    child.set_position(3);
    ts.advance(std::time::Duration::from_secs(1));
    group.tick();
    child.finish_error();
    ts.advance(std::time::Duration::from_secs(1));
    group.tick();

    assert_eq!(
        term.contents(),
        concat!(
            "⠏                 [F] child ████████████░░░░░░░░░  3/5 1s\n",
            "⠼                   overall ░░░░░░░░░░░░░░░░░░░░░  0/1 2s 0/d",
        )
    );
}

/// Exact output: child abandons with overall.
#[test]
fn transition_exact_abandon_with_overall() {
    let term = InMemoryTerm::new(2, 80);
    let target = ProgressDrawTarget::term_like(Box::new(term.clone()));
    let mp = MultiProgress::with_draw_target(target);
    let ts = Arc::new(TestTimeSource::new());
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .with_time_source(ts.clone() as Arc<dyn TimeSource>)
        .build_with_overall();
    let child = group.add_bar(5, "child");
    child.set_position(3);
    ts.advance(std::time::Duration::from_secs(1));
    group.tick();
    child.abandon();
    ts.advance(std::time::Duration::from_secs(1));
    group.tick();

    assert_eq!(
        term.contents(),
        concat!(
            "⠏                 [A] child ████████████░░░░░░░░░  3/5 1s\n",
            "⠼                   overall ░░░░░░░░░░░░░░░░░░░░░  0/1 2s 0/d",
        )
    );
}

/// Exact output: child finishes success with overall, full bar, no brackets.
#[test]
fn transition_exact_success_with_overall() {
    let term = InMemoryTerm::new(2, 80);
    let target = ProgressDrawTarget::term_like(Box::new(term.clone()));
    let mp = MultiProgress::with_draw_target(target);
    let ts = Arc::new(TestTimeSource::new());
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(2)
        .with_overall("overall", 1)
        .with_time_source(ts.clone() as Arc<dyn TimeSource>)
        .build_with_overall();
    let child = group.add_bar(5, "child");
    child.set_position(5);
    ts.advance(std::time::Duration::from_secs(1));
    group.tick();
    child.finish_success();
    ts.advance(std::time::Duration::from_secs(1));
    group.tick();

    assert_eq!(
        term.contents(),
        concat!(
            "⠏                     child █████████████████████  5/5 1s\n",
            "⠼                   overall ░░░░░░░░░░░░░░░░░░░░░  0/1 2s 0/d",
        )
    );
}
