// NOTE: This file was auto-generated by splitting progress_output.rs.
// Do not edit directly.

use indicatif::{InMemoryTerm, MultiProgress, ProgressBar, ProgressDrawTarget, ProgressStyle};
use mediapm_utils::progress::{
    DimensionSource, ProgressGroup, TestDimensionSource, TestTimeSource, TimeSource, TrackedHandle,
};
use std::sync::Arc;

use super::common::*;

#[test]
fn worker_count_grow() {
    let (mp, term) = mk();
    let o = add_bar(&mp, 10, "overall");
    let c1 = ins_bar(&mp, &o, 2, "tool1");
    let c2 = ins_bar(&mp, &o, 3, "tool2");
    let c3 = ins_bar(&mp, &o, 1, "tool3");
    c1.tick();
    c2.tick();
    c3.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "   tool1 [00:00:00] ░░░░░░░░░░░░░░░ 0/2\n",
            "   tool2 [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "   tool3 [00:00:00] ░░░░░░░░░░░░░░░ 0/1\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░ 0/10",
        ),
    );
}

#[test]
fn worker_count_shrink() {
    let (mp, term) = mk();
    let o = add_bar(&mp, 10, "overall");
    let a = ins_bar(&mp, &o, 3, "tool-a");
    let b = ins_bar(&mp, &o, 2, "tool-b");
    let c = ins_bar(&mp, &o, 1, "tool-c");
    a.tick();
    b.tick();
    c.tick();
    o.tick();
    b.finish_and_clear();
    b.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "  tool-a [00:00:00] ░░░░░░░░░░░░░░░ 0/3\n",
            "  tool-c [00:00:00] ░░░░░░░░░░░░░░░ 0/1\n",
            " overall [00:00:00] ░░░░░░░░░░░░░░ 0/10",
        ),
    );
}

#[test]
fn worker_count_surge_drain() {
    let (mp, term) = mk();
    let o = add_bar(&mp, 5, "overall");
    let mut kids = Vec::new();
    for i in 0..5 {
        let name = format!("t{i:02}");
        let c = ins_bar(&mp, &o, 1, &name);
        c.inc(1);
        c.finish_and_clear();
        c.tick();
        kids.push(c);
    }
    o.inc(5);
    o.tick();
    assert_eq!(term.contents(), " overall [00:00:00] ███████████████ 5/5");
}

#[test]
fn worker_count_new_batch() {
    let (mp, term) = mk();
    let o = add_bar(&mp, 10, "overall");
    let a = ins_bar(&mp, &o, 2, "tool1");
    let b = ins_bar(&mp, &o, 2, "tool2");
    a.finish_and_clear();
    b.finish_and_clear();
    a.tick();
    b.tick();
    o.tick();
    drop(a);
    drop(b);
    o.inc(4);
    let c = ins_bar(&mp, &o, 2, "tool3");
    let d = ins_bar(&mp, &o, 1, "tool4");
    c.tick();
    d.tick();
    o.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "   tool3 [00:00:00] ░░░░░░░░░░░░░░░ 0/2\n",
            "   tool4 [00:00:00] ░░░░░░░░░░░░░░░ 0/1\n",
            " overall [00:00:00] █████░░░░░░░░░ 4/10",
        ),
    );
}

// ── Many simultaneous bars ────────────────────────────────────────────────────

#[test]
fn many_bars_fifty() {
    let (mp, term) = mk_with_size(55, 40);
    let o = add_bar(&mp, 50, "overall");
    let mut kids = Vec::new();
    for i in 0..50 {
        let p = format!("t{i:02}");
        let c = ins_bar(&mp, &o, 1, &p);
        c.tick();
        kids.push(c);
    }
    o.tick();
    let contents = term.contents();
    let lines: Vec<&str> = contents.lines().collect();
    assert_eq!(lines.len(), 51, "50 children + 1 overall = 51 lines");
    assert_eq!(lines[0], "     t00 [00:00:00] ░░░░░░░░░░░░░░░ 0/1");
    assert_eq!(lines[49], "     t49 [00:00:00] ░░░░░░░░░░░░░░░ 0/1");
    assert_eq!(lines[50], " overall [00:00:00] ░░░░░░░░░░░░░░ 0/50");
}

#[test]
fn many_bars_hundred() {
    let (mp, term) = mk_with_size(105, 40);
    let o = add_bar(&mp, 100, "overall");
    let mut kids = Vec::new();
    for i in 0..100 {
        let p = format!("t{i:02}");
        let c = ins_bar(&mp, &o, 1, &p);
        c.tick();
        kids.push(c);
    }
    o.tick();
    let contents = term.contents();
    let lines: Vec<&str> = contents.lines().collect();
    assert_eq!(lines.len(), 101, "100 children + 1 overall = 101 lines");
    assert_eq!(lines[0], "     t00 [00:00:00] ░░░░░░░░░░░░░░░ 0/1");
    assert_eq!(lines[99], "     t99 [00:00:00] ░░░░░░░░░░░░░░░ 0/1");
    assert_eq!(lines[100], " overall [00:00:00] ░░░░░░░░░░░░░ 0/100");
}

// ═════════════════════════════════════════════════════════════════════════════
// Phase 6: Worker exact-output tests
// ═════════════════════════════════════════════════════════════════════════════

/// Exact output: 3 workers with mixed finish states + overall.
#[test]
fn worker_exact_mixed_finish_states() {
    let (mp, term) = mk_with_size(5, 80);
    let (group, overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(4)
        .with_overall("overall", 3)
        .with_ticker_enabled(false)
        .build_with_overall();
    let c1 = group.add_bar(2, "worker-a");
    let c2 = group.add_bar(2, "worker-b");
    let c3 = group.add_bar(2, "worker-c");
    c1.advance(2);
    c1.finish_success();
    c2.set_position(1);
    c2.finish_error();
    c3.set_position(1);
    c3.abandon();
    overall.advance(3);
    overall.finish();
    group.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "⠏                       worker-a █████████████████████  2/2 0s\n",
            "⠏                   [F] worker-b ██████████░░░░░░░░░░░  1/2 0s\n",
            "⠏                   [A] worker-c ██████████░░░░░░░░░░░  1/2 0s\n",
            "⠏                        overall █████████████████████  3/3 0s",
        ),
    );
}

/// Exact output: all 3 workers + overall finish successfully.
#[test]
fn worker_exact_all_finish_with_overall() {
    let (mp, term) = mk_with_size(5, 80);
    let (group, overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(4)
        .with_overall("overall", 3)
        .with_ticker_enabled(false)
        .build_with_overall();
    let c1 = group.add_bar(2, "worker-a");
    let c2 = group.add_bar(2, "worker-b");
    let c3 = group.add_bar(2, "worker-c");
    c1.advance(2);
    c1.finish_success();
    c2.advance(2);
    c2.finish_success();
    c3.advance(2);
    c3.finish_success();
    overall.advance(3);
    overall.finish();
    group.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "⠏                       worker-a █████████████████████  2/2 0s\n",
            "⠏                       worker-b █████████████████████  2/2 0s\n",
            "⠏                       worker-c █████████████████████  2/2 0s\n",
            "⠏                        overall █████████████████████  3/3 0s",
        ),
    );
}

/// Exact output: 2 workers with interleaved advance rates.
#[test]
fn worker_exact_interleaved_advances() {
    let (mp, term) = mk_with_size(5, 80);
    let ts = Arc::new(TestTimeSource::new());
    let (group, overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(4)
        .with_overall("overall", 10)
        .with_time_source(ts.clone())
        .with_ticker_enabled(false)
        .build_with_overall();
    let c1 = group.add_bar(10, "fast");
    let c2 = group.add_bar(10, "slow");
    c1.set_position(8);
    c2.set_position(3);
    overall.advance(11);
    ts.advance(std::time::Duration::from_secs(1));
    group.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "\n",
            "⠸                           fast ████████████████░░░░░  8/10 1s 48/m 2s\n",
            "⠼                           slow ██████░░░░░░░░░░░░░░░  3/10 1s 18/m 23s\n",
            "⠹                        overall █████████████████████  11/10 1s 1.1/s",
        ),
    );
}

/// Exact output: 3 children, no overall bar visible (pushed off-screen at H=4).
#[test]
fn worker_exact_no_overall_multiple_children() {
    let (mp, term) = mk_with_size(4, 80);
    let ts = Arc::new(TestTimeSource::new());
    let (group, _overall) = ProgressGroup::builder()
        .with_multi_progress(mp)
        .capacity(3)
        .with_overall("overall", 1)
        .with_time_source(ts.clone())
        .with_ticker_enabled(false)
        .build_with_overall();
    let c1 = group.add_bar(5, "child-a");
    let c2 = group.add_bar(5, "child-b");
    let c3 = group.add_bar(5, "child-c");
    c1.set_position(2);
    c2.set_position(4);
    c3.set_position(5);
    ts.advance(std::time::Duration::from_millis(1));
    group.tick();
    assert_eq!(
        term.contents(),
        concat!(
            "⠸                        child-a ████████░░░░░░░░░░░░░  2/5 0s 0/d\n",
            "⠼                        child-b ████████████████░░░░░  4/5 0s 0/d\n",
            "⠹                        overall ░░░░░░░░░░░░░░░░░░░░░  0/1 0s 0/d",
        ),
    );
}
