//! Native Phase-3 metadata tagging pipeline.
//!
//! This module replaces the legacy external Picard step with an internal
//! `mediapm` flow:
//! 1. decode input audio and compute Chromaprint fingerprint,
//! 2. resolve MBIDs through AcoustID,
//! 3. fetch rich recording/release payloads through `musicbrainz_rs`,
//! 4. map metadata into `FFmetadata` key/value pairs,
//! 5. persist one `FFmetadata` document for downstream apply stages.
//!
//! Failure policy is controlled by `strict_identification`: when enabled,
//! unresolved identity or metadata-fetch failures abort the step; when disabled,
//! an empty `FFmetadata` document is written so downstream apply stages may
//! continue deterministically.
//! AcoustID lookup itself is only attempted when no recording MBID override is
//! supplied. Missing/empty lookup credentials are a hard error on that
//! autodetection path; when credentials are provided, lookup/authentication
//! failures are surfaced as hard errors.

#![allow(clippy::doc_markdown)]

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{Context, bail};
use chromaprint::{Algorithm, fingerprint_audio};
use ffmetadata::FFMetadata;
use mediapm_cas::{CasApi, FileSystemCas, Hash};
use musicbrainz_rs::entity::recording::Recording;
use musicbrainz_rs::entity::release::Release;
use musicbrainz_rs::prelude::*;
use serde::{Deserialize, Serialize, de::DeserializeOwned};
use serde_json::Value;
use tokio::process::Command;
use tokio::time::sleep;

use crate::http_client::shared_http_client;

/// Default AcoustID lookup endpoint used by the internal tagger.
pub const DEFAULT_ACOUSTID_ENDPOINT: &str = "https://api.acoustid.org/v2/lookup";
/// Default MusicBrainz API endpoint label used for diagnostics.
pub const DEFAULT_MUSICBRAINZ_ENDPOINT: &str = "https://musicbrainz.org/ws/2";

/// Target sample rate used for deterministic fingerprint extraction.
const FINGERPRINT_SAMPLE_RATE: u32 = 44_100;
/// Target channel count used for deterministic fingerprint extraction.
const FINGERPRINT_CHANNELS: u16 = 2;
/// Environment variable fallback for AcoustID API credentials.
const ACOUSTID_API_KEY_ENV: &str = "ACOUSTID_API_KEY";
/// Executable name used for decode/export metadata operations.
const FFMPEG_EXECUTABLE: &str = "ffmpeg";
/// Optional env-var override for ffmpeg executable used by internal tagger.
pub const MEDIA_TAGGER_FFMPEG_BIN_ENV: &str = "MEDIAPM_MEDIA_TAGGER_FFMPEG_BIN";
/// Maximum metadata entries emitted to `FFmetadata` output.
const MAX_FLATTENED_METADATA_ENTRIES: usize = 1_024;
/// Maximum flattened metadata value length to avoid runaway tags.
const MAX_FLATTENED_VALUE_LEN: usize = 4_096;
/// Default number of cover-art attachment slots prepared per invocation.
pub const DEFAULT_COVER_ART_SLOT_COUNT: usize = 63;
/// Default media-tagger HTTP cache expiry budget in seconds (one day).
pub const DEFAULT_CACHE_EXPIRY_SECONDS: i64 = 24 * 60 * 60;
/// Cache-index format marker for media-tagger JSONC metadata rows.
const MEDIA_TAGGER_CACHE_INDEX_VERSION: u32 = 1;
/// Default media-tagger metadata index file name under cache root.
const MEDIA_TAGGER_CACHE_INDEX_FILE_NAME: &str = "media-tagger.jsonc";
/// Retry count for transient media-tagger HTTP request failures.
const MEDIA_TAGGER_HTTP_RETRY_ATTEMPTS: usize = 3;
/// Initial retry backoff for transient media-tagger HTTP request failures.
const MEDIA_TAGGER_HTTP_RETRY_BASE_DELAY_MILLIS: u64 = 250;

/// Returns deterministic sandbox-artifact file name for one cover-art slot payload.
#[must_use]
pub(crate) fn cover_art_slot_image_member_name(slot_index: usize) -> String {
    format!("coverart-slot-{slot_index}.bin")
}

/// Returns deterministic sandbox-artifact file name for one cover-art slot flag.
#[must_use]
pub(crate) fn cover_art_slot_flag_member_name(slot_index: usize) -> String {
    format!("coverart-slot-{slot_index}.flag")
}

/// Runtime options for one internal media-tagger invocation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InternalMediaTaggerOptions {
    /// Optional input media path to inspect and tag.
    ///
    /// This is required only for fingerprint-based autodetection paths.
    pub input_path: Option<PathBuf>,
    /// Output `FFmetadata` path generated by this metadata-fetch stage.
    pub output_path: PathBuf,
    /// Optional AcoustID API key override.
    pub acoustid_api_key: Option<String>,
    /// AcoustID lookup endpoint.
    pub acoustid_endpoint: String,
    /// MusicBrainz API endpoint used in diagnostics.
    pub musicbrainz_endpoint: String,
    /// Optional media-tagger HTTP cache root directory.
    ///
    /// When provided, endpoint and cover-art payload responses are cached
    /// through one shared cache layout:
    /// - `<cache_dir>/store/` CAS payload objects,
    /// - `<cache_dir>/media-tagger.jsonc` key-to-hash metadata index.
    ///
    /// This keeps media-tagger cache semantics aligned with the workspace/user
    /// managed cache model and avoids dedicated per-tool directories inside
    /// `store/`.
    pub cache_dir: Option<PathBuf>,
    /// Cache expiry budget in seconds.
    ///
    /// Negative values disable cache expiry and keep rows indefinitely.
    pub cache_expiry_seconds: i64,
    /// Whether unresolved identity should fail the invocation.
    pub strict_identification: bool,
    /// Whether to emit extended `Picard`-compatible tags from available payloads.
    pub write_all_tags: bool,
    /// Whether to enrich metadata with `Picard`-compatible `coverart_*` tags.
    pub write_all_images: bool,
    /// Number of deterministic cover-art slots emitted for downstream apply.
    ///
    /// Managed workflow synthesis binds ffmpeg cover-image inputs to these
    /// slot files, so the internal tagger always writes all slot members:
    /// populated slots carry image bytes and "true" flags, unused slots carry
    /// empty payloads and empty flags.
    pub cover_art_slot_count: usize,
    /// Optional direct recording MBID override.
    pub recording_mbid: Option<String>,
    /// Optional direct release MBID override.
    pub release_mbid: Option<String>,
}

/// Executes one full internal tagging pipeline.
///
/// # Errors
///
/// Returns an error when metadata identification/fetching fails in strict mode,
/// when fallback metadata output cannot be written, or when upstream tool/API
/// calls fail in a way that prevents deterministic output generation.
pub async fn run_internal_media_tagger(options: InternalMediaTaggerOptions) -> anyhow::Result<()> {
    if let Some(input_path) = options.input_path.as_ref()
        && !input_path.exists()
    {
        bail!("input media path '{}' does not exist", input_path.display());
    }

    let output_path = options.output_path.clone();
    let fallback_input = options.input_path.clone();
    match run_internal_media_tagger_impl(options).await {
        Ok(()) => Ok(()),
        Err(error) => {
            let fallback_map = fallback_ffmetadata_map(fallback_input.as_deref()).await;
            if let Err(write_error) = write_ffmetadata_document(&output_path, &fallback_map) {
                return Err(error.context(format!(
                    "failed to persist fallback ffmetadata output '{}' after tagging error: {write_error}",
                    output_path.display()
                )));
            }

            Err(error)
        }
    }
}

/// Executes one full internal tagging pipeline without fallback-output handling.
#[expect(
    clippy::too_many_lines,
    reason = "this item intentionally keeps end-to-end tagging flow explicit for maintainability"
)]
async fn run_internal_media_tagger_impl(options: InternalMediaTaggerOptions) -> anyhow::Result<()> {
    let resolved_input = options
        .input_path
        .as_ref()
        .map(|input_path| input_path.canonicalize().unwrap_or_else(|_| input_path.clone()));
    let media_tagger_cache = MediaTaggerHttpCache::new(
        options.cache_dir.clone(),
        CacheExpiryPolicy::from_seconds(options.cache_expiry_seconds),
    );
    let mut detected_recording_mbid = normalize_optional_text(options.recording_mbid.as_deref());
    let mut detected_release_mbid = normalize_optional_text(options.release_mbid.as_deref());

    if detected_recording_mbid.is_none() {
        let Some(resolved_input) = resolved_input.as_ref() else {
            bail!(
                "input media is required when --recording-mbid is not provided (fingerprint autodetection path)"
            );
        };

        let acoustid_api_key = require_acoustid_api_key_for_lookup(resolve_acoustid_api_key(
            options.acoustid_api_key.as_deref(),
        ))?;
        let fingerprint_payload = decode_and_fingerprint_audio(resolved_input)
            .await
            .context("decoding media for fingerprinting")?;
        let match_result = lookup_acoustid_match(
            &options.acoustid_endpoint,
            &acoustid_api_key,
            &fingerprint_payload.fingerprint,
            fingerprint_payload.duration_seconds,
        )
        .await
        .with_context(|| {
            format!(
                "resolving recording identity through AcoustID endpoint '{}'",
                options.acoustid_endpoint
            )
        })?;

        detected_recording_mbid = detected_recording_mbid.or(match_result.recording_mbid);
        detected_release_mbid = detected_release_mbid.or(match_result.release_mbid);
    }

    let Some(recording_mbid) = detected_recording_mbid else {
        if options.strict_identification {
            bail!(
                "could not resolve recording MBID (set --recording-mbid or provide AcoustID API key via --acoustid-api-key/{ACOUSTID_API_KEY_ENV})"
            );
        }

        let fallback_map = fallback_ffmetadata_map(resolved_input.as_deref()).await;
        write_ffmetadata_document(&options.output_path, &fallback_map)?;
        return Ok(());
    };

    let metadata_payload =
        fetch_musicbrainz_payloads(&recording_mbid, detected_release_mbid.as_deref())
            .await
            .with_context(|| {
                format!(
                    "fetching MusicBrainz entities from '{}' for recording '{}'",
                    options.musicbrainz_endpoint, recording_mbid
                )
            });

    let metadata_payload = match metadata_payload {
        Ok(payload) => payload,
        Err(error) => {
            if options.strict_identification {
                return Err(error);
            }
            let fallback_map = fallback_ffmetadata_map(resolved_input.as_deref()).await;
            write_ffmetadata_document(&options.output_path, &fallback_map)?;
            return Ok(());
        }
    };

    let mut ffmetadata_map = build_ffmetadata_map(&metadata_payload, options.write_all_tags)
        .context("building FFmetadata mapping from MusicBrainz payload")?;

    let mut selected_cover_art = Vec::new();
    if options.write_all_images {
        selected_cover_art = collect_musicbrainz_cover_art(&metadata_payload, &media_tagger_cache)
            .await
            .context("collecting MusicBrainz cover-art entries")?;
        insert_musicbrainz_image_tags(&mut ffmetadata_map, &selected_cover_art);
    }

    if let Some(input_path) = resolved_input.as_deref() {
        let existing_metadata = extract_existing_ffmetadata_map(input_path).await?;
        if !existing_metadata.is_empty() {
            let mut merged = existing_metadata;
            for (key, value) in ffmetadata_map {
                merged.insert(key, value);
            }
            ffmetadata_map = merged;
        }
    }

    if ffmetadata_map.is_empty() {
        if options.strict_identification {
            bail!("resolved metadata payload did not produce any FFmetadata entries");
        }
        let fallback_map = fallback_ffmetadata_map(resolved_input.as_deref()).await;
        write_ffmetadata_document(&options.output_path, &fallback_map)?;
        return Ok(());
    }

    persist_cover_art_slot_artifacts(
        &options.output_path,
        &selected_cover_art,
        options.cover_art_slot_count,
        &media_tagger_cache,
    )
    .await
    .context("writing media-tagger cover-art slot artifacts")?;

    write_ffmetadata_document(&options.output_path, &ffmetadata_map)
}

/// Builds fallback FFmetadata content from existing input media metadata.
///
/// When input media is available, fallback output should preserve existing tags
/// to avoid destructive metadata clears in downstream ffmpeg apply stages.
async fn fallback_ffmetadata_map(input_path: Option<&Path>) -> BTreeMap<String, String> {
    let Some(input_path) = input_path else {
        return BTreeMap::new();
    };

    extract_existing_ffmetadata_map(input_path).await.unwrap_or_default()
}

/// Extracts current global metadata from one media file through ffmpeg
/// FFmetadata export and decodes it into a key/value map.
async fn extract_existing_ffmetadata_map(
    input_path: &Path,
) -> anyhow::Result<BTreeMap<String, String>> {
    let ffmpeg_executable = resolve_ffmpeg_executable();
    let output = Command::new(&ffmpeg_executable)
        .arg("-v")
        .arg("error")
        .arg("-i")
        .arg(input_path)
        // Skip codec initialization: the FFmetadata muxer reads only
        // container-level tags and does not need to decode any streams.
        .arg("-vn")
        .arg("-an")
        .arg("-sn")
        .arg("-dn")
        .arg("-f")
        .arg("ffmetadata")
        .arg("-")
        .output()
        .await
        .with_context(|| {
            format!(
                "running '{ffmpeg_executable}' to extract existing metadata from '{}'",
                input_path.display()
            )
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!(
            "ffmpeg metadata extraction failed for '{}' with status {}: {stderr}",
            input_path.display(),
            output.status
        );
    }

    let text = String::from_utf8(output.stdout).with_context(|| {
        format!(
            "ffmpeg metadata extraction output for '{}' was not valid UTF-8",
            input_path.display()
        )
    })?;

    Ok(parse_ffmetadata_global_map(&text))
}

/// Parses ffmpeg `-f ffmetadata -` output into a global metadata map.
fn parse_ffmetadata_global_map(document: &str) -> BTreeMap<String, String> {
    let mut metadata = BTreeMap::new();
    for raw_line in document.lines() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with(';') {
            continue;
        }
        if line.starts_with('[') {
            break;
        }
        let Some((raw_key, raw_value)) = line.split_once('=') else {
            continue;
        };

        let key = decode_ffmetadata_escape(raw_key);
        let value = decode_ffmetadata_escape(raw_value);
        if key.trim().is_empty() || value.trim().is_empty() {
            continue;
        }
        metadata.insert(key, value);
    }

    metadata
}

/// Decodes ffmetadata backslash escapes for one scalar key/value text fragment.
fn decode_ffmetadata_escape(value: &str) -> String {
    let mut decoded = String::new();
    let mut chars = value.chars();
    while let Some(character) = chars.next() {
        if character == '\\' {
            if let Some(next) = chars.next() {
                decoded.push(next);
            }
            continue;
        }
        decoded.push(character);
    }
    decoded
}

/// Decoded fingerprint payload plus AcoustID request duration hint.
#[derive(Debug, Clone, PartialEq, Eq)]
struct FingerprintPayload {
    /// Encoded Chromaprint fingerprint string used by AcoustID lookup.
    fingerprint: String,
    /// Rounded audio duration in whole seconds.
    duration_seconds: u32,
}

/// Resolves AcoustID API key from CLI override or environment.
fn resolve_acoustid_api_key(override_value: Option<&str>) -> Option<String> {
    if let Some(override_value) = override_value {
        if let Some(value) = normalize_optional_text(Some(override_value)) {
            return Some(value);
        }

        // An explicit blank override intentionally disables environment
        // fallback so callers can force the "missing-key" flow.
        return None;
    }

    if let Some(value) = std::env::var_os(ACOUSTID_API_KEY_ENV)
        .and_then(|value| value.into_string().ok())
        .and_then(|value| normalize_optional_text(Some(&value)))
    {
        return Some(value);
    }

    None
}

/// Enforces that AcoustID autodetection has a non-empty API key.
///
/// The lookup path is entered only when callers omit `recording_mbid`.
/// At that point, missing credentials represent a configuration error:
/// runtime would otherwise silently disable autodetection and surprise users.
///
/// In `mediapm sync` executions, the internal media-tagger runs as a managed
/// executable tool under conductor. In that mode, operators typically need to
/// include `ACOUSTID_API_KEY` in `runtime.inherited_env_vars` so the tool
/// subprocess can read it from environment.
fn require_acoustid_api_key_for_lookup(resolved_key: Option<String>) -> anyhow::Result<String> {
    let Some(api_key) = resolved_key else {
        bail!(
            "AcoustID lookup requires a non-empty API key; set --acoustid-api-key or {ACOUSTID_API_KEY_ENV} (for mediapm sync workflows, ensure runtime.inherited_env_vars includes {ACOUSTID_API_KEY_ENV})"
        );
    };

    Ok(api_key)
}

/// Runs `ffmpeg` decode + Chromaprint fingerprint generation for one media file.
async fn decode_and_fingerprint_audio(input_path: &Path) -> anyhow::Result<FingerprintPayload> {
    let ffmpeg_executable = resolve_ffmpeg_executable();
    let output = Command::new(&ffmpeg_executable)
        .arg("-v")
        .arg("error")
        .arg("-i")
        .arg(input_path)
        .arg("-vn")
        .arg("-f")
        .arg("s16le")
        .arg("-ac")
        .arg(FINGERPRINT_CHANNELS.to_string())
        .arg("-ar")
        .arg(FINGERPRINT_SAMPLE_RATE.to_string())
        .arg("-")
        .output()
        .await
        .with_context(|| {
            format!("running '{ffmpeg_executable}' to decode '{}'", input_path.display())
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!(
            "ffmpeg decode failed for '{}' with status {}: {stderr}",
            input_path.display(),
            output.status
        );
    }

    if output.stdout.is_empty() {
        bail!("ffmpeg decode for '{}' produced no PCM bytes", input_path.display());
    }

    let samples = output
        .stdout
        .chunks_exact(2)
        .map(|chunk| i16::from_le_bytes([chunk[0], chunk[1]]))
        .collect::<Vec<_>>();

    if samples.is_empty() {
        bail!("decoded PCM sample stream is empty");
    }

    let fingerprint = fingerprint_audio(
        &samples,
        FINGERPRINT_SAMPLE_RATE,
        FINGERPRINT_CHANNELS,
        Algorithm::default(),
    )
    .context("computing chromaprint fingerprint")?;

    let encoded_fingerprint = fingerprint.encoded().to_string();
    let sample_count = u128::try_from(samples.len()).unwrap_or(u128::MAX);
    let samples_per_second = u128::from(FINGERPRINT_SAMPLE_RATE) * u128::from(FINGERPRINT_CHANNELS);
    let rounded_seconds = ((sample_count + (samples_per_second / 2)) / samples_per_second).max(1);
    let duration_seconds = u32::try_from(rounded_seconds).unwrap_or(u32::MAX);

    Ok(FingerprintPayload { fingerprint: encoded_fingerprint, duration_seconds })
}

/// AcoustID API response payload.
#[derive(Debug, Deserialize)]
struct AcoustIdLookupResponse {
    /// API status string (`ok` on success).
    status: String,
    /// Candidate matches returned by AcoustID.
    #[serde(default)]
    results: Vec<AcoustIdResult>,
}

/// Wire-format query parameters for AcoustID lookup.
#[derive(Debug, Serialize)]
struct AcoustIdLookupQuery<'a> {
    /// API key issued by AcoustID.
    client: &'a str,
    /// Requested lookup metadata projections.
    meta: &'a str,
    /// Rounded clip duration in seconds.
    duration: u32,
    /// Encoded Chromaprint fingerprint text.
    fingerprint: &'a str,
    /// Output response format.
    format: &'a str,
}

/// One AcoustID candidate match.
#[derive(Debug, Deserialize)]
struct AcoustIdResult {
    /// Match confidence score in `[0, 1]`.
    score: Option<f64>,
    /// Candidate recordings for this fingerprint match.
    #[serde(default)]
    recordings: Vec<AcoustIdRecording>,
}

/// Recording payload returned in AcoustID lookup metadata.
#[derive(Debug, Deserialize)]
struct AcoustIdRecording {
    /// MusicBrainz recording identifier.
    id: String,
    /// Optional release candidates linked to this recording.
    #[serde(default)]
    releases: Vec<AcoustIdRelease>,
}

/// Release payload returned in AcoustID lookup metadata.
#[derive(Debug, Deserialize)]
struct AcoustIdRelease {
    /// MusicBrainz release identifier.
    id: String,
}

/// Selected AcoustID match values used for downstream fetches.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
struct AcoustIdMatch {
    /// Selected recording MBID, when available.
    recording_mbid: Option<String>,
    /// Selected release MBID, when available.
    release_mbid: Option<String>,
}

/// Calls AcoustID lookup API and returns highest-scoring MBID pair.
async fn lookup_acoustid_match(
    endpoint: &str,
    api_key: &str,
    fingerprint: &str,
    duration_seconds: u32,
) -> anyhow::Result<AcoustIdMatch> {
    let http_client = shared_http_client()
        .map_err(|error| anyhow::anyhow!("initializing shared HTTP client failed: {error}"))?;

    let payload = http_client
        .get(endpoint)
        .query(&AcoustIdLookupQuery {
            client: api_key,
            meta: "recordings releases releasegroups tracks compress usermeta sources",
            duration: duration_seconds,
            fingerprint,
            format: "json",
        })
        .send()
        .await
        .context("sending AcoustID lookup request")?
        .error_for_status()
        .context("AcoustID lookup returned non-success status")?
        .text()
        .await
        .context("reading AcoustID lookup response body")?;

    let response = serde_json::from_str::<AcoustIdLookupResponse>(&payload)
        .context("decoding AcoustID lookup response JSON")?;

    if !response.status.eq_ignore_ascii_case("ok") {
        bail!("AcoustID lookup returned status '{}'", response.status);
    }

    let mut ordered_results = response.results;
    ordered_results.sort_by(|left, right| {
        right
            .score
            .unwrap_or_default()
            .partial_cmp(&left.score.unwrap_or_default())
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    let Some(best) = ordered_results.into_iter().next() else {
        return Ok(AcoustIdMatch::default());
    };

    let Some(recording) = best.recordings.into_iter().find(|recording| !recording.id.is_empty())
    else {
        return Ok(AcoustIdMatch::default());
    };

    let release_mbid: Option<String> = recording
        .releases
        .into_iter()
        .map(|release| release.id)
        .find(|value| !value.trim().is_empty());

    Ok(AcoustIdMatch { recording_mbid: Some(recording.id), release_mbid })
}

/// Recording + optional release payload fetched from MusicBrainz.
#[derive(Debug, Clone)]
struct MusicBrainzPayload {
    /// Recording entity resolved from MusicBrainz API.
    recording: Recording,
    /// Optional release entity resolved from MusicBrainz API.
    release: Option<Release>,
}

/// Fetches recording/release payloads through `musicbrainz_rs`.
async fn fetch_musicbrainz_payloads(
    recording_mbid: &str,
    release_mbid: Option<&str>,
) -> anyhow::Result<MusicBrainzPayload> {
    let recording = Recording::fetch()
        .id(recording_mbid)
        .with_artists()
        .with_releases()
        .with_isrcs()
        .with_genres()
        .with_tags()
        .with_annotations()
        .with_work_level_relations()
        .execute()
        .await
        .with_context(|| format!("fetching MusicBrainz recording '{recording_mbid}'"))?;

    let release_id = release_mbid.map(ToOwned::to_owned).or_else(|| {
        recording
            .releases
            .as_ref()
            .and_then(|releases| releases.first())
            .map(|release| release.id.clone())
    });

    let release = if let Some(release_id) = release_id {
        Some(
            Release::fetch()
                .id(&release_id)
                .with_artists()
                .with_recordings()
                .with_release_groups()
                .with_media()
                .with_labels()
                .with_isrcs()
                .with_genres()
                .with_tags()
                .with_annotations()
                .with_recording_level_relations()
                .with_release_group_level_relations()
                .execute()
                .await
                .with_context(|| format!("fetching MusicBrainz release '{release_id}'"))?,
        )
    } else {
        None
    };

    Ok(MusicBrainzPayload { recording, release })
}

/// Converts MusicBrainz payload into FFmetadata key/value map.
fn build_ffmetadata_map(
    payload: &MusicBrainzPayload,
    write_all_tags: bool,
) -> anyhow::Result<BTreeMap<String, String>> {
    let mut tags = BTreeMap::new();

    tags.insert("title".to_string(), payload.recording.title.clone());
    tags.insert("musicbrainz_recordingid".to_string(), payload.recording.id.clone());
    tags.insert("musicbrainz_trackid".to_string(), payload.recording.id.clone());

    if let Some(artist) = artist_credit_text(payload.recording.artist_credit.as_deref()) {
        tags.insert("artist".to_string(), artist);
    }

    if let Some(first_release_date) = payload.recording.first_release_date.as_ref() {
        tags.insert("originaldate".to_string(), first_release_date.0.clone());
    }

    if let Some(isrcs) = payload.recording.isrcs.as_ref()
        && !isrcs.is_empty()
    {
        tags.insert("isrc".to_string(), join_unique(isrcs.iter().map(String::as_str)));
    }

    if let Some(genres) = payload.recording.genres.as_ref() {
        let genre_values = genres.iter().map(|genre| genre.name.as_str()).collect::<Vec<_>>();
        if !genre_values.is_empty() {
            tags.insert("genre".to_string(), join_unique(genre_values));
        }
    }

    if let Some(release) = payload.release.as_ref() {
        tags.insert("album".to_string(), release.title.clone());
        tags.insert("musicbrainz_albumid".to_string(), release.id.clone());

        if let Some(date) = release.date.as_ref() {
            tags.insert("date".to_string(), date.0.clone());
        }
        if let Some(barcode) = release.barcode.as_ref()
            && !barcode.trim().is_empty()
        {
            tags.insert("barcode".to_string(), barcode.clone());
        }
        if let Some(country) = release.country.as_ref()
            && !country.trim().is_empty()
        {
            tags.insert("releasecountry".to_string(), country.clone());
        }
        if let Some(label_info) = release.label_info.as_ref() {
            let labels = label_info
                .iter()
                .filter_map(|info| info.label.as_ref().map(|label| label.name.as_str()))
                .collect::<Vec<_>>();
            if !labels.is_empty() {
                tags.insert("label".to_string(), join_unique(labels));
            }

            let catalog_numbers = label_info
                .iter()
                .filter_map(|info| info.catalog_number.as_deref())
                .collect::<Vec<_>>();
            if !catalog_numbers.is_empty() {
                tags.insert("catalognumber".to_string(), join_unique(catalog_numbers));
            }
        }

        if let Some(release_group) = release.release_group.as_ref() {
            tags.insert("musicbrainz_releasegroupid".to_string(), release_group.id.clone());
            tags.insert("releasegroup".to_string(), release_group.title.clone());
        }

        if let Some(release_artist) = artist_credit_text(release.artist_credit.as_deref()) {
            tags.insert("albumartist".to_string(), release_artist);
        }

        if let Some(track_info) = resolve_track_position(&payload.recording.id, release) {
            tags.insert("tracknumber".to_string(), track_info.track_number);
            tags.insert("discnumber".to_string(), track_info.disc_number.to_string());
            if let Some(total_tracks) = track_info.total_tracks {
                tags.insert("tracktotal".to_string(), total_tracks.to_string());
                tags.insert("totaltracks".to_string(), total_tracks.to_string());
            }
            if let Some(total_discs) = track_info.total_discs {
                tags.insert("disctotal".to_string(), total_discs.to_string());
                tags.insert("totaldiscs".to_string(), total_discs.to_string());
            }
        }
    }

    if write_all_tags {
        let mut recording_flattened = BTreeMap::new();
        flatten_entity_json(
            "musicbrainz_recording",
            &serde_json::to_value(&payload.recording)?,
            &mut recording_flattened,
        );
        let mut release_flattened = BTreeMap::new();
        if let Some(release) = payload.release.as_ref() {
            flatten_entity_json(
                "musicbrainz_release",
                &serde_json::to_value(release)?,
                &mut release_flattened,
            );
        }

        insert_extended_picard_tags(&mut tags, &recording_flattened, &release_flattened);
    }

    Ok(tags)
}

/// Inserts optional Picard-compatible tags from flattened MusicBrainz payloads.
///
/// This helper intentionally emits only known Picard tag keys and rejects the
/// previous broad flatten/alias expansion to avoid non-Picard metadata keys.
fn insert_extended_picard_tags(
    tags: &mut BTreeMap<String, String>,
    recording_flattened: &BTreeMap<String, String>,
    release_flattened: &BTreeMap<String, String>,
) {
    for (alias, source_key) in [
        ("albumartistsort", "musicbrainz_release_artist_credit_0_artist_sort_name"),
        ("artistsort", "musicbrainz_recording_artist_credit_0_artist_sort_name"),
        ("artistcredit", "artist"),
        ("albumartistcredit", "albumartist"),
        ("releasestatus", "musicbrainz_release_status"),
        ("releasetype", "musicbrainz_release_release_group_primary_type"),
        ("secondaryreleasetype", "musicbrainz_release_release_group_secondary_types"),
        ("primaryreleasetype", "musicbrainz_release_release_group_primary_type"),
        ("releasegroup", "musicbrainz_release_release_group_title"),
        ("musicbrainz_releasegroupid", "musicbrainz_release_release_group_id"),
        ("musicbrainz_artistid", "musicbrainz_recording_artist_credit_0_artist_id"),
        ("musicbrainz_albumartistid", "musicbrainz_release_artist_credit_0_artist_id"),
        ("recordingtitle", "musicbrainz_recording_title"),
        ("recordingcomment", "musicbrainz_recording_disambiguation"),
        ("releasecomment", "musicbrainz_release_disambiguation"),
        ("releasegroupcomment", "musicbrainz_release_release_group_disambiguation"),
        ("releaselanguage", "musicbrainz_release_text_representation_language"),
        ("script", "musicbrainz_release_text_representation_script"),
        ("releaseannotation", "musicbrainz_release_annotation"),
        ("recordingannotation", "musicbrainz_recording_annotation"),
        ("releasedate", "date"),
        ("releasecountry", "musicbrainz_release_country"),
        ("media", "musicbrainz_release_media_0_format"),
        ("asin", "musicbrainz_release_asin"),
    ] {
        if let Some(value) = tags.get(source_key).cloned().or_else(|| {
            recording_flattened
                .get(source_key)
                .cloned()
                .or_else(|| release_flattened.get(source_key).cloned())
        }) {
            insert_tag_if_absent(tags, alias, &value);
        }
    }
}

/// Inserts one normalized tag key/value when key is absent and value is non-empty.
fn insert_tag_if_absent(tags: &mut BTreeMap<String, String>, key: &str, value: &str) {
    if value.trim().is_empty() {
        return;
    }
    tags.entry(sanitize_metadata_key(key)).or_insert_with(|| truncate_metadata_value(value));
}

/// One selected cover-art payload retained for metadata and attach stages.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct SelectedCoverArt {
    /// Highest-quality URL selected for this artwork entry.
    url: String,
    /// Primary normalized kind used for compatibility metadata.
    maintype: String,
    /// Ordered normalized kind list for compatibility metadata.
    types: Vec<String>,
    /// Optional human comment associated with this artwork entry.
    comment: String,
}

/// Cover Art Archive response payload.
#[derive(Debug, Deserialize)]
struct CoverArtArchiveResponse {
    /// Artwork entries published for one release/release-group entity.
    #[serde(default)]
    images: Vec<CoverArtArchiveImage>,
}

/// One Cover Art Archive image entry.
#[derive(Debug, Deserialize)]
struct CoverArtArchiveImage {
    /// Canonical original-quality artwork URL.
    #[serde(default)]
    image: Option<String>,
    /// Optional thumbnail URL map keyed by quality labels.
    #[serde(default)]
    thumbnails: BTreeMap<String, String>,
    /// Explicit artwork kind labels.
    #[serde(default)]
    types: Vec<String>,
    /// Optional artwork comment text.
    #[serde(default)]
    comment: Option<String>,
}

/// Cache-expiry policy used by media-tagger HTTP response caches.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum CacheExpiryPolicy {
    /// Cache rows never expire by age.
    Never,
    /// Cache rows expire after this many seconds.
    Seconds(u64),
}

impl CacheExpiryPolicy {
    /// Resolves one cache-expiry policy from runtime option seconds.
    #[must_use]
    fn from_seconds(seconds: i64) -> Self {
        if seconds < 0 { Self::Never } else { Self::Seconds(seconds.unsigned_abs()) }
    }

    /// Returns true when one cached row is still fresh at the current time.
    #[must_use]
    fn is_fresh(self, fetched_unix_seconds: u64, now_unix_seconds: u64) -> bool {
        match self {
            Self::Never => true,
            Self::Seconds(max_age_seconds) => {
                now_unix_seconds.saturating_sub(fetched_unix_seconds) <= max_age_seconds
            }
        }
    }
}

/// One cached row plus freshness metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
struct CachedValue<T> {
    /// Cached payload value.
    payload: T,
    /// Whether this row is currently within configured expiry budget.
    is_fresh: bool,
}

/// JSONC cache index for media-tagger HTTP response rows.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct MediaTaggerCacheIndex {
    /// Envelope version marker.
    version: u32,
    /// Cache metadata rows keyed by logical cache namespace + lookup key.
    #[serde(default)]
    entries: BTreeMap<String, MediaTaggerCacheIndexEntry>,
}

impl Default for MediaTaggerCacheIndex {
    fn default() -> Self {
        Self { version: MEDIA_TAGGER_CACHE_INDEX_VERSION, entries: BTreeMap::new() }
    }
}

/// One media-tagger cache metadata row persisted inside `media-tagger.jsonc`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct MediaTaggerCacheIndexEntry {
    /// CAS hash text pointing at cached payload bytes under `store/`.
    hash: String,
    /// Time when payload was fetched/written (Unix seconds).
    fetched_unix_seconds: u64,
}

/// Persistent on-disk HTTP cache used by media-tagger metadata helpers.
#[derive(Debug, Clone)]
struct MediaTaggerHttpCache {
    /// Optional CAS storage directory under the cache root.
    store_dir: Option<PathBuf>,
    /// Optional JSONC index path under the cache root.
    index_path: Option<PathBuf>,
    /// In-memory cache index rows guarded for concurrent access.
    index: Arc<Mutex<MediaTaggerCacheIndex>>,
    /// Expiry policy applied to cached rows.
    expiry: CacheExpiryPolicy,
}

impl MediaTaggerHttpCache {
    /// Creates one cache policy object from optional directory + expiry config.
    #[must_use]
    fn new(root_dir: Option<PathBuf>, expiry: CacheExpiryPolicy) -> Self {
        let normalized_root =
            root_dir.and_then(|path| if path.as_os_str().is_empty() { None } else { Some(path) });

        let store_dir = normalized_root.as_ref().map(|path| path.join("store"));
        let index_path =
            normalized_root.as_ref().map(|path| path.join(MEDIA_TAGGER_CACHE_INDEX_FILE_NAME));
        let index = index_path.as_deref().map(load_media_tagger_cache_index).unwrap_or_default();

        Self { store_dir, index_path, index: Arc::new(Mutex::new(index)), expiry }
    }

    /// Reads cached cover-art endpoint rows for one CAA endpoint URL.
    #[must_use]
    async fn read_cover_art_entries(
        &self,
        endpoint: &str,
    ) -> Option<CachedValue<Vec<SelectedCoverArt>>> {
        self.read_json_payload("caa-entries", endpoint).await
    }

    /// Persists cached cover-art endpoint rows for one CAA endpoint URL.
    async fn write_cover_art_entries(
        &self,
        endpoint: &str,
        payload: &[SelectedCoverArt],
    ) -> anyhow::Result<()> {
        self.write_json_payload("caa-entries", endpoint, &payload.to_vec()).await
    }

    /// Reads cached cover-art bytes for one artwork URL.
    #[must_use]
    async fn read_cover_art_bytes(&self, url: &str) -> Option<CachedValue<Vec<u8>>> {
        self.read_bytes_payload("caa-images", url).await
    }

    /// Persists cached cover-art bytes for one artwork URL.
    async fn write_cover_art_bytes(&self, url: &str, payload: &[u8]) -> anyhow::Result<()> {
        self.write_bytes_payload("caa-images", url, payload).await
    }

    /// Builds deterministic logical index key for one namespace/key pair.
    #[must_use]
    fn cache_key(namespace: &str, key: &str) -> String {
        format!("{namespace}|{key}")
    }

    /// Reads one JSON payload row from CAS and computes freshness metadata.
    #[must_use]
    async fn read_json_payload<T: DeserializeOwned>(
        &self,
        namespace: &str,
        key: &str,
    ) -> Option<CachedValue<T>> {
        let cache_key = Self::cache_key(namespace, key);
        let entry = {
            let index = self.index.lock().ok()?;
            index.entries.get(&cache_key).cloned()
        }?;

        let hash = entry.hash.parse::<Hash>().ok()?;
        let cas = self.open_cache_cas().await.ok().flatten()?;
        let Ok(bytes) = cas.get(hash).await else {
            self.remove_index_entry(&cache_key);
            return None;
        };

        let Ok(payload) = serde_json::from_slice::<T>(&bytes) else {
            self.remove_index_entry(&cache_key);
            return None;
        };

        let now = now_unix_seconds();
        Some(CachedValue {
            is_fresh: self.expiry.is_fresh(entry.fetched_unix_seconds, now),
            payload,
        })
    }

    /// Reads one raw-bytes payload row from CAS and computes freshness metadata.
    #[must_use]
    async fn read_bytes_payload(&self, namespace: &str, key: &str) -> Option<CachedValue<Vec<u8>>> {
        let cache_key = Self::cache_key(namespace, key);
        let entry = {
            let index = self.index.lock().ok()?;
            index.entries.get(&cache_key).cloned()
        }?;

        let hash = entry.hash.parse::<Hash>().ok()?;
        let cas = self.open_cache_cas().await.ok().flatten()?;
        let Ok(bytes) = cas.get(hash).await else {
            self.remove_index_entry(&cache_key);
            return None;
        };

        let now = now_unix_seconds();
        Some(CachedValue {
            is_fresh: self.expiry.is_fresh(entry.fetched_unix_seconds, now),
            payload: bytes.to_vec(),
        })
    }

    /// Writes one JSON payload row to CAS and updates the JSONC index.
    async fn write_json_payload<T: Serialize>(
        &self,
        namespace: &str,
        key: &str,
        payload: &T,
    ) -> anyhow::Result<()> {
        let Some(cas) = self.open_cache_cas().await? else {
            return Ok(());
        };

        let encoded =
            serde_json::to_vec(payload).context("encoding media-tagger cached payload")?;
        let hash =
            cas.put(encoded).await.context("writing media-tagger cached payload bytes to CAS")?;
        self.upsert_index_entry(Self::cache_key(namespace, key), hash)
    }

    /// Writes one raw-bytes payload row to CAS and updates the JSONC index.
    async fn write_bytes_payload(
        &self,
        namespace: &str,
        key: &str,
        payload: &[u8],
    ) -> anyhow::Result<()> {
        let Some(cas) = self.open_cache_cas().await? else {
            return Ok(());
        };

        let hash = cas
            .put(payload.to_vec())
            .await
            .context("writing media-tagger cached payload bytes to CAS")?;
        self.upsert_index_entry(Self::cache_key(namespace, key), hash)
    }

    /// Opens the media-tagger cache CAS store from `<cache_root>/store`.
    async fn open_cache_cas(&self) -> anyhow::Result<Option<FileSystemCas>> {
        let Some(store_dir) = self.store_dir.as_ref() else {
            return Ok(None);
        };

        let cas = FileSystemCas::open(store_dir).await.with_context(|| {
            format!("opening media-tagger cache CAS store '{}'", store_dir.display())
        })?;

        Ok(Some(cas))
    }

    /// Upserts one cache metadata row and persists updated index JSONC.
    fn upsert_index_entry(&self, cache_key: String, hash: Hash) -> anyhow::Result<()> {
        let mut index = self
            .index
            .lock()
            .map_err(|_| anyhow::anyhow!("locking media-tagger cache index mutex failed"))?;
        index.entries.insert(
            cache_key,
            MediaTaggerCacheIndexEntry {
                hash: hash.to_string(),
                fetched_unix_seconds: now_unix_seconds(),
            },
        );

        self.write_index_file(&index)
    }

    /// Removes one corrupted cache metadata row and persists updated index JSONC.
    fn remove_index_entry(&self, cache_key: &str) {
        let Ok(mut index) = self.index.lock() else {
            return;
        };

        if index.entries.remove(cache_key).is_some() {
            let _ = self.write_index_file(&index);
        }
    }

    /// Persists current media-tagger cache index JSONC with replace-on-rename semantics.
    fn write_index_file(&self, index: &MediaTaggerCacheIndex) -> anyhow::Result<()> {
        let Some(path) = self.index_path.as_ref() else {
            return Ok(());
        };

        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).with_context(|| {
                format!("creating media-tagger cache directory '{}'", parent.display())
            })?;
        }

        let rendered =
            serde_json::to_string_pretty(index).context("encoding media-tagger cache index")?;
        let temp_path = path.with_extension("jsonc.tmp");
        fs::write(&temp_path, format!("{rendered}\n")).with_context(|| {
            format!("writing temporary media-tagger cache index '{}'", temp_path.display())
        })?;

        if path.exists() {
            let _ = fs::remove_file(path);
        }

        fs::rename(&temp_path, path)
            .with_context(|| format!("replacing media-tagger cache index '{}'", path.display()))
    }
}

/// Loads one media-tagger cache index file from disk.
///
/// Missing or malformed index files fall back to an empty index so metadata
/// fetching remains best-effort and non-blocking.
#[must_use]
fn load_media_tagger_cache_index(index_path: &Path) -> MediaTaggerCacheIndex {
    let Ok(raw) = fs::read_to_string(index_path) else {
        return MediaTaggerCacheIndex::default();
    };

    let Ok(index) = serde_json::from_str::<MediaTaggerCacheIndex>(&raw) else {
        return MediaTaggerCacheIndex::default();
    };

    if index.version == MEDIA_TAGGER_CACHE_INDEX_VERSION {
        index
    } else {
        MediaTaggerCacheIndex::default()
    }
}

/// Returns current Unix timestamp in seconds.
#[must_use]
fn now_unix_seconds() -> u64 {
    SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()
}

/// Executes one HTTP GET with retry/backoff for transient failures.
async fn http_get_with_retry(
    http_client: &reqwest::Client,
    url: &str,
) -> Result<reqwest::Response, reqwest::Error> {
    let mut backoff_millis = MEDIA_TAGGER_HTTP_RETRY_BASE_DELAY_MILLIS;

    for attempt in 0..MEDIA_TAGGER_HTTP_RETRY_ATTEMPTS {
        match http_client.get(url).send().await {
            Ok(response)
                if response.status().is_server_error()
                    && attempt + 1 < MEDIA_TAGGER_HTTP_RETRY_ATTEMPTS =>
            {
                sleep(std::time::Duration::from_millis(backoff_millis)).await;
                backoff_millis = backoff_millis.saturating_mul(2);
            }
            Ok(response) => return Ok(response),
            Err(error) if attempt + 1 < MEDIA_TAGGER_HTTP_RETRY_ATTEMPTS => {
                sleep(std::time::Duration::from_millis(backoff_millis)).await;
                backoff_millis = backoff_millis.saturating_mul(2);
                let _ = error;
            }
            Err(error) => return Err(error),
        }
    }

    unreachable!("retry loop always returns on final attempt")
}

/// Fetches all discoverable cover-art entries for release/release-group entities.
async fn collect_musicbrainz_cover_art(
    payload: &MusicBrainzPayload,
    cache: &MediaTaggerHttpCache,
) -> anyhow::Result<Vec<SelectedCoverArt>> {
    let mut unique = BTreeMap::new();

    if let Some(release) = payload.release.as_ref() {
        for path in [
            format!("https://coverartarchive.org/release/{}", release.id),
            release
                .release_group
                .as_ref()
                .map(|group| format!("https://coverartarchive.org/release-group/{}", group.id))
                .unwrap_or_default(),
        ] {
            if path.trim().is_empty() {
                continue;
            }
            for entry in fetch_cover_art_entries(&path, cache).await? {
                unique.entry(entry.url.clone()).or_insert(entry);
            }
        }
    }

    let mut selected = unique.into_values().collect::<Vec<_>>();
    selected.sort_by(|left, right| {
        cover_art_type_priority(&left.maintype)
            .cmp(&cover_art_type_priority(&right.maintype))
            .then_with(|| left.comment.cmp(&right.comment))
            .then_with(|| left.url.cmp(&right.url))
    });

    Ok(selected)
}

/// Queries one Cover Art Archive endpoint and returns one selected URL per entry.
async fn fetch_cover_art_entries(
    endpoint: &str,
    cache: &MediaTaggerHttpCache,
) -> anyhow::Result<Vec<SelectedCoverArt>> {
    let http_client = shared_http_client()
        .map_err(|error| anyhow::anyhow!("initializing shared HTTP client failed: {error}"))?;

    let cached_entries = cache.read_cover_art_entries(endpoint).await;
    if let Some(cached) = cached_entries.as_ref()
        && cached.is_fresh
    {
        return Ok(cached.payload.clone());
    }

    let stale_or_fresh_cached_payload =
        cached_entries.as_ref().map_or_else(Vec::new, |cached| cached.payload.clone());

    let Ok(response) = http_get_with_retry(http_client, endpoint).await else {
        return Ok(stale_or_fresh_cached_payload.clone());
    };

    let status = response.status();
    if status == reqwest::StatusCode::NOT_FOUND {
        let empty = Vec::<SelectedCoverArt>::new();
        let _ = cache.write_cover_art_entries(endpoint, &empty).await;
        return Ok(empty);
    }

    if status.is_server_error() {
        return Ok(stale_or_fresh_cached_payload.clone());
    }

    if !status.is_success() {
        return Ok(stale_or_fresh_cached_payload.clone());
    }

    let body = response.text().await.context("reading cover-art response body")?;
    let payload = serde_json::from_str::<CoverArtArchiveResponse>(&body)
        .context("decoding cover-art JSON")?;

    let mut entries = Vec::new();
    for image in payload.images {
        let Some(url) = select_highest_quality_cover_url(&image) else {
            continue;
        };

        let types = normalized_cover_art_types(&image);
        let maintype = types
            .iter()
            .min_by_key(|value| cover_art_type_priority(value))
            .cloned()
            .unwrap_or_else(|| "other".to_string());

        entries.push(SelectedCoverArt {
            url,
            maintype,
            types,
            comment: normalize_optional_text(image.comment.as_deref()).unwrap_or_default(),
        });
    }

    let _ = cache.write_cover_art_entries(endpoint, &entries).await;
    Ok(entries)
}

/// Returns one normalized highest-quality URL for one CAA image entry.
fn select_highest_quality_cover_url(image: &CoverArtArchiveImage) -> Option<String> {
    let mut candidates = Vec::new();

    if let Some(original) = normalize_optional_text(image.image.as_deref()) {
        candidates.push((i32::MAX, original));
    }

    for (key, value) in &image.thumbnails {
        let Some(normalized_url) = normalize_optional_text(Some(value)) else {
            continue;
        };

        let quality_score = key.trim().parse::<i32>().unwrap_or_else(|_| {
            if key.eq_ignore_ascii_case("large") {
                1_200
            } else if key.eq_ignore_ascii_case("small") {
                250
            } else {
                0
            }
        });

        candidates.push((quality_score, normalized_url));
    }

    candidates
        .into_iter()
        .max_by(|(left_score, left_url), (right_score, right_url)| {
            left_score.cmp(right_score).then_with(|| left_url.cmp(right_url))
        })
        .map(|(_, url)| url)
}

/// Normalizes one CAA image-entry kind list into deterministic lowercase tags.
fn normalized_cover_art_types(image: &CoverArtArchiveImage) -> Vec<String> {
    let mut ordered = Vec::new();
    let mut seen = BTreeSet::new();

    let mut push_type = |candidate: &str| {
        let normalized = candidate.trim().to_ascii_lowercase();
        if normalized.is_empty() {
            return;
        }
        if seen.insert(normalized.clone()) {
            ordered.push(normalized);
        }
    };

    for kind in &image.types {
        push_type(kind);
    }

    if ordered.is_empty() {
        ordered.push("other".to_string());
    }

    ordered.sort_by_key(|kind| cover_art_type_priority(kind));
    ordered
}

/// Returns stable sort priority for normalized cover-art kind tags.
#[must_use]
fn cover_art_type_priority(kind: &str) -> usize {
    match kind {
        "front" => 0,
        "back" => 1,
        "booklet" => 2,
        "medium" => 3,
        "tray" => 4,
        "obi" => 5,
        "spine" => 6,
        "sticker" => 7,
        "poster" => 8,
        "liner" => 9,
        "watermark" => 10,
        _ => 100,
    }
}

/// Emits deterministic image-link metadata tags.
///
/// Keep the emitted `coverart_*` key family synchronized with Picard's
/// cover-art metadata usage in
/// `https://github.com/metabrainz/picard/blob/master/picard/coverart/image.py`.
fn insert_musicbrainz_image_tags(tags: &mut BTreeMap<String, String>, images: &[SelectedCoverArt]) {
    if images.is_empty() {
        return;
    }

    let primary = images.iter().find(|image| image.maintype == "front").unwrap_or(&images[0]);

    tags.insert("coverart_url".to_string(), primary.url.clone());
    for (index, image) in images.iter().enumerate() {
        tags.insert(format!("coverart_url_{index}"), image.url.clone());
    }
    tags.insert("coverart_maintype".to_string(), primary.maintype.clone());

    let all_types =
        join_unique(images.iter().flat_map(|image| image.types.iter().map(String::as_str)));
    if !all_types.trim().is_empty() {
        tags.insert("coverart_types".to_string(), all_types);
    }

    tags.insert("coverart_comment".to_string(), primary.comment.clone());
}

/// Writes deterministic cover-art slot members consumed by apply-stage ffmpeg.
async fn persist_cover_art_slot_artifacts(
    output_path: &Path,
    selected_cover_art: &[SelectedCoverArt],
    slot_count: usize,
    cache: &MediaTaggerHttpCache,
) -> anyhow::Result<()> {
    let artifact_directory = resolve_cover_art_artifact_directory(output_path);
    fs::create_dir_all(&artifact_directory).with_context(|| {
        format!(
            "creating media-tagger cover-art artifact directory '{}'",
            artifact_directory.display()
        )
    })?;

    if selected_cover_art.len() > slot_count {
        bail!(
            "media-tagger resolved {} cover-art entries but only {slot_count} slot(s) are available; increase tools.ffmpeg.max_input_slots to at least {}",
            selected_cover_art.len(),
            selected_cover_art.len() + 1,
        );
    }

    let http_client = shared_http_client()
        .map_err(|error| anyhow::anyhow!("initializing shared HTTP client failed: {error}"))?;

    let mut downloaded = Vec::new();
    for image in selected_cover_art {
        let Some(bytes) = download_cover_art_bytes(http_client, &image.url, cache)
            .await
            .with_context(|| format!("downloading cover-art payload '{}'", image.url))?
        else {
            continue;
        };

        downloaded.push(bytes);
    }

    if downloaded.len() > slot_count {
        bail!(
            "downloaded {} cover-art entries but only {slot_count} slot(s) are available",
            downloaded.len()
        );
    }

    for slot_index in 1..=slot_count {
        let image_member = cover_art_slot_image_member_name(slot_index);
        let flag_member = cover_art_slot_flag_member_name(slot_index);
        let image_path = artifact_directory.join(&image_member);
        let flag_path = artifact_directory.join(&flag_member);

        if let Some(bytes) = downloaded.get(slot_index - 1) {
            fs::write(&image_path, bytes).with_context(|| {
                format!("writing cover-art slot payload '{}'", image_path.display())
            })?;
            fs::write(&flag_path, b"true").with_context(|| {
                format!("writing cover-art slot flag '{}'", flag_path.display())
            })?;
        } else {
            fs::write(&image_path, &[] as &[u8]).with_context(|| {
                format!("writing empty cover-art slot payload '{}'", image_path.display())
            })?;
            fs::write(&flag_path, &[] as &[u8]).with_context(|| {
                format!("writing empty cover-art slot flag '{}'", flag_path.display())
            })?;
        }
    }

    Ok(())
}

/// Resolves sandbox folder where managed runs expose materialized input files.
fn resolve_cover_art_artifact_directory(output_path: &Path) -> PathBuf {
    let metadata_dir = output_path.parent().unwrap_or_else(|| Path::new("."));
    // Cover art files are placed under a dedicated `coverart/` directory in the
    // sandbox root rather than alongside the input media in `inputs/`. This keeps
    // cover art separated from the large input media file and ensures the
    // `sandbox_artifacts` capture for media-tagger can target `coverart/` only,
    // avoiding redundant capture of `inputs/input.media`.
    metadata_dir
        .parent()
        .map_or_else(|| metadata_dir.join("coverart"), |sandbox_root| sandbox_root.join("coverart"))
}

/// Downloads one cover-art payload, returning `None` when URL is unreachable.
async fn download_cover_art_bytes(
    http_client: &reqwest::Client,
    url: &str,
    cache: &MediaTaggerHttpCache,
) -> anyhow::Result<Option<Vec<u8>>> {
    let cached_bytes = cache.read_cover_art_bytes(url).await;
    if let Some(cached) = cached_bytes.as_ref()
        && cached.is_fresh
    {
        return Ok((!cached.payload.is_empty()).then(|| cached.payload.clone()));
    }

    let stale_cached_payload = cached_bytes
        .as_ref()
        .and_then(|cached| (!cached.payload.is_empty()).then(|| cached.payload.clone()));

    let Ok(response) = http_get_with_retry(http_client, url).await else {
        return Ok(stale_cached_payload);
    };

    let status = response.status();
    if status == reqwest::StatusCode::NOT_FOUND {
        return Ok(None);
    }

    if status.is_server_error() {
        return Ok(stale_cached_payload);
    }

    if !status.is_success() {
        return Ok(stale_cached_payload);
    }

    let bytes = response
        .bytes()
        .await
        .with_context(|| format!("reading cover-art payload bytes from '{url}'"))?;

    if bytes.is_empty() {
        return Ok(stale_cached_payload);
    }

    let payload = bytes.to_vec();
    let _ = cache.write_cover_art_bytes(url, &payload).await;
    Ok(Some(payload))
}

/// Track-position metadata resolved from release media structure.
#[derive(Debug, Clone, PartialEq, Eq)]
struct TrackPosition {
    /// Human-facing track number from the release tracklist.
    track_number: String,
    /// One-based disc index in release media ordering.
    disc_number: u32,
    /// Optional total track count for the current disc.
    total_tracks: Option<u32>,
    /// Optional total disc count for the release.
    total_discs: Option<u32>,
}

/// Resolves track/disc position metadata by matching recording MBID.
fn resolve_track_position(recording_mbid: &str, release: &Release) -> Option<TrackPosition> {
    let medias = release.media.as_ref()?;

    for media in medias {
        let tracks = media.tracks.as_ref()?;
        for track in tracks {
            let Some(recording) = track.recording.as_ref() else {
                continue;
            };
            if recording.id != recording_mbid {
                continue;
            }

            return Some(TrackPosition {
                track_number: track.number.clone(),
                disc_number: media.position.unwrap_or(1),
                total_tracks: Some(media.track_count),
                total_discs: media.disc_count,
            });
        }
    }

    None
}

/// Converts artist-credit list into stable display string.
fn artist_credit_text(
    artist_credit: Option<&[musicbrainz_rs::entity::artist_credit::ArtistCredit]>,
) -> Option<String> {
    let artist_credit = artist_credit?;
    if artist_credit.is_empty() {
        return None;
    }

    let mut combined = String::new();
    for credit in artist_credit {
        combined.push_str(&credit.name);
        if let Some(join_phrase) = credit.joinphrase.as_deref() {
            combined.push_str(join_phrase);
        }
    }

    if combined.trim().is_empty() { None } else { Some(combined) }
}

/// Joins string values while preserving first-seen order and uniqueness.
fn join_unique<'a>(values: impl IntoIterator<Item = &'a str>) -> String {
    let mut seen = BTreeSet::new();
    let mut ordered = Vec::new();

    for value in values {
        let trimmed = value.trim();
        if trimmed.is_empty() {
            continue;
        }
        if seen.insert(trimmed.to_string()) {
            ordered.push(trimmed.to_string());
        }
    }

    ordered.join("; ")
}

/// Flattens one arbitrary JSON tree into FFmetadata-safe key/value pairs.
fn flatten_entity_json(prefix: &str, value: &Value, out: &mut BTreeMap<String, String>) {
    fn walk(prefix: &str, value: &Value, out: &mut BTreeMap<String, String>) {
        if out.len() >= MAX_FLATTENED_METADATA_ENTRIES {
            return;
        }

        match value {
            Value::Object(map) => {
                let mut entries = map.iter().collect::<Vec<_>>();
                entries.sort_by(|(left, _), (right, _)| left.cmp(right));
                for (key, nested) in entries {
                    let nested_prefix = format!("{prefix}_{key}");
                    walk(&nested_prefix, nested, out);
                }
            }
            Value::Array(items) => {
                if items.iter().all(is_scalar_json_value) {
                    let joined = items
                        .iter()
                        .filter_map(json_scalar_to_string)
                        .collect::<Vec<_>>()
                        .join("; ");
                    let key = sanitize_metadata_key(prefix);
                    if !joined.is_empty() {
                        out.insert(key, truncate_metadata_value(&joined));
                    }
                } else {
                    for (index, nested) in items.iter().enumerate() {
                        walk(&format!("{prefix}_{index}"), nested, out);
                    }
                }
            }
            _ => {
                if let Some(rendered) = json_scalar_to_string(value)
                    && !rendered.is_empty()
                {
                    out.insert(sanitize_metadata_key(prefix), truncate_metadata_value(&rendered));
                }
            }
        }
    }

    walk(prefix, value, out);
}

/// Returns true when one JSON value can be represented as scalar metadata text.
fn is_scalar_json_value(value: &Value) -> bool {
    matches!(value, Value::Null | Value::Bool(_) | Value::Number(_) | Value::String(_))
}

/// Converts one scalar JSON value into metadata text.
fn json_scalar_to_string(value: &Value) -> Option<String> {
    match value {
        Value::Bool(flag) => Some(flag.to_string()),
        Value::Number(number) => Some(number.to_string()),
        Value::String(text) => normalize_optional_text(Some(text)),
        _ => None,
    }
}

/// Sanitizes one metadata key for broad ffmpeg tag compatibility.
fn sanitize_metadata_key(input: &str) -> String {
    let mut key =
        input
            .chars()
            .map(|character| {
                if character.is_ascii_alphanumeric() { character.to_ascii_lowercase() } else { '_' }
            })
            .collect::<String>();

    while key.contains("__") {
        key = key.replace("__", "_");
    }
    key = key.trim_matches('_').to_string();

    if key.is_empty() {
        return "metadata".to_string();
    }
    if key.starts_with(|character: char| character.is_ascii_digit()) {
        return format!("meta_{key}");
    }

    key
}

/// Truncates one metadata value to bounded maximum length.
fn truncate_metadata_value(value: &str) -> String {
    if value.len() <= MAX_FLATTENED_VALUE_LEN {
        value.to_string()
    } else {
        value.chars().take(MAX_FLATTENED_VALUE_LEN).collect::<String>()
    }
}

/// Persists one FFmetadata document to requested output path.
fn write_ffmetadata_document(
    output_path: &Path,
    metadata_map: &BTreeMap<String, String>,
) -> anyhow::Result<()> {
    let document = FFMetadata {
        global: metadata_map
            .iter()
            .map(|(key, value)| (key.clone(), value.clone()))
            .collect::<Vec<_>>(),
        ..FFMetadata::default()
    };

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!("creating ffmetadata output directory '{}'", parent.display())
        })?;
    }

    fs::write(output_path, document.to_string())
        .with_context(|| format!("writing ffmetadata file '{}'", output_path.display()))?;

    Ok(())
}

/// Returns normalized, non-empty optional string value.
fn normalize_optional_text(value: Option<&str>) -> Option<String> {
    value.map(str::trim).filter(|value| !value.is_empty()).map(ToString::to_string)
}

/// Resolves ffmpeg executable path for internal tagger operations.
///
/// Managed sync injects a host-specific relative executable path through
/// `MEDIA_TAGGER_FFMPEG_BIN_ENV` so internal launchers can run without relying
/// on ambient PATH state.
fn resolve_ffmpeg_executable() -> String {
    normalize_optional_text(std::env::var(MEDIA_TAGGER_FFMPEG_BIN_ENV).ok().as_deref())
        .unwrap_or_else(|| FFMPEG_EXECUTABLE.to_string())
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use tempfile::tempdir;

    use super::{
        CacheExpiryPolicy, CoverArtArchiveImage, DEFAULT_ACOUSTID_ENDPOINT,
        DEFAULT_CACHE_EXPIRY_SECONDS, DEFAULT_MUSICBRAINZ_ENDPOINT, InternalMediaTaggerOptions,
        MediaTaggerHttpCache, SelectedCoverArt, cover_art_slot_flag_member_name,
        cover_art_slot_image_member_name, insert_extended_picard_tags,
        insert_musicbrainz_image_tags, normalized_cover_art_types, parse_ffmetadata_global_map,
        persist_cover_art_slot_artifacts, require_acoustid_api_key_for_lookup,
        run_internal_media_tagger, select_highest_quality_cover_url,
    };

    /// Protects strict autodetection policy: when `recording_mbid` is absent,
    /// missing/blank `AcoustID` credentials must fail immediately.
    #[tokio::test]
    async fn run_internal_media_tagger_fails_when_acoustid_key_is_missing_for_autodetect() {
        let workspace = tempdir().expect("tempdir");
        let input_path = workspace.path().join("input.mp3");
        let output_path = workspace.path().join("output.ffmetadata");
        std::fs::write(&input_path, b"dummy-bytes").expect("write input media stub");

        let result = run_internal_media_tagger(InternalMediaTaggerOptions {
            input_path: Some(input_path),
            output_path: output_path.clone(),
            acoustid_api_key: Some("   ".to_string()),
            acoustid_endpoint: DEFAULT_ACOUSTID_ENDPOINT.to_string(),
            musicbrainz_endpoint: DEFAULT_MUSICBRAINZ_ENDPOINT.to_string(),
            cache_dir: None,
            cache_expiry_seconds: DEFAULT_CACHE_EXPIRY_SECONDS,
            strict_identification: false,
            write_all_tags: true,
            write_all_images: true,
            cover_art_slot_count: 8,
            recording_mbid: None,
            release_mbid: None,
        })
        .await;

        let error = result.expect_err("missing key on autodetect path must fail");
        assert!(
            error.to_string().contains("AcoustID lookup requires a non-empty API key"),
            "expected strict missing-key failure but got: {error:#}"
        );
        assert!(
            !error.to_string().contains("decoding media for fingerprinting"),
            "missing-key validation should fail before decode path"
        );

        assert!(
            output_path.exists(),
            "wrapper should still write fallback ffmetadata output after error"
        );
    }

    /// Protects helper behavior that enforces explicit key presence for
    /// autodetection lookups.
    #[test]
    fn require_acoustid_api_key_for_lookup_enforces_non_empty_key() {
        let missing = require_acoustid_api_key_for_lookup(None).expect_err("missing key must fail");
        assert!(
            missing.to_string().contains("AcoustID lookup requires a non-empty API key"),
            "expected missing-key diagnostic"
        );

        let provided = require_acoustid_api_key_for_lookup(Some("demo-key".to_string()))
            .expect("non-empty key should pass");
        assert_eq!(provided, "demo-key");
    }

    /// Protects phase-3 behavior that when credentials are supplied, the
    /// `AcoustID` lookup path is attempted and failures are surfaced.
    #[tokio::test]
    async fn run_internal_media_tagger_with_key_attempts_lookup_path() {
        let workspace = tempdir().expect("tempdir");
        let input_path = workspace.path().join("input.mp3");
        let output_path = workspace.path().join("output.ffmetadata");
        std::fs::write(&input_path, b"dummy-bytes").expect("write input media stub");

        let result = run_internal_media_tagger(InternalMediaTaggerOptions {
            input_path: Some(input_path),
            output_path: output_path.clone(),
            acoustid_api_key: Some("demo-key".to_string()),
            acoustid_endpoint: DEFAULT_ACOUSTID_ENDPOINT.to_string(),
            musicbrainz_endpoint: DEFAULT_MUSICBRAINZ_ENDPOINT.to_string(),
            cache_dir: None,
            cache_expiry_seconds: DEFAULT_CACHE_EXPIRY_SECONDS,
            strict_identification: false,
            write_all_tags: true,
            write_all_images: true,
            cover_art_slot_count: 8,
            recording_mbid: None,
            release_mbid: None,
        })
        .await;

        let error = result.expect_err("provided key should execute lookup path");
        assert!(
            error.to_string().contains("decoding media for fingerprinting"),
            "expected decode path failure when lookup path is active"
        );
        assert!(
            output_path.exists(),
            "ffmetadata output should still exist for workflow output-capture consistency"
        );
    }

    /// Protects ffmetadata parsing for metadata-preserving merge behavior.
    #[test]
    fn parse_ffmetadata_global_map_decodes_escaped_pairs() {
        let parsed = parse_ffmetadata_global_map(
            ";FFMETADATA1\nartist=Example Artist\ncomment=hello\\=world\n[CHAPTER]\nstart=0\n",
        );

        assert_eq!(parsed.get("artist"), Some(&"Example Artist".to_string()));
        assert_eq!(parsed.get("comment"), Some(&"hello=world".to_string()));
        assert!(!parsed.contains_key("start"));
    }

    /// Protects Picard-compatible cover-art tag projection from discovered URLs.
    #[test]
    fn insert_musicbrainz_image_tags_emits_picard_coverart_aliases() {
        let mut tags = BTreeMap::new();
        insert_musicbrainz_image_tags(
            &mut tags,
            &[SelectedCoverArt {
                url: "https://example.test/front.jpg".to_string(),
                maintype: "front".to_string(),
                types: vec!["front".to_string(), "booklet".to_string()],
                comment: "Scanned sleeve".to_string(),
            }],
        );

        assert_eq!(tags.get("coverart_url"), Some(&"https://example.test/front.jpg".to_string()));
        assert_eq!(tags.get("coverart_url_0"), Some(&"https://example.test/front.jpg".to_string()));
        assert_eq!(tags.get("coverart_maintype"), Some(&"front".to_string()));
        assert_eq!(tags.get("coverart_types"), Some(&"front; booklet".to_string()));
        assert_eq!(tags.get("coverart_comment"), Some(&"Scanned sleeve".to_string()));
    }

    /// Protects cover-art quality selection so each artwork entry prefers the
    /// highest available source image over thumbnail fallbacks.
    #[test]
    fn select_highest_quality_cover_url_prefers_original_image() {
        let image = CoverArtArchiveImage {
            image: Some("https://example.test/original.jpg".to_string()),
            thumbnails: BTreeMap::from([
                ("250".to_string(), "https://example.test/250.jpg".to_string()),
                ("1200".to_string(), "https://example.test/1200.jpg".to_string()),
            ]),
            types: vec!["Front".to_string()],
            comment: None,
        };

        assert_eq!(
            select_highest_quality_cover_url(&image),
            Some("https://example.test/original.jpg".to_string())
        );
    }

    /// Protects no-backcompat behavior by ignoring legacy `front`/`back` bools.
    #[test]
    fn normalized_cover_art_types_ignores_legacy_bool_aliases() {
        let image: CoverArtArchiveImage = serde_json::from_value(serde_json::json!({
            "image": "https://example.test/original.jpg",
            "thumbnails": {},
            "types": [],
            "front": true,
            "back": true
        }))
        .expect("legacy bool payload should deserialize with unknown fields ignored");

        assert_eq!(normalized_cover_art_types(&image), vec!["other".to_string()]);
    }

    /// Protects deterministic cover-art slot fanout by requiring empty
    /// placeholder members for unused slots.
    #[tokio::test]
    async fn persist_cover_art_slot_artifacts_writes_empty_members_for_unused_slots() {
        let root = tempdir().expect("tempdir");
        let output_path = root.path().join("metadata").join("output.ffmeta");
        let cache = MediaTaggerHttpCache::new(None, CacheExpiryPolicy::from_seconds(0));

        persist_cover_art_slot_artifacts(&output_path, &[], 3, &cache)
            .await
            .expect("empty slot artifact write should succeed");

        let artifact_dir = root.path().join("coverart");
        for slot_index in 1..=3 {
            let image_path = artifact_dir.join(cover_art_slot_image_member_name(slot_index));
            let flag_path = artifact_dir.join(cover_art_slot_flag_member_name(slot_index));

            let image_bytes = std::fs::read(&image_path).expect("read image slot");
            let flag_bytes = std::fs::read(&flag_path).expect("read flag slot");
            assert!(image_bytes.is_empty(), "unused image slot should be empty bytes");
            assert!(flag_bytes.is_empty(), "unused flag slot should be empty bytes");
        }
    }

    /// Protects strict Picard mapping by preventing flattened source keys from
    /// leaking into generated ffmetadata output.
    #[test]
    fn insert_extended_picard_tags_does_not_emit_flattened_source_keys() {
        let mut tags = BTreeMap::new();
        let recording_flattened = BTreeMap::from([(
            "musicbrainz_recording_artist_credit_0_artist_sort_name".to_string(),
            "Recording Artist Sort".to_string(),
        )]);
        let release_flattened = BTreeMap::from([(
            "musicbrainz_release_artist_credit_0_artist_sort_name".to_string(),
            "Album Artist Sort".to_string(),
        )]);

        insert_extended_picard_tags(&mut tags, &recording_flattened, &release_flattened);

        assert_eq!(tags.get("artistsort"), Some(&"Recording Artist Sort".to_string()));
        assert_eq!(tags.get("albumartistsort"), Some(&"Album Artist Sort".to_string()));
        assert!(!tags.contains_key("musicbrainz_recording_artist_credit_0_artist_sort_name"));
        assert!(!tags.contains_key("musicbrainz_release_artist_credit_0_artist_sort_name"));
    }

    /// Protects cache policy semantics where negative expiry means
    /// "never expire" and non-negative values enforce age checks.
    #[test]
    fn cache_expiry_policy_handles_negative_never_expire() {
        let never_expire = CacheExpiryPolicy::from_seconds(-1);
        assert!(never_expire.is_fresh(1, 10_000_000));

        let one_second = CacheExpiryPolicy::from_seconds(1);
        assert!(one_second.is_fresh(99, 100));
        assert!(!one_second.is_fresh(98, 100));
    }

    /// Protects media-tagger JSONC cache persistence so cached cover-art rows
    /// can be reused after transient upstream failures.
    #[tokio::test]
    async fn media_tagger_http_cache_round_trips_cover_entries() {
        let root = tempdir().expect("tempdir");
        let cache = MediaTaggerHttpCache::new(
            Some(root.path().join("cache-store")),
            CacheExpiryPolicy::from_seconds(60),
        );

        let entries = vec![SelectedCoverArt {
            url: "https://example.test/front.jpg".to_string(),
            maintype: "front".to_string(),
            types: vec!["front".to_string()],
            comment: "cover".to_string(),
        }];
        cache
            .write_cover_art_entries("https://coverartarchive.org/release/demo", &entries)
            .await
            .expect("write cached entries");

        let loaded = cache
            .read_cover_art_entries("https://coverartarchive.org/release/demo")
            .await
            .expect("read cached entries");
        assert!(loaded.is_fresh);
        assert_eq!(loaded.payload, entries);

        assert!(root.path().join("cache-store").join("store").exists());
        assert!(root.path().join("cache-store").join("media-tagger.jsonc").exists());
        assert!(!root.path().join("cache-store").join("store").join("media-tagger").exists());
    }
}
