//! Native Phase-3 metadata tagging pipeline.
//!
//! This module replaces the legacy external Picard step with an internal
//! `mediapm` flow:
//! 1. decode input audio and compute Chromaprint fingerprint,
//! 2. resolve MBIDs through AcoustID,
//! 3. fetch rich recording/release payloads through `musicbrainz_rs`,
//! 4. map metadata into FFmetadata key/value pairs,
//! 5. persist one FFmetadata document for downstream apply stages.
//!
//! Failure policy is controlled by `strict_identification`: when enabled,
//! unresolved identity or metadata-fetch failures abort the step; when disabled,
//! an empty FFmetadata document is written so downstream apply stages may
//! continue deterministically.
//! AcoustID lookup itself is only attempted when no recording MBID override is
//! supplied. Missing/empty lookup credentials are a hard error on that
//! autodetection path; when credentials are provided, lookup/authentication
//! failures are surfaced as hard errors.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, bail};
use chromaprint::{Algorithm, fingerprint_audio};
use ffmetadata::FFMetadata;
use musicbrainz_rs::entity::recording::Recording;
use musicbrainz_rs::entity::release::Release;
use musicbrainz_rs::prelude::*;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use tokio::process::Command;

use crate::http_client::shared_http_client;

/// Default AcoustID lookup endpoint used by the internal tagger.
pub const DEFAULT_ACOUSTID_ENDPOINT: &str = "https://api.acoustid.org/v2/lookup";
/// Default MusicBrainz API endpoint label used for diagnostics.
pub const DEFAULT_MUSICBRAINZ_ENDPOINT: &str = "https://musicbrainz.org/ws/2";

/// Target sample rate used for deterministic fingerprint extraction.
const FINGERPRINT_SAMPLE_RATE: u32 = 44_100;
/// Target channel count used for deterministic fingerprint extraction.
const FINGERPRINT_CHANNELS: u16 = 2;
/// Environment variable fallback for AcoustID API credentials.
const ACOUSTID_API_KEY_ENV: &str = "ACOUSTID_API_KEY";
/// Maximum metadata entries emitted to FFmetadata output.
const MAX_FLATTENED_METADATA_ENTRIES: usize = 1_024;
/// Maximum flattened metadata value length to avoid runaway tags.
const MAX_FLATTENED_VALUE_LEN: usize = 4_096;

/// Runtime options for one internal media-tagger invocation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InternalMediaTaggerOptions {
    /// Input media path to inspect and tag.
    pub input_path: PathBuf,
    /// Output FFmetadata path generated by this metadata-fetch stage.
    pub output_path: PathBuf,
    /// Optional AcoustID API key override.
    pub acoustid_api_key: Option<String>,
    /// AcoustID lookup endpoint.
    pub acoustid_endpoint: String,
    /// MusicBrainz API endpoint used in diagnostics.
    pub musicbrainz_endpoint: String,
    /// Whether unresolved identity should fail the invocation.
    pub strict_identification: bool,
    /// Optional direct recording MBID override.
    pub recording_mbid: Option<String>,
    /// Optional direct release MBID override.
    pub release_mbid: Option<String>,
    /// `ffmpeg` executable used for decode + metadata write stages.
    pub ffmpeg_bin: String,
}

/// Executes one full internal tagging pipeline.
pub async fn run_internal_media_tagger(options: InternalMediaTaggerOptions) -> anyhow::Result<()> {
    if !options.input_path.exists() {
        bail!("input media path '{}' does not exist", options.input_path.display());
    }

    let output_path = options.output_path.clone();
    match run_internal_media_tagger_impl(options).await {
        Ok(()) => Ok(()),
        Err(error) => {
            if let Err(write_error) = write_ffmetadata_document(&output_path, &BTreeMap::new()) {
                return Err(error.context(format!(
                    "failed to persist fallback ffmetadata output '{}' after tagging error: {write_error}",
                    output_path.display()
                )));
            }

            Err(error)
        }
    }
}

/// Executes one full internal tagging pipeline without fallback-output handling.
async fn run_internal_media_tagger_impl(options: InternalMediaTaggerOptions) -> anyhow::Result<()> {
    let resolved_input =
        options.input_path.canonicalize().unwrap_or_else(|_| options.input_path.clone());
    let mut detected_recording_mbid = normalize_optional_text(options.recording_mbid.as_deref());
    let mut detected_release_mbid = normalize_optional_text(options.release_mbid.as_deref());

    if detected_recording_mbid.is_none() {
        let acoustid_api_key = require_acoustid_api_key_for_lookup(resolve_acoustid_api_key(
            options.acoustid_api_key.as_deref(),
        )?)?;
        let fingerprint_payload =
            decode_and_fingerprint_audio(&options.ffmpeg_bin, &resolved_input)
                .await
                .context("decoding media for fingerprinting")?;
        let match_result = lookup_acoustid_match(
            &options.acoustid_endpoint,
            &acoustid_api_key,
            &fingerprint_payload.fingerprint,
            fingerprint_payload.duration_seconds,
        )
        .await
        .with_context(|| {
            format!(
                "resolving recording identity through AcoustID endpoint '{}'",
                options.acoustid_endpoint
            )
        })?;

        detected_recording_mbid = detected_recording_mbid.or(match_result.recording_mbid);
        detected_release_mbid = detected_release_mbid.or(match_result.release_mbid);
    }

    let Some(recording_mbid) = detected_recording_mbid else {
        if options.strict_identification {
            bail!(
                "could not resolve recording MBID (set --recording-mbid or provide AcoustID API key via --acoustid-api-key/{ACOUSTID_API_KEY_ENV})"
            );
        }

        write_ffmetadata_document(&options.output_path, &BTreeMap::new())?;
        return Ok(());
    };

    let metadata_payload =
        fetch_musicbrainz_payloads(&recording_mbid, detected_release_mbid.as_deref())
            .await
            .with_context(|| {
                format!(
                    "fetching MusicBrainz entities from '{}' for recording '{}'",
                    options.musicbrainz_endpoint, recording_mbid
                )
            });

    let metadata_payload = match metadata_payload {
        Ok(payload) => payload,
        Err(error) => {
            if options.strict_identification {
                return Err(error);
            }
            write_ffmetadata_document(&options.output_path, &BTreeMap::new())?;
            return Ok(());
        }
    };

    let ffmetadata_map = build_ffmetadata_map(&metadata_payload)
        .context("building FFmetadata mapping from MusicBrainz payload")?;

    if ffmetadata_map.is_empty() {
        if options.strict_identification {
            bail!("resolved metadata payload did not produce any FFmetadata entries");
        }
        write_ffmetadata_document(&options.output_path, &BTreeMap::new())?;
        return Ok(());
    }

    write_ffmetadata_document(&options.output_path, &ffmetadata_map)
}

/// Decoded fingerprint payload plus AcoustID request duration hint.
#[derive(Debug, Clone, PartialEq, Eq)]
struct FingerprintPayload {
    /// Encoded Chromaprint fingerprint string used by AcoustID lookup.
    fingerprint: String,
    /// Rounded audio duration in whole seconds.
    duration_seconds: u32,
}

/// Resolves AcoustID API key from CLI override or environment.
fn resolve_acoustid_api_key(override_value: Option<&str>) -> anyhow::Result<Option<String>> {
    if let Some(override_value) = override_value {
        if let Some(value) = normalize_optional_text(Some(override_value)) {
            return Ok(Some(value));
        }

        // An explicit blank override intentionally disables environment
        // fallback so callers can force the "missing-key" flow.
        return Ok(None);
    }

    if let Some(value) = std::env::var_os(ACOUSTID_API_KEY_ENV)
        .and_then(|value| value.into_string().ok())
        .and_then(|value| normalize_optional_text(Some(&value)))
    {
        return Ok(Some(value));
    }

    Ok(None)
}

/// Enforces that AcoustID autodetection has a non-empty API key.
///
/// The lookup path is entered only when callers omit `recording_mbid`.
/// At that point, missing credentials represent a configuration error:
/// runtime would otherwise silently disable autodetection and surprise users.
///
/// In `mediapm sync` executions, the internal media-tagger runs as a managed
/// executable tool under conductor. In that mode, operators typically need to
/// include `ACOUSTID_API_KEY` in `runtime.inherited_env_vars` so the tool
/// subprocess can read it from environment.
fn require_acoustid_api_key_for_lookup(resolved_key: Option<String>) -> anyhow::Result<String> {
    let Some(api_key) = resolved_key else {
        bail!(
            "AcoustID lookup requires a non-empty API key; set --acoustid-api-key or {ACOUSTID_API_KEY_ENV} (for mediapm sync workflows, ensure runtime.inherited_env_vars includes {ACOUSTID_API_KEY_ENV})"
        );
    };

    Ok(api_key)
}

/// Runs `ffmpeg` decode + Chromaprint fingerprint generation for one media file.
async fn decode_and_fingerprint_audio(
    ffmpeg_bin: &str,
    input_path: &Path,
) -> anyhow::Result<FingerprintPayload> {
    let output = Command::new(ffmpeg_bin)
        .arg("-v")
        .arg("error")
        .arg("-i")
        .arg(input_path)
        .arg("-vn")
        .arg("-f")
        .arg("s16le")
        .arg("-ac")
        .arg(FINGERPRINT_CHANNELS.to_string())
        .arg("-ar")
        .arg(FINGERPRINT_SAMPLE_RATE.to_string())
        .arg("-")
        .output()
        .await
        .with_context(|| format!("running '{ffmpeg_bin}' to decode '{}'", input_path.display()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!(
            "ffmpeg decode failed for '{}' with status {}: {stderr}",
            input_path.display(),
            output.status
        );
    }

    if output.stdout.is_empty() {
        bail!("ffmpeg decode for '{}' produced no PCM bytes", input_path.display());
    }

    let samples = output
        .stdout
        .chunks_exact(2)
        .map(|chunk| i16::from_le_bytes([chunk[0], chunk[1]]))
        .collect::<Vec<_>>();

    if samples.is_empty() {
        bail!("decoded PCM sample stream is empty");
    }

    let fingerprint = fingerprint_audio(
        &samples,
        FINGERPRINT_SAMPLE_RATE,
        FINGERPRINT_CHANNELS,
        Algorithm::default(),
    )
    .context("computing chromaprint fingerprint")?;

    let encoded_fingerprint = fingerprint.encoded().to_string();
    let duration_seconds = (((samples.len() as f64)
        / (f64::from(FINGERPRINT_SAMPLE_RATE) * f64::from(FINGERPRINT_CHANNELS)))
    .round()
    .max(1.0)) as u32;

    Ok(FingerprintPayload { fingerprint: encoded_fingerprint, duration_seconds })
}

/// AcoustID API response payload.
#[derive(Debug, Deserialize)]
struct AcoustIdLookupResponse {
    /// API status string (`ok` on success).
    status: String,
    /// Candidate matches returned by AcoustID.
    #[serde(default)]
    results: Vec<AcoustIdResult>,
}

/// Wire-format query parameters for AcoustID lookup.
#[derive(Debug, Serialize)]
struct AcoustIdLookupQuery<'a> {
    /// API key issued by AcoustID.
    client: &'a str,
    /// Requested lookup metadata projections.
    meta: &'a str,
    /// Rounded clip duration in seconds.
    duration: u32,
    /// Encoded Chromaprint fingerprint text.
    fingerprint: &'a str,
    /// Output response format.
    format: &'a str,
}

/// One AcoustID candidate match.
#[derive(Debug, Deserialize)]
struct AcoustIdResult {
    /// Match confidence score in `[0, 1]`.
    score: Option<f64>,
    /// Candidate recordings for this fingerprint match.
    #[serde(default)]
    recordings: Vec<AcoustIdRecording>,
}

/// Recording payload returned in AcoustID lookup metadata.
#[derive(Debug, Deserialize)]
struct AcoustIdRecording {
    /// MusicBrainz recording identifier.
    id: String,
    /// Optional release candidates linked to this recording.
    #[serde(default)]
    releases: Vec<AcoustIdRelease>,
}

/// Release payload returned in AcoustID lookup metadata.
#[derive(Debug, Deserialize)]
struct AcoustIdRelease {
    /// MusicBrainz release identifier.
    id: String,
}

/// Selected AcoustID match values used for downstream fetches.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
struct AcoustIdMatch {
    /// Selected recording MBID, when available.
    recording_mbid: Option<String>,
    /// Selected release MBID, when available.
    release_mbid: Option<String>,
}

/// Calls AcoustID lookup API and returns highest-scoring MBID pair.
async fn lookup_acoustid_match(
    endpoint: &str,
    api_key: &str,
    fingerprint: &str,
    duration_seconds: u32,
) -> anyhow::Result<AcoustIdMatch> {
    let http_client = shared_http_client()
        .map_err(|error| anyhow::anyhow!("initializing shared HTTP client failed: {error}"))?;

    let payload = http_client
        .get(endpoint)
        .query(&AcoustIdLookupQuery {
            client: api_key,
            meta: "recordings releases releasegroups tracks compress usermeta sources",
            duration: duration_seconds,
            fingerprint,
            format: "json",
        })
        .send()
        .await
        .context("sending AcoustID lookup request")?
        .error_for_status()
        .context("AcoustID lookup returned non-success status")?
        .text()
        .await
        .context("reading AcoustID lookup response body")?;

    let response = serde_json::from_str::<AcoustIdLookupResponse>(&payload)
        .context("decoding AcoustID lookup response JSON")?;

    if !response.status.eq_ignore_ascii_case("ok") {
        bail!("AcoustID lookup returned status '{}'", response.status);
    }

    let mut ordered_results = response.results;
    ordered_results.sort_by(|left, right| {
        right
            .score
            .unwrap_or_default()
            .partial_cmp(&left.score.unwrap_or_default())
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    let Some(best) = ordered_results.into_iter().next() else {
        return Ok(AcoustIdMatch::default());
    };

    let Some(recording) = best.recordings.into_iter().find(|recording| !recording.id.is_empty())
    else {
        return Ok(AcoustIdMatch::default());
    };

    let release_mbid: Option<String> = recording
        .releases
        .into_iter()
        .map(|release| release.id)
        .find(|value| !value.trim().is_empty());

    Ok(AcoustIdMatch { recording_mbid: Some(recording.id), release_mbid })
}

/// Recording + optional release payload fetched from MusicBrainz.
#[derive(Debug, Clone)]
struct MusicBrainzPayload {
    /// Recording entity resolved from MusicBrainz API.
    recording: Recording,
    /// Optional release entity resolved from MusicBrainz API.
    release: Option<Release>,
}

/// Fetches recording/release payloads through `musicbrainz_rs`.
async fn fetch_musicbrainz_payloads(
    recording_mbid: &str,
    release_mbid: Option<&str>,
) -> anyhow::Result<MusicBrainzPayload> {
    let recording = Recording::fetch()
        .id(recording_mbid)
        .with_artists()
        .with_releases()
        .with_isrcs()
        .with_genres()
        .with_tags()
        .with_annotations()
        .with_work_level_relations()
        .execute()
        .await
        .with_context(|| format!("fetching MusicBrainz recording '{recording_mbid}'"))?;

    let release_id = release_mbid.map(ToOwned::to_owned).or_else(|| {
        recording
            .releases
            .as_ref()
            .and_then(|releases| releases.first())
            .map(|release| release.id.clone())
    });

    let release = if let Some(release_id) = release_id {
        Some(
            Release::fetch()
                .id(&release_id)
                .with_artists()
                .with_recordings()
                .with_release_groups()
                .with_media()
                .with_labels()
                .with_isrcs()
                .with_genres()
                .with_tags()
                .with_annotations()
                .with_recording_level_relations()
                .with_release_group_level_relations()
                .execute()
                .await
                .with_context(|| format!("fetching MusicBrainz release '{release_id}'"))?,
        )
    } else {
        None
    };

    Ok(MusicBrainzPayload { recording, release })
}

/// Converts MusicBrainz payload into FFmetadata key/value map.
fn build_ffmetadata_map(payload: &MusicBrainzPayload) -> anyhow::Result<BTreeMap<String, String>> {
    let mut tags = BTreeMap::new();

    tags.insert("title".to_string(), payload.recording.title.clone());
    tags.insert("musicbrainz_recordingid".to_string(), payload.recording.id.clone());

    if let Some(artist) = artist_credit_text(payload.recording.artist_credit.as_deref()) {
        tags.insert("artist".to_string(), artist);
    }

    if let Some(first_release_date) = payload.recording.first_release_date.as_ref() {
        tags.insert("originaldate".to_string(), first_release_date.0.clone());
    }

    if let Some(isrcs) = payload.recording.isrcs.as_ref()
        && !isrcs.is_empty()
    {
        tags.insert("isrc".to_string(), join_unique(isrcs.iter().map(String::as_str)));
    }

    if let Some(genres) = payload.recording.genres.as_ref() {
        let genre_values = genres.iter().map(|genre| genre.name.as_str()).collect::<Vec<_>>();
        if !genre_values.is_empty() {
            tags.insert("genre".to_string(), join_unique(genre_values));
        }
    }

    if let Some(recording_tags) = payload.recording.tags.as_ref() {
        let values = recording_tags.iter().map(|tag| tag.name.as_str()).collect::<Vec<_>>();
        if !values.is_empty() {
            tags.insert("musicbrainz_recording_tags".to_string(), join_unique(values));
        }
    }

    if let Some(release) = payload.release.as_ref() {
        tags.insert("album".to_string(), release.title.clone());
        tags.insert("musicbrainz_albumid".to_string(), release.id.clone());

        if let Some(date) = release.date.as_ref() {
            tags.insert("date".to_string(), date.0.clone());
        }
        if let Some(barcode) = release.barcode.as_ref()
            && !barcode.trim().is_empty()
        {
            tags.insert("barcode".to_string(), barcode.clone());
        }
        if let Some(country) = release.country.as_ref()
            && !country.trim().is_empty()
        {
            tags.insert("releasecountry".to_string(), country.clone());
        }
        if let Some(label_info) = release.label_info.as_ref() {
            let labels = label_info
                .iter()
                .filter_map(|info| info.label.as_ref().map(|label| label.name.as_str()))
                .collect::<Vec<_>>();
            if !labels.is_empty() {
                tags.insert("label".to_string(), join_unique(labels));
            }

            let catalog_numbers = label_info
                .iter()
                .filter_map(|info| info.catalog_number.as_deref())
                .collect::<Vec<_>>();
            if !catalog_numbers.is_empty() {
                tags.insert("catalognumber".to_string(), join_unique(catalog_numbers));
            }
        }

        if let Some(release_group) = release.release_group.as_ref() {
            tags.insert("musicbrainz_releasegroupid".to_string(), release_group.id.clone());
            tags.insert("release_group".to_string(), release_group.title.clone());
        }

        if let Some(release_artist) = artist_credit_text(release.artist_credit.as_deref()) {
            tags.insert("album_artist".to_string(), release_artist);
        }

        if let Some(track_info) = resolve_track_position(&payload.recording.id, release) {
            tags.insert("track".to_string(), track_info.track_number);
            tags.insert("disc".to_string(), track_info.disc_number.to_string());
            if let Some(total_tracks) = track_info.total_tracks {
                tags.insert("tracktotal".to_string(), total_tracks.to_string());
            }
            if let Some(total_discs) = track_info.total_discs {
                tags.insert("disctotal".to_string(), total_discs.to_string());
            }
        }

        if let Some(release_tags) = release.tags.as_ref() {
            let values = release_tags.iter().map(|tag| tag.name.as_str()).collect::<Vec<_>>();
            if !values.is_empty() {
                tags.insert("musicbrainz_release_tags".to_string(), join_unique(values));
            }
        }

        if let Some(release_genres) = release.genres.as_ref() {
            let values = release_genres.iter().map(|genre| genre.name.as_str()).collect::<Vec<_>>();
            if !values.is_empty() {
                tags.insert("album_genre".to_string(), join_unique(values));
            }
        }
    }

    flatten_entity_json(
        "musicbrainz_recording",
        &serde_json::to_value(&payload.recording)?,
        &mut tags,
    );
    if let Some(release) = payload.release.as_ref() {
        flatten_entity_json("musicbrainz_release", &serde_json::to_value(release)?, &mut tags);
    }

    Ok(tags)
}

/// Track-position metadata resolved from release media structure.
#[derive(Debug, Clone, PartialEq, Eq)]
struct TrackPosition {
    /// Human-facing track number from the release tracklist.
    track_number: String,
    /// One-based disc index in release media ordering.
    disc_number: u32,
    /// Optional total track count for the current disc.
    total_tracks: Option<u32>,
    /// Optional total disc count for the release.
    total_discs: Option<u32>,
}

/// Resolves track/disc position metadata by matching recording MBID.
fn resolve_track_position(recording_mbid: &str, release: &Release) -> Option<TrackPosition> {
    let medias = release.media.as_ref()?;

    for media in medias {
        let tracks = media.tracks.as_ref()?;
        for track in tracks {
            let Some(recording) = track.recording.as_ref() else {
                continue;
            };
            if recording.id != recording_mbid {
                continue;
            }

            return Some(TrackPosition {
                track_number: track.number.clone(),
                disc_number: media.position.unwrap_or(1),
                total_tracks: Some(media.track_count),
                total_discs: media.disc_count,
            });
        }
    }

    None
}

/// Converts artist-credit list into stable display string.
fn artist_credit_text(
    artist_credit: Option<&[musicbrainz_rs::entity::artist_credit::ArtistCredit]>,
) -> Option<String> {
    let artist_credit = artist_credit?;
    if artist_credit.is_empty() {
        return None;
    }

    let mut combined = String::new();
    for credit in artist_credit {
        combined.push_str(&credit.name);
        if let Some(join_phrase) = credit.joinphrase.as_deref() {
            combined.push_str(join_phrase);
        }
    }

    if combined.trim().is_empty() { None } else { Some(combined) }
}

/// Joins string values while preserving first-seen order and uniqueness.
fn join_unique<'a>(values: impl IntoIterator<Item = &'a str>) -> String {
    let mut seen = BTreeSet::new();
    let mut ordered = Vec::new();

    for value in values {
        let trimmed = value.trim();
        if trimmed.is_empty() {
            continue;
        }
        if seen.insert(trimmed.to_string()) {
            ordered.push(trimmed.to_string());
        }
    }

    ordered.join("; ")
}

/// Flattens one arbitrary JSON tree into FFmetadata-safe key/value pairs.
fn flatten_entity_json(prefix: &str, value: &Value, out: &mut BTreeMap<String, String>) {
    fn walk(prefix: &str, value: &Value, out: &mut BTreeMap<String, String>) {
        if out.len() >= MAX_FLATTENED_METADATA_ENTRIES {
            return;
        }

        match value {
            Value::Object(map) => {
                let mut entries = map.iter().collect::<Vec<_>>();
                entries.sort_by(|(left, _), (right, _)| left.cmp(right));
                for (key, nested) in entries {
                    let nested_prefix = format!("{prefix}_{key}");
                    walk(&nested_prefix, nested, out);
                }
            }
            Value::Array(items) => {
                if items.iter().all(is_scalar_json_value) {
                    let joined = items
                        .iter()
                        .filter_map(json_scalar_to_string)
                        .collect::<Vec<_>>()
                        .join("; ");
                    let key = sanitize_metadata_key(prefix);
                    if !joined.is_empty() {
                        out.insert(key, truncate_metadata_value(&joined));
                    }
                } else {
                    for (index, nested) in items.iter().enumerate() {
                        walk(&format!("{prefix}_{index}"), nested, out);
                    }
                }
            }
            _ => {
                if let Some(rendered) = json_scalar_to_string(value)
                    && !rendered.is_empty()
                {
                    out.insert(sanitize_metadata_key(prefix), truncate_metadata_value(&rendered));
                }
            }
        }
    }

    walk(prefix, value, out);
}

/// Returns true when one JSON value can be represented as scalar metadata text.
fn is_scalar_json_value(value: &Value) -> bool {
    matches!(value, Value::Null | Value::Bool(_) | Value::Number(_) | Value::String(_))
}

/// Converts one scalar JSON value into metadata text.
fn json_scalar_to_string(value: &Value) -> Option<String> {
    match value {
        Value::Null => None,
        Value::Bool(flag) => Some(flag.to_string()),
        Value::Number(number) => Some(number.to_string()),
        Value::String(text) => normalize_optional_text(Some(text)),
        _ => None,
    }
}

/// Sanitizes one metadata key for broad ffmpeg tag compatibility.
fn sanitize_metadata_key(input: &str) -> String {
    let mut key =
        input
            .chars()
            .map(|character| {
                if character.is_ascii_alphanumeric() { character.to_ascii_lowercase() } else { '_' }
            })
            .collect::<String>();

    while key.contains("__") {
        key = key.replace("__", "_");
    }
    key = key.trim_matches('_').to_string();

    if key.is_empty() {
        return "metadata".to_string();
    }
    if key.starts_with(|character: char| character.is_ascii_digit()) {
        return format!("meta_{key}");
    }

    key
}

/// Truncates one metadata value to bounded maximum length.
fn truncate_metadata_value(value: &str) -> String {
    if value.len() <= MAX_FLATTENED_VALUE_LEN {
        value.to_string()
    } else {
        value.chars().take(MAX_FLATTENED_VALUE_LEN).collect::<String>()
    }
}

/// Persists one FFmetadata document to requested output path.
fn write_ffmetadata_document(
    output_path: &Path,
    metadata_map: &BTreeMap<String, String>,
) -> anyhow::Result<()> {
    let document = FFMetadata {
        global: metadata_map
            .iter()
            .map(|(key, value)| (key.clone(), value.clone()))
            .collect::<Vec<_>>(),
        ..FFMetadata::default()
    };

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!("creating ffmetadata output directory '{}'", parent.display())
        })?;
    }

    fs::write(output_path, document.to_string())
        .with_context(|| format!("writing ffmetadata file '{}'", output_path.display()))?;

    Ok(())
}

/// Returns normalized, non-empty optional string value.
fn normalize_optional_text(value: Option<&str>) -> Option<String> {
    value.map(str::trim).filter(|value| !value.is_empty()).map(ToString::to_string)
}

#[cfg(test)]
mod tests {
    use tempfile::tempdir;

    use super::{
        DEFAULT_ACOUSTID_ENDPOINT, DEFAULT_MUSICBRAINZ_ENDPOINT, InternalMediaTaggerOptions,
        require_acoustid_api_key_for_lookup, run_internal_media_tagger,
    };

    /// Protects strict autodetection policy: when `recording_mbid` is absent,
    /// missing/blank AcoustID credentials must fail immediately.
    #[tokio::test]
    async fn run_internal_media_tagger_fails_when_acoustid_key_is_missing_for_autodetect() {
        let workspace = tempdir().expect("tempdir");
        let input_path = workspace.path().join("input.mp3");
        let output_path = workspace.path().join("output.ffmetadata");
        std::fs::write(&input_path, b"dummy-bytes").expect("write input media stub");

        let result = run_internal_media_tagger(InternalMediaTaggerOptions {
            input_path,
            output_path: output_path.clone(),
            acoustid_api_key: Some("   ".to_string()),
            acoustid_endpoint: DEFAULT_ACOUSTID_ENDPOINT.to_string(),
            musicbrainz_endpoint: DEFAULT_MUSICBRAINZ_ENDPOINT.to_string(),
            strict_identification: false,
            recording_mbid: None,
            release_mbid: None,
            ffmpeg_bin: "ffmpeg-missing-for-skipped-lookup".to_string(),
        })
        .await;

        let error = result.expect_err("missing key on autodetect path must fail");
        assert!(
            error.to_string().contains("AcoustID lookup requires a non-empty API key"),
            "expected strict missing-key failure but got: {error:#}"
        );
        assert!(
            !error.to_string().contains("decoding media for fingerprinting"),
            "missing-key validation should fail before decode path"
        );

        assert!(
            output_path.exists(),
            "wrapper should still write fallback ffmetadata output after error"
        );
    }

    /// Protects helper behavior that enforces explicit key presence for
    /// autodetection lookups.
    #[test]
    fn require_acoustid_api_key_for_lookup_enforces_non_empty_key() {
        let missing = require_acoustid_api_key_for_lookup(None).expect_err("missing key must fail");
        assert!(
            missing.to_string().contains("AcoustID lookup requires a non-empty API key"),
            "expected missing-key diagnostic"
        );

        let provided = require_acoustid_api_key_for_lookup(Some("demo-key".to_string()))
            .expect("non-empty key should pass");
        assert_eq!(provided, "demo-key");
    }

    /// Protects phase-3 behavior that when credentials are supplied, the
    /// AcoustID lookup path is attempted and failures are surfaced.
    #[tokio::test]
    async fn run_internal_media_tagger_with_key_attempts_lookup_path() {
        let workspace = tempdir().expect("tempdir");
        let input_path = workspace.path().join("input.mp3");
        let output_path = workspace.path().join("output.ffmetadata");
        std::fs::write(&input_path, b"dummy-bytes").expect("write input media stub");

        let result = run_internal_media_tagger(InternalMediaTaggerOptions {
            input_path,
            output_path: output_path.clone(),
            acoustid_api_key: Some("demo-key".to_string()),
            acoustid_endpoint: DEFAULT_ACOUSTID_ENDPOINT.to_string(),
            musicbrainz_endpoint: DEFAULT_MUSICBRAINZ_ENDPOINT.to_string(),
            strict_identification: false,
            recording_mbid: None,
            release_mbid: None,
            ffmpeg_bin: "ffmpeg-missing-for-lookup-attempt".to_string(),
        })
        .await;

        let error = result.expect_err("provided key should execute lookup path");
        assert!(
            error.to_string().contains("decoding media for fingerprinting"),
            "expected decode path failure when lookup path is active"
        );
        assert!(
            output_path.exists(),
            "ffmetadata output should still exist for workflow output-capture consistency"
        );
    }
}
