//! Tool lifecycle transitions.
//!
//! This module manages content-map hash validation and internal launcher
//! file regeneration for managed tools.

use std::path::Path;

use mediapm_conductor::NickelDocument;

use crate::error::MediaPmError;

/// Returns true when the tool name identifies a builtin source-ingest
/// tool that requires special content-ingestion handling.
#[must_use]
pub(super) fn is_builtin_source_ingest_requirement(tool_name: &str) -> bool {
    tool_name.eq_ignore_ascii_case("import")
}

/// Checks whether a content-map hash value is still referenced by any
/// tool runtime in the document.
#[allow(dead_code)]
#[must_use]
pub(super) fn is_hash_in_tool_content_maps(hash: &str, document: &NickelDocument) -> bool {
    document.tools.values().any(|spec| spec.runtime.content_map.values().any(|v| v == hash))
}

/// Stores a CAS lock marker for a provisioned tool registry version.
///
/// Creates a deterministic marker payload `registry-locks/<tool_id>/<version>`
/// and stores it in CAS. The returned hex hash uniquely identifies the locked
/// version — identical inputs produce the same hash, making the operation
/// idempotent.
///
/// Returns `None` when `identity` is empty.
#[allow(dead_code)]
pub(super) async fn lock_registry_version(
    cas: &impl mediapm_cas::CasApi,
    tool_id: &str,
    identity: &str,
) -> Option<String> {
    if identity.is_empty() {
        return None;
    }
    let marker = format!("registry-locks/{tool_id}/{identity}");
    let hash = cas.put(bytes::Bytes::from(marker)).await.ok()?;
    Some(hash.to_hex())
}

/// Ensures that `media-tagger` internal launcher content entries exist in the
/// generated document and content map.
pub(super) fn ensure_internal_launcher_content_entries_exist(
    document: &mut NickelDocument,
    tools_dir: &Path,
) {
    let launcher_tool_id = "media-tagger";
    let launcher_name = "media-tagger-launcher";

    if let Some(spec) = document.tools.get_mut(launcher_tool_id)
        && !spec.runtime.content_map.contains_key(launcher_name)
    {
        let launcher_path = tools_dir.join(launcher_tool_id).join(launcher_name);
        // Register the launcher path as a content-map entry placeholder.
        // The actual file is materialized by regenerate_media_tagger_internal_launcher_file.
        spec.runtime
            .content_map
            .insert(launcher_name.to_string(), launcher_path.to_string_lossy().to_string());
    }
}

/// Regenerates the `media-tagger` launcher file for the current platform.
///
/// `mediapm_bin` is the path to the current `mediapm` binary, resolved at
/// generation time so the launcher script dispatches to the same binary.
pub(super) fn regenerate_media_tagger_internal_launcher_file(
    tools_dir: &Path,
    mediapm_bin: &std::path::Path,
) -> Result<(), MediaPmError> {
    let launcher_dir = tools_dir.join("media-tagger");
    std::fs::create_dir_all(&launcher_dir).map_err(|source| MediaPmError::Io {
        operation: "creating media-tagger launcher directory".to_string(),
        path: launcher_dir.clone(),
        source,
    })?;

    let launcher_path = launcher_dir.join("media-tagger-launcher");
    let launcher_content = generate_media_tagger_launcher_content(mediapm_bin);

    std::fs::write(&launcher_path, launcher_content.as_bytes()).map_err(|source| {
        MediaPmError::Io {
            operation: "writing media-tagger launcher file".to_string(),
            path: launcher_path.clone(),
            source,
        }
    })?;

    Ok(())
}

/// Generates the platform-specific launcher script content for media-tagger.
///
/// On Unix (macOS/Linux) this produces a shell script that dispatches to the
/// `mediapm` binary's builtin command. On Windows this produces a batch script.
#[must_use]
fn generate_media_tagger_launcher_content(mediapm_bin: &std::path::Path) -> String {
    let bin_str = mediapm_bin.to_string_lossy();
    if cfg!(windows) {
        format!(
            "@echo off\r\n\
             rem media-tagger launcher (generated by mediapm)\r\n\
             \"{bin_str}\" builtin media-tagger %*\r\n",
        )
    } else {
        format!(
            "#!/bin/sh\n\
             # media-tagger launcher (generated by mediapm)\n\
             exec \"{bin_str}\" builtin media-tagger \"$@\"\n",
        )
    }
}
