//! Tool-config generation and companion-dependency binding.
//!
//! This module resolves companion tool selectors (ffmpeg, deno for yt-dlp),
//! generates runtime environment files, and manages content-map prefixing
//! for same-step companion dependencies.

use std::collections::BTreeMap;
use std::fmt::Write;

use mediapm_conductor::ToolRuntime;

use crate::config::{MediaMetadataValue, ToolRequirement};
use crate::error::MediaPmError;
use crate::paths::MediaPmPaths;

use super::super::util::write_bytes_if_changed;

/// Header prefix for machine-generated runtime dotenv values.
const GENERATED_RUNTIME_ENV_HEADER: &str = concat!(
    "# @generated by mediapm\n",
    "# Managed runtime environment variables for conductor execution.\n",
    "# Do not edit manually; values may be rewritten during sync.\n\n",
);

/// Resolves the companion ffmpeg selection for a tool from its dependency config.
///
/// Searches all tool requirements for the first non-default `ffmpeg_version`
/// literal dependency value and returns it. Returns `None` when no override
/// is specified (the global default applies).
#[must_use]
pub(super) fn resolve_companion_ffmpeg_selection(
    requirements: &BTreeMap<String, serde_json::Value>,
) -> Option<String> {
    for value in requirements.values() {
        if let Ok(requirement) = serde_json::from_value::<ToolRequirement>(value.clone())
            && let Some(version) = requirement.dependencies.ffmpeg_version
            && let MediaMetadataValue::Literal(v) = version
            && !v.is_empty()
            && !v.eq_ignore_ascii_case("inherit")
        {
            return Some(v);
        }
    }
    None
}

/// Resolves the companion deno selection for a tool from its dependency config.
///
/// Searches all tool requirements for the first non-default `deno_version`
/// literal dependency value and returns it. Returns `None` when no override
/// is specified (the global default applies).
#[must_use]
pub(super) fn resolve_companion_deno_selection(
    requirements: &BTreeMap<String, serde_json::Value>,
) -> Option<String> {
    for value in requirements.values() {
        if let Ok(requirement) = serde_json::from_value::<ToolRequirement>(value.clone())
            && let Some(version) = requirement.dependencies.deno_version
            && let MediaMetadataValue::Literal(v) = version
            && !v.is_empty()
            && !v.eq_ignore_ascii_case("inherit")
        {
            return Some(v);
        }
    }
    None
}

/// Prefixes same-step companion content-map entries to distinguish them from
/// the requester's own payload entries.
#[allow(dead_code)]
#[must_use]
pub(super) fn prefix_same_step_companion_content_map(
    companion_prefix: &str,
    companion_content_map: &BTreeMap<String, String>,
) -> BTreeMap<String, String> {
    companion_content_map
        .iter()
        .map(|(k, v)| (format!("{companion_prefix}{k}"), v.clone()))
        .collect()
}

/// Prefixes same-step companion content-map entries (value type is
/// [`mediapm_conductor::Hash`] string representation).
#[allow(dead_code)]
#[must_use]
pub(super) fn prefix_same_step_companion_content_entries(
    companion_prefix: &str,
    entries: &BTreeMap<String, String>,
) -> BTreeMap<String, String> {
    prefix_same_step_companion_content_map(companion_prefix, entries)
}

/// Writes the generated runtime `.env` file with tool binary paths.
///
/// Iterates over resolved tool runtimes and emits one dotenv entry per
/// content-map key mapping the resolved tool id and relative path to an
/// env var of the form `MEDIAPM_<TOOL_ID_UPPER>_<KEY_UPPER>=<full_path>`.
pub(super) fn write_generated_runtime_env_file(
    paths: &MediaPmPaths,
    tool_runtimes: &BTreeMap<String, ToolRuntime>,
) -> Result<(), MediaPmError> {
    let generated_path = &paths.env_generated_file;

    let mut content = String::from(GENERATED_RUNTIME_ENV_HEADER);
    for (tool_id, runtime) in tool_runtimes {
        for key in runtime.content_map.keys() {
            let env_name = format!(
                "MEDIAPM_{}_{}",
                tool_id.to_uppercase().replace(['-', '.'], "_"),
                key.to_uppercase().replace(['-', '.'], "_"),
            );
            let env_value = paths.tools_dir.join(key).to_string_lossy().to_string();
            let _ = writeln!(content, "{env_name}={}", render_dotenv_quoted_value(&env_value));
        }
    }

    write_bytes_if_changed(
        generated_path,
        content.as_bytes(),
        "writing generated runtime dotenv values",
    )
}

/// Ensures the machine runtime inherits generated environment variables.
///
/// Reads the generated env file and adds each entry to every tool spec's
/// `inherited_env_vars` so tool processes receive the resolved binary paths.
pub(super) fn ensure_machine_runtime_inherits_generated_env_vars(
    document: &mut mediapm_conductor::NickelDocument,
    generated_env_path: &str,
) {
    let Ok(content) = std::fs::read_to_string(generated_env_path) else {
        return; // File not yet generated; nothing to inherit.
    };

    let mut generated_vars: BTreeMap<String, String> = BTreeMap::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(eq_pos) = line.find('=') {
            let name = line[..eq_pos].trim().to_string();
            let value = line[eq_pos + 1..].trim().to_string();
            if !name.is_empty() {
                generated_vars.insert(name, value);
            }
        }
    }

    if generated_vars.is_empty() {
        return;
    }

    for tool_spec in document.tools.values_mut() {
        for (name, value) in &generated_vars {
            tool_spec
                .runtime
                .inherited_env_vars
                .entry(name.clone())
                .or_insert_with(|| value.clone());
        }
    }
}

/// Renders one dotenv value as a double-quoted literal with escapes.
#[must_use]
fn render_dotenv_quoted_value(value: &str) -> String {
    let escaped = value
        .replace("\\\\", "\\\\\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t");
    format!("\"{escaped}\"")
}
