//! Ordered option-name constants per managed tool.
//!
//! Each constant defines the canonical iteration order for option inputs
//! used by [`super::option_tokens`] to produce CLI token sequences.

#![allow(dead_code)]
// TODO: Stream A stubs — wired when provisioning pipeline is complete.

/// Ordered ffmpeg option input names.
pub(super) const FFMPEG_OPTION_INPUTS: &[&str] = &[
    "option_args",
    "vn",
    "an",
    "sn",
    "dn",
    "codec_copy",
    "codec_video",
    "codec_audio",
    "codec_subtitle",
    "pixel_format",
    "max_muxing_queue_size",
    "threads",
    "preset",
    "crf",
    "bitrate_video",
    "bitrate_audio",
    "sample_rate",
    "channels",
    "volume",
    "filter_complex",
    "filter_video",
    "filter_audio",
    "filter_subtitle",
    "map_metadata",
    "map_chapters",
    "metadata",
    "timestamp",
    "ss",
    "t",
    "to",
    "frames",
    "frame_rate",
    "resolution",
    "aspect",
    "crop",
    "rotate",
    "hflip",
    "vflip",
    "color_balance",
    "color_brightness",
    "color_contrast",
    "color_saturation",
    "color_gamma",
    "deinterlace",
    "denoise",
    "sharpness",
    "subtitles",
    "ass_subtitles",
    "watermark",
    "watermark_position",
    "movflags",
    "cues_to_front",
    "audio_codec",
    "audio_bitrate",
    "audio_sample_rate",
    "audio_channels",
    "hide_banner",
    "overwrite_output",
];

/// Ordered yt-dlp option input names.
pub(super) const YT_DLP_OPTION_INPUTS: &[&str] = &[
    "option_args",
    "format",
    "output",
    "paths",
    "playlist_start",
    "playlist_end",
    "playlist_reverse",
    "playlist_random",
    "match_title",
    "reject_title",
    "max_downloads",
    "min_filesize",
    "max_filesize",
    "date",
    "dateafter",
    "datebefore",
    "sub_langs",
    "write_subs",
    "write_auto_subs",
    "embed_subs",
    "sub_format",
    "merge_output_format",
    "extract_audio",
    "audio_format",
    "audio_quality",
    "remux_video",
    "recode_video",
    "postprocessor_args",
    "embed_thumbnail",
    "embed_metadata",
    "embed_chapters",
    "embed_info_json",
    "write_thumbnail",
    "write_all_thumbnails",
    "write_info_json",
    "clean_info_json",
    "write_comments",
    "write_description",
    "write_annotations",
    "write_chapters",
    "write_link",
    "write_url_link",
    "write_webloc_link",
    "write_desktop_link",
    "download_archive",
    "split_chapters",
    "no_playlist",
    "yes_playlist",
    "limit_rate",
    "retries",
    "fragment_retries",
    "skip_unavailable_fragments",
    "abort_on_unavailable_fragment",
    "extractor_args",
    "cache_dir",
    "cookies",
    "cookies_from_browser",
    "ffmpeg_location",
    "concurrent_fragment_downloads",
];

/// Ordered rsgain option input names.
pub(super) const RSGAIN_OPTION_INPUTS: &[&str] = &[
    "option_args",
    "input_extension",
    "album",
    "album_mode",
    "target_lufs",
    "tagmode",
    "clip_mode",
    "true_peak",
    "max_peak",
    "preserve_mtimes",
    "loudness_range",
    "integrated_loudness",
    "true_peak_level",
    "lra_loudness",
    "loudness_correction",
    "sample_peak",
    "bit_depth",
    "dynamic_range",
    "dynamic_range_max",
    "dynamic_range_count",
    "dynamic_range_avg",
    "dynamic_range_stdev",
    "dynamic_range_threshold",
    "dynamic_range_histogram",
    "dynamic_range_histogram_count",
    "dynamic_range_histogram_bins",
];

/// Ordered media-tagger option input names.
pub(super) const MEDIA_TAGGER_OPTION_INPUTS: &[&str] = &[
    "option_args",
    "strict_identification",
    "write_all_tags",
    "write_all_images",
    "save_images_to_tags",
    "enable_tag_saving",
    "embed_only_one_front_image",
    "ca_providers",
    "caa_image_types",
    "caa_image_size",
    "caa_approved_only",
    "preserve_images",
    "clear_existing_tags",
    "release_ars",
    "cover_art_slot_count",
    "acoustid_endpoint",
    "musicbrainz_endpoint",
    "cache_dir",
    "cache_expiry_seconds",
    "acoustid_api_key",
    "enable_acoustid",
];

/// Resolves the ordered option input names for a given tool.
#[must_use]
pub(super) fn option_input_names_for_tool(tool_name: &str) -> &'static [&'static str] {
    if tool_name.eq_ignore_ascii_case("ffmpeg") {
        FFMPEG_OPTION_INPUTS
    } else if tool_name.eq_ignore_ascii_case("yt-dlp") {
        YT_DLP_OPTION_INPUTS
    } else if tool_name.eq_ignore_ascii_case("rsgain") {
        RSGAIN_OPTION_INPUTS
    } else if tool_name.eq_ignore_ascii_case("media-tagger") {
        MEDIA_TAGGER_OPTION_INPUTS
    } else {
        &[]
    }
}
