//! Ordered option-name constants per managed tool.
//!
//! Each constant defines the canonical iteration order for option inputs
//! used by [`super::option_tokens`] to produce CLI token sequences.
//! Names must match the corresponding [`TokenSpec`] keys in
//! `option_tokens.rs`.

#![allow(dead_code)]

/// Ordered ffmpeg option input names.
pub(super) const FFMPEG_OPTION_INPUTS: &[&str] = &[
    "option_args",
    "vn",
    "an",
    "sn",
    "dn",
    "codec_copy",
    "audio_codec",
    "video_codec",
    "container",
    "audio_bitrate",
    "video_bitrate",
    "audio_quality",
    "video_quality",
    "crf",
    "preset",
    "threads",
    "log_level",
    "progress",
    "tune",
    "profile",
    "level",
    "pixel_format",
    "frame_rate",
    "sample_rate",
    "channels",
    "audio_filters",
    "video_filters",
    "filter_complex",
    "start_time",
    "duration",
    "to",
    "movflags",
    "cues_to_front",
    "map_metadata",
    "map_chapters",
    "map",
    "map_channel",
    "copy_ts",
    "start_at_zero",
    "stats",
    "no_overwrite",
    "faststart",
    "hwaccel",
    "sample_format",
    "channel_layout",
    "metadata",
    "timestamp",
    "disposition",
    "fps_mode",
    "force_key_frames",
    "aspect",
    "stream_loop",
    "max_muxing_queue_size",
    "strict",
    "maxrate",
    "bufsize",
    "bitstream_filter",
    "id3v2_version",
    "shortest",
    "hide_banner",
    // Extra new-style options
    "codec_video",
    "codec_audio",
    "codec_subtitle",
    "overwrite_output",
    "volume",
    "filter_video",
    "filter_audio",
    "filter_subtitle",
    "ss",
    "frames",
    "resolution",
    "aspect",
    "crop",
    "rotate",
    "hflip",
    "vflip",
    "color_balance",
    "color_brightness",
    "color_contrast",
    "color_saturation",
    "color_gamma",
    "deinterlace",
    "denoise",
    "sharpness",
    "subtitles",
    "ass_subtitles",
    "watermark",
    "watermark_position",
];

/// Ordered yt-dlp option input names.
pub(super) const YT_DLP_OPTION_INPUTS: &[&str] = &[
    "option_args",
    "format",
    "format_sort",
    "extract_audio",
    "audio_format",
    "audio_quality",
    "remux_video",
    "recode_video",
    "merge_output_format",
    "embed_thumbnail",
    "embed_metadata",
    "embed_subs",
    "embed_chapters",
    "embed_info_json",
    "write_subs",
    "write_auto_subs",
    "sub_langs",
    "sub_format",
    "convert_subs",
    "write_thumbnail",
    "write_all_thumbnails",
    "convert_thumbnails",
    "write_info_json",
    "clean_info_json",
    "write_comments",
    "write_description",
    "write_annotations",
    "write_chapters",
    "write_link",
    "write_url_link",
    "write_webloc_link",
    "write_desktop_link",
    "split_chapters",
    "playlist_items",
    "no_playlist",
    "yes_playlist",
    "skip_download",
    "retries",
    "limit_rate",
    "concurrent_fragments",
    "proxy",
    "socket_timeout",
    "sleep_subtitles",
    "user_agent",
    "referer",
    "add_header",
    "cookies",
    "cookies_from_browser",
    "cache_dir",
    "js_runtimes",
    "ffmpeg_location",
    "paths",
    "output",
    "parse_metadata",
    "replace_in_metadata",
    "download_sections",
    "postprocessor_args",
    "extractor_args",
    "http_chunk_size",
    "download_archive",
    "sponsorblock_mark",
    "sponsorblock_remove",
    // Extra new-style options
    "playlist_start",
    "playlist_end",
    "playlist_reverse",
    "playlist_random",
    "match_title",
    "reject_title",
    "max_downloads",
    "min_filesize",
    "max_filesize",
    "date",
    "dateafter",
    "datebefore",
    "fragment_retries",
    "skip_unavailable_fragments",
    "abort_on_unavailable_fragment",
    "concurrent_fragment_downloads",
];

/// Ordered rsgain option input names.
pub(super) const RSGAIN_OPTION_INPUTS: &[&str] = &[
    "option_args",
    "input_extension",
    "mode",
    "album",
    "album_aes77",
    "skip_existing",
    "tagmode",
    "target_lufs",
    "loudness",
    "clip_mode",
    "true_peak",
    "dual_mono",
    "album_mode",
    "max_peak",
    "lowercase",
    "id3v2_version",
    "opus_mode",
    "multithread",
    "jobs",
    "preset",
    "dry_run",
    "output",
    "quiet",
    "skip_tags",
    "preserve_mtime",
    "preserve_mtimes",
    // Extra new-style options
    "loudness_range",
    "integrated_loudness",
    "true_peak_level",
    "lra_loudness",
    "loudness_correction",
    "sample_peak",
    "bit_depth",
    "dynamic_range",
    "dynamic_range_max",
    "dynamic_range_count",
    "dynamic_range_avg",
    "dynamic_range_stdev",
    "dynamic_range_threshold",
    "dynamic_range_histogram",
    "dynamic_range_histogram_count",
    "dynamic_range_histogram_bins",
];

/// Ordered media-tagger option input names.
pub(super) const MEDIA_TAGGER_OPTION_INPUTS: &[&str] = &[
    "option_args",
    "acoustid_endpoint",
    "musicbrainz_endpoint",
    "cache_dir",
    "cache_expiry_seconds",
    "strict_identification",
    "write_all_tags",
    "write_all_images",
    "save_images_to_tags",
    "embed_only_one_front_image",
    "ca_providers",
    "caa_image_types",
    "caa_image_size",
    "caa_approved_only",
    "preserve_images",
    "clear_existing_tags",
    "enable_tag_saving",
    "release_ars",
    "cover_art_slot_count",
    "recording_mbid",
    "release_mbid",
    // Extra new-style options
    "acoustid_api_key",
    "enable_acoustid",
];

/// Resolves the ordered option input names for a given tool.
#[must_use]
pub(super) fn option_input_names_for_tool(tool_name: &str) -> &'static [&'static str] {
    if tool_name.eq_ignore_ascii_case("ffmpeg") {
        FFMPEG_OPTION_INPUTS
    } else if tool_name.eq_ignore_ascii_case("yt-dlp") {
        YT_DLP_OPTION_INPUTS
    } else if tool_name.eq_ignore_ascii_case("rsgain") {
        RSGAIN_OPTION_INPUTS
    } else if tool_name.eq_ignore_ascii_case("media-tagger") {
        MEDIA_TAGGER_OPTION_INPUTS
    } else {
        &[]
    }
}
