//! Conductor Nickel document bootstrap/load/save helpers.

use std::fs;
use std::path::Path;

use mediapm_conductor::{NickelDocument, ToolKindSpec, ToolSpec, decode_document, encode_document};

use crate::error::MediaPmError;
use crate::paths::MediaPmPaths;
use crate::registered_builtin_ids;

use super::ConductorToolRow;
use super::tool_runtime::tool_spec_has_binary;
use super::util::write_bytes_if_changed;

/// Ownership banner for mediapm-managed conductor user document.
const GENERATED_CONDUCTOR_USER_BANNER: &str = concat!(
    "# @generated by mediapm\n",
    "# Do not edit directly; edit mediapm.ncl and rerun sync.\n\n",
);

/// Ownership banner for mediapm-managed conductor machine document.
const GENERATED_CONDUCTOR_MACHINE_BANNER: &str = concat!(
    "# @generated by mediapm\n",
    "# Do not edit directly; edit mediapm.ncl and rerun sync.\n\n",
);

/// Ensures conductor user/machine Nickel files exist for mediapm orchestration.
pub(crate) fn ensure_conductor_documents(paths: &MediaPmPaths) -> Result<(), MediaPmError> {
    if !paths.conductor_user_ncl.exists() {
        let user_document = default_user_document(paths);
        save_user_document(&paths.conductor_user_ncl, &user_document)?;
    }

    if paths.conductor_machine_ncl.exists() {
        let mut machine_document = load_machine_document(&paths.conductor_machine_ncl)?;
        let mut changed = register_missing_builtin_tools(&mut machine_document);
        changed |= register_missing_builtin_tool_configs(&mut machine_document);
        if changed {
            save_machine_document(&paths.conductor_machine_ncl, &machine_document)?;
        }
    } else {
        let machine_document = default_machine_document();
        save_machine_document(&paths.conductor_machine_ncl, &machine_document)?;
    }

    Ok(())
}

/// Creates a default user document with mediapm runtime-storage defaults.
fn default_user_document(paths: &MediaPmPaths) -> NickelDocument {
    let _ = paths; // storage paths are not embedded in documents anymore
    NickelDocument::default()
}

/// Creates a default machine document with builtin tools registered.
fn default_machine_document() -> NickelDocument {
    let mut doc = NickelDocument::default();
    register_missing_builtin_tools(&mut doc);
    register_missing_builtin_tool_configs(&mut doc);
    doc
}

/// Registers missing conductor builtin tool identities in machine config.
///
/// `mediapm` synthesized workflows may reference builtins directly
/// (for example `import@1.0.0` for local-source ingest). This helper ensures
/// those builtin ids are always present in the machine document so workflow
/// reconciliation can resolve them deterministically.
pub(crate) fn register_missing_builtin_tools(machine: &mut NickelDocument) -> bool {
    let mut changed = false;

    for tool_id in registered_builtin_ids() {
        let Some((name, version)) = parse_builtin_tool_identity(&tool_id) else {
            continue;
        };

        let should_insert = !machine.tools.contains_key(name);

        if should_insert {
            machine.tools.insert(
                name.to_string(),
                ToolSpec {
                    kind: ToolKindSpec::Builtin {
                        name: name.to_string(),
                        version: version.to_string(),
                    },
                    name: name.to_string(),
                    version: version.to_string(),
                    ..ToolSpec::default()
                },
            );
            changed = true;
        }
    }

    changed
}

/// Registers missing default runtime configuration for builtin tools.
///
/// In the current model, runtime fields are always present on `ToolSpec`
/// via serde defaults, so this function is a no-op kept for compatibility
/// with existing call sites.
pub(super) fn register_missing_builtin_tool_configs(_machine: &mut NickelDocument) -> bool {
    false
}

/// Parses one builtin identity tuple from immutable tool id text.
fn parse_builtin_tool_identity(tool_id: &str) -> Option<(&str, &str)> {
    let (raw_name, version) = tool_id.split_once('@')?;
    let name = raw_name.rsplit('.').next().unwrap_or(raw_name).trim();
    let version = version.trim();

    if name.is_empty() || version.is_empty() {
        return None;
    }

    Some((name, version))
}

/// Loads one user Nickel document from disk, returning defaults when absent.
#[allow(dead_code)]
fn load_user_document(path: &Path) -> Result<NickelDocument, MediaPmError> {
    if !path.exists() {
        return Ok(NickelDocument::default());
    }

    let bytes = fs::read(path).map_err(|source| MediaPmError::Io {
        operation: "reading mediapm.conductor.ncl".to_string(),
        path: path.to_path_buf(),
        source,
    })?;

    if bytes.iter().all(u8::is_ascii_whitespace) {
        return Ok(NickelDocument::default());
    }

    decode_document(&bytes).map_err(MediaPmError::from)
}

/// Lists conductor tools visible in machine config.
pub(crate) fn list_tools(paths: &MediaPmPaths) -> Result<Vec<ConductorToolRow>, MediaPmError> {
    let machine = load_machine_document(&paths.conductor_machine_ncl)?;
    let mut rows = machine
        .tools
        .values()
        .map(|tool_spec| {
            let tool_id = &tool_spec.name;
            let has_materialized_content = tool_spec
                .runtime
                .content_map
                .values()
                .any(|value| value.parse::<mediapm_cas::Hash>().is_ok());
            let has_binary = has_materialized_content || tool_spec_has_binary(tool_spec);

            ConductorToolRow { tool_id: tool_id.clone(), has_binary }
        })
        .collect::<Vec<_>>();

    rows.sort_by(|left, right| left.tool_id.cmp(&right.tool_id));
    Ok(rows)
}

/// Loads one machine Nickel document from disk, returning defaults when absent.
pub(crate) fn load_machine_document(path: &Path) -> Result<NickelDocument, MediaPmError> {
    if !path.exists() {
        return Ok(NickelDocument::default());
    }

    let bytes = fs::read(path).map_err(|source| MediaPmError::Io {
        operation: "reading mediapm.conductor.machine.ncl".to_string(),
        path: path.to_path_buf(),
        source,
    })?;

    if bytes.iter().all(u8::is_ascii_whitespace) {
        return Ok(NickelDocument::default());
    }

    decode_document(&bytes).map_err(MediaPmError::from)
}

/// Saves one machine Nickel document with conductor's canonical encoder.
pub(crate) fn save_machine_document(
    path: &Path,
    document: &NickelDocument,
) -> Result<(), MediaPmError> {
    let bytes = with_generated_banner(
        encode_document(document.clone())?,
        GENERATED_CONDUCTOR_MACHINE_BANNER,
    );
    write_bytes_if_changed(path, &bytes, "writing mediapm.conductor.machine.ncl")
}

/// Saves one user Nickel document with conductor's canonical encoder.
fn save_user_document(path: &Path, document: &NickelDocument) -> Result<(), MediaPmError> {
    let bytes =
        with_generated_banner(encode_document(document.clone())?, GENERATED_CONDUCTOR_USER_BANNER);
    write_bytes_if_changed(path, &bytes, "writing mediapm.conductor.ncl")
}

/// Prefixes generated-file ownership banner bytes when not already present.
#[must_use]
fn with_generated_banner(mut bytes: Vec<u8>, banner: &str) -> Vec<u8> {
    if bytes.starts_with(banner.as_bytes()) {
        return bytes;
    }

    let mut merged = banner.as_bytes().to_vec();
    merged.append(&mut bytes);
    merged
}
