//! Persistent `mediapm` demo that produces inspectable artifacts.
//!
//! This example demonstrates a fully local ingest + transform flow:
//! - loads one bundled binary MP4 fixture,
//! - imports fixture bytes into the workspace CAS,
//! - defines one managed workflow chain
//!   (`import -> ffmpeg -> rsgain -> media-tagger`),
//! - writes inspectable artifacts under `examples/.artifacts/demo`.
//!
//! Default runtime behavior executes full sync (`run_sync = true`) in manual
//! runs. When this example is executed as a Cargo test binary, it
//! auto-switches to configuration-only mode so automated runs avoid external
//! tool downloads/execution. Operators can still override via
//! `MEDIAPM_DEMO_RUN_SYNC`.

use std::collections::{BTreeMap, BTreeSet};
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};
use std::process;
use std::str::FromStr;
use std::thread;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use mediapm::{
    HierarchyNode, HierarchyNodeKind, MaterializationMethod, MediaMetadataRegexTransform,
    MediaMetadataValue, MediaMetadataVariantBinding, MediaPmApi, MediaPmService,
    MediaRuntimeStorage, MediaSourceSpec, MediaStep, MediaStepTool, PlaylistEntryPathMode,
    PlaylistFormat, PlaylistItemRef, ToolRequirement, ToolRequirementDependencies,
    TransformInputValue, load_lockfile, load_mediapm_document, save_mediapm_document,
};
use mediapm_cas::{CasApi, FileSystemCas, Hash};
use mediapm_conductor::{SimpleConductor, default_runtime_inherited_env_vars_for_host};
use same_file::is_same_file;
use serde::Serialize;
use serde_json::json;

/// Shared result type for this demo.
type ExampleResult<T> = Result<T, Box<dyn Error>>;

/// Embedded tiny MP4 payload containing both video and audio tracks.
const SAMPLE_AV_MP4_BYTES: &[u8] = include_bytes!("assets/sample-av.mp4");

/// Canonical demo media id.
const DEMO_MEDIA_ID: &str = "local-av";

/// Hierarchy id used by playlist entries to reference the tagged media file.
const DEMO_PLAYLIST_TARGET_HIERARCHY_ID: &str = "local-av-tagged";

/// Demo metadata title value used in hierarchy interpolation.
const DEMO_METADATA_TITLE: &str = "Never Gonna Give You Up";

/// Demo metadata artist value used in hierarchy interpolation.
const DEMO_METADATA_ARTIST: &str = "Rick Astley";

/// Demo metadata video-id value used in flattened hierarchy interpolation.
const DEMO_METADATA_VIDEO_ID: &str = "dQw4w9WgXcQ";

/// Demo metadata literal source value showing mixed literal + variant metadata.
const DEMO_METADATA_SOURCE_LITERAL: &str = "local-fixture";

/// Top-level library folder used by demo hierarchy entries.
const DEMO_LIBRARY_ROOT: &str = "music videos";

/// Metadata-interpolated media-folder path under `DEMO_LIBRARY_ROOT`.
const DEMO_MEDIA_FOLDER_TEMPLATE: &str =
    "${media.metadata.artist} - ${media.metadata.title} [${media.id}]";

/// Variant name used for metadata lookup bindings.
const DEMO_METADATA_VARIANT: &str = "infojson";

/// Metadata object key used for title lookup from metadata variant file.
const DEMO_METADATA_TITLE_KEY: &str = "title";

/// Metadata object key used for video-id lookup from metadata variant file.
const DEMO_METADATA_VIDEO_ID_KEY: &str = "id";

/// Metadata object key used for artist lookup from metadata variant file.
const DEMO_METADATA_ARTIST_KEY: &str = "artist";

/// Import source kind expected by runtime for CAS-hash ingest.
const IMPORT_KIND_CAS_HASH: &str = "cas_hash";

/// Environment variable controlling whether this example runs full sync.
///
/// - unset: full sync enabled in manual runs; disabled in test-binary runs,
/// - set to one of `0`, `false`, `no`, or `off` (case-insensitive): sync
///   disabled and only artifact/config generation runs.
const DEMO_RUN_SYNC_ENV_VAR: &str = "MEDIAPM_DEMO_RUN_SYNC";

/// Explicit runtime materialization preference order showcased by this demo.
const DEMO_MATERIALIZATION_PREFERENCE_ORDER: [MaterializationMethod; 4] = [
    MaterializationMethod::Hardlink,
    MaterializationMethod::Symlink,
    MaterializationMethod::Reflink,
    MaterializationMethod::Copy,
];

/// Manifest persisted under `examples/.artifacts/demo/manifest.json`.
#[derive(Debug, Clone, PartialEq, Serialize)]
#[expect(
    clippy::struct_excessive_bools,
    reason = "demo manifest intentionally records many explicit invariant flags for regression inspection"
)]
struct DemoManifest {
    /// Unix timestamp (seconds) when artifacts were generated.
    generated_unix_epoch_seconds: u64,
    /// Artifact root for this demo run.
    artifact_root: String,
    /// Demo workspace root (same path as artifact root).
    workspace_root: String,
    /// Canonical media id configured by this demo.
    media_id: String,
    /// Media id generated by one pre-configuration `add_local_source` call.
    auto_added_media_id: String,
    /// Auto-populated title written by `add_local_source`.
    auto_added_source_title: String,
    /// Auto-populated description written by `add_local_source`.
    auto_added_source_description: String,
    /// Source local MP4 fixture path used for CAS ingest.
    source_file_path: String,
    /// CAS hash string used by the `import` source step.
    source_hash: String,
    /// Whether source bytes include a video-track marker.
    source_has_video_track_marker: bool,
    /// Whether source bytes include an audio-track marker.
    source_has_audio_track_marker: bool,
    /// Configured managed tool count in `mediapm.ncl`.
    configured_tool_count: usize,
    /// Configured step count in the managed source workflow.
    configured_step_count: usize,
    /// Runtime materialization policy order written into `mediapm.ncl`.
    materialization_preference_order: Vec<String>,
    /// Materialized output path #1.
    materialized_primary_path: String,
    /// Materialized output path #2.
    materialized_secondary_path: String,
    /// Whether output #1 exists after optional sync.
    materialized_primary_exists: bool,
    /// Whether output #2 exists after optional sync.
    materialized_secondary_exists: bool,
    /// Whether output #1 is verified as a hard link to CAS object bytes.
    materialized_primary_hardlinked_to_cas: bool,
    /// Whether output #2 is verified as a hard link to CAS object bytes.
    materialized_secondary_hardlinked_to_cas: bool,
    /// Whether full sync was executed during this demo run.
    sync_executed: bool,
    /// Number of managed files recorded in lock state.
    lock_managed_files_count: usize,
    /// Number of tool-registry rows in lock state.
    lock_tool_registry_count: usize,
    /// Sync executed count.
    executed_instances: usize,
    /// Sync cache-hit count.
    cached_instances: usize,
    /// Sync rematerialized count.
    rematerialized_instances: usize,
    /// Sync materialized path count.
    materialized_paths: usize,
    /// Sync removed-path count.
    removed_paths: usize,
    /// Sync warning count.
    warning_count: usize,
    /// Path to conductor workflow profile JSON written after sync execution.
    ///
    /// The profile records per-step elapsed times for the managed pipeline.
    /// Set `MEDIAPM_CONDUCTOR_PROFILE_JSON` to override the output path.
    profile_path: String,
    /// Path to `mediapm.ncl`.
    mediapm_ncl_path: String,
    /// Path to conductor user document.
    conductor_user_ncl_path: String,
    /// Path to conductor machine document.
    conductor_machine_ncl_path: String,
    /// Path to `.mediapm/state.ncl`.
    mediapm_state_ncl_path: String,
    /// Path to resolved library root.
    library_root_path: String,
    /// Logical CAS store footprint without delta compression (bytes).
    store_size_without_delta_bytes: u64,
    /// Effective CAS store footprint with delta compression (bytes).
    store_size_with_delta_bytes: u64,
    /// Ratio `with_delta / without_delta` for quick compression comparison.
    ///
    /// Values `< 1.0` indicate on-disk savings from delta compression; values
    /// near `1.0` are expected when most payloads are already compressed.
    ///
    /// When `store_size_without_delta_bytes == 0`, this demo emits `1.0` so
    /// empty/objectless stores report a neutral ratio instead of
    /// divide-by-zero noise.
    store_size_ratio_with_delta_over_without: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
/// Aggregate CAS store-size metrics shared by manifest serialization.
struct StoreSizeStats {
    /// Logical CAS store footprint without delta compression (bytes).
    without_delta_bytes: u64,
    /// Effective CAS store footprint with delta compression (bytes).
    with_delta_bytes: u64,
}

impl StoreSizeStats {
    /// Returns `with_delta / without_delta` for manifest reporting.
    ///
    /// Values `< 1.0` indicate on-disk savings from delta compression.
    ///
    /// For zero-byte logical stores, this returns `1.0` to represent a neutral
    /// no-change baseline and avoid divide-by-zero artifacts.
    #[must_use]
    #[expect(
        clippy::cast_precision_loss,
        reason = "manifest ratio output is intentionally approximate for human-facing diagnostics"
    )]
    fn ratio_with_delta_over_without(self) -> f64 {
        if self.without_delta_bytes == 0 {
            1.0
        } else {
            self.with_delta_bytes as f64 / self.without_delta_bytes as f64
        }
    }
}

/// Paths printed at the end of demo execution.
#[derive(Debug, Clone)]
struct DemoRunPaths {
    /// Artifact root containing all generated demo outputs.
    artifact_root: PathBuf,
    /// Workspace root used by `MediaPmService`.
    workspace_root: PathBuf,
    /// Manifest file path for quick human inspection.
    manifest_path: PathBuf,
    /// Materialized media library path.
    library_root: PathBuf,
}

/// Returns deterministic artifact root for this persistent demo.
fn artifact_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("examples").join(".artifacts").join("demo")
}

/// Returns current Unix timestamp in seconds.
fn unix_timestamp_seconds() -> u64 {
    SystemTime::now().duration_since(UNIX_EPOCH).map(|duration| duration.as_secs()).unwrap_or(0)
}

/// Converts one filesystem path to a slash-normalized display string.
fn display_path(path: &Path) -> String {
    path.display().to_string().replace('\\', "/")
}

/// Recreates artifact root so every run starts clean.
fn reset_artifact_root() -> ExampleResult<PathBuf> {
    let root = artifact_root();
    if root.exists()
        && let Err(error) = remove_dir_all_with_retry(&root)
    {
        if is_share_violation_remove_error(error.as_ref()) {
            return prepare_fallback_artifact_root(&root);
        }

        return Err(error);
    }
    fs::create_dir_all(&root)?;
    Ok(root)
}

/// Returns true when one cleanup error matches transient Windows lock failures.
fn is_share_violation_remove_error(error: &(dyn Error + 'static)) -> bool {
    error.downcast_ref::<std::io::Error>().is_some_and(|io_error| {
        io_error.kind() == std::io::ErrorKind::PermissionDenied
            || io_error.raw_os_error() == Some(32)
    })
}

/// Creates one unique fallback artifact root when canonical cleanup is locked.
fn prepare_fallback_artifact_root(canonical_root: &Path) -> ExampleResult<PathBuf> {
    let suffix = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_nanos())
        .unwrap_or(0);
    let fallback_root =
        canonical_root.with_file_name(format!("demo-fallback-{}-{suffix}", process::id()));

    fs::create_dir_all(&fallback_root)?;
    eprintln!(
        "[demo] canonical artifact root '{}' is locked; using fallback root '{}'",
        canonical_root.display(),
        fallback_root.display()
    );
    Ok(fallback_root)
}

/// Removes one directory with short retry policy for Windows locking behavior.
fn remove_dir_all_with_retry(path: &Path) -> ExampleResult<()> {
    const ATTEMPTS: usize = 6;
    const BACKOFF_MS: u64 = 40;

    let mut last_error: Option<std::io::Error> = None;
    for attempt in 0..ATTEMPTS {
        match fs::remove_dir_all(path) {
            Ok(()) => return Ok(()),
            Err(error) => {
                let retryable = error.kind() == std::io::ErrorKind::PermissionDenied
                    || error.raw_os_error() == Some(32);
                if !retryable || attempt + 1 == ATTEMPTS {
                    last_error = Some(error);
                    break;
                }
                clear_readonly_bits_recursively(path);
                thread::sleep(Duration::from_millis(BACKOFF_MS));
                last_error = Some(error);
            }
        }
    }

    match last_error {
        Some(error) => Err(Box::new(error)),
        None => Ok(()),
    }
}

/// Best-effort recursive readonly-bit clearing for Windows cleanup retries.
///
/// Managed demo outputs are marked read-only after sync commit. Clearing those
/// flags before retrying `remove_dir_all` keeps repeated example runs and test
/// execution deterministic on Windows hosts.
#[cfg_attr(
    windows,
    expect(
        clippy::permissions_set_readonly_false,
        reason = "Windows demo cleanup retries must clear readonly flags on managed artifacts before recursive removal"
    )
)]
fn clear_readonly_bits_recursively(path: &Path) {
    #[cfg(not(windows))]
    {
        let _ = path;
        return;
    }

    #[cfg(windows)]
    {
        if !path.exists() {
            return;
        }

        let mut stack = vec![path.to_path_buf()];
        while let Some(next) = stack.pop() {
            if let Ok(metadata) = fs::metadata(&next) {
                let mut permissions = metadata.permissions();
                if permissions.readonly() {
                    permissions.set_readonly(false);
                    let _ = fs::set_permissions(&next, permissions);
                }
            }

            if next.is_dir()
                && let Ok(entries) = fs::read_dir(&next)
            {
                for entry in entries.flatten() {
                    stack.push(entry.path());
                }
            }
        }
    }
}

/// Writes one serializable value as pretty JSON.
fn write_json_file<T>(path: &Path, value: &T) -> ExampleResult<()>
where
    T: Serialize,
{
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, serde_json::to_vec_pretty(value)?)?;
    Ok(())
}

/// Returns whether one path segment is a hexadecimal fragment.
#[must_use]
fn is_hex_segment(value: &str) -> bool {
    !value.is_empty() && value.bytes().all(|byte| byte.is_ascii_hexdigit())
}

/// Parses one filesystem CAS object path into a canonical hash when possible.
fn parse_hash_from_store_object_path(objects_root: &Path, path: &Path) -> Option<Hash> {
    let relative = path.strip_prefix(objects_root).ok()?;
    let mut components = relative.iter();
    let algorithm = components.next()?.to_string_lossy().to_string();
    if algorithm.is_empty() {
        return None;
    }

    let mut hex = String::new();
    for component in components {
        let segment = component.to_string_lossy();
        let segment = segment.strip_suffix(".diff").unwrap_or(segment.as_ref());
        if !is_hex_segment(segment) {
            return None;
        }
        hex.push_str(segment);
    }

    if hex.len() != 64 {
        return None;
    }

    Hash::from_str(&format!("{algorithm}:{hex}")).ok()
}

/// Recursively visits one CAS object directory and records discovered hashes.
fn collect_store_object_hashes_recursive(
    objects_root: &Path,
    current_dir: &Path,
    hashes: &mut BTreeSet<Hash>,
) -> ExampleResult<()> {
    for entry in fs::read_dir(current_dir)? {
        let entry = entry?;
        let path = entry.path();
        if entry.file_type()?.is_dir() {
            collect_store_object_hashes_recursive(objects_root, &path, hashes)?;
            continue;
        }

        if !entry.file_type()?.is_file() {
            continue;
        }

        if let Some(hash) = parse_hash_from_store_object_path(objects_root, &path) {
            let _ = hashes.insert(hash);
        }
    }

    Ok(())
}

/// Collects all persisted object hashes currently present in one CAS root.
fn collect_store_object_hashes(cas_root: &Path) -> ExampleResult<BTreeSet<Hash>> {
    let mut hashes = BTreeSet::new();
    let objects_root = cas_root.join("v1");
    if !objects_root.exists() {
        return Ok(hashes);
    }

    collect_store_object_hashes_recursive(&objects_root, &objects_root, &mut hashes)?;

    Ok(hashes)
}

/// Resolves canonical CAS object file path for one content hash.
fn cas_object_path_for_hash(cas_root: &Path, hash: Hash) -> PathBuf {
    let hex = hash.to_hex();
    let algorithm = hash.algorithm_name();
    cas_root.join("v1").join(algorithm).join(&hex[..2]).join(&hex[2..4]).join(&hex[4..])
}

/// Returns lockfile-relative managed path for one materialized output file.
fn managed_relative_path(hierarchy_root: &Path, output_path: &Path) -> ExampleResult<String> {
    let relative = output_path.strip_prefix(hierarchy_root).map_err(|error| {
        std::io::Error::other(format!(
            "materialized path '{}' is outside hierarchy root '{}': {error}",
            output_path.display(),
            hierarchy_root.display()
        ))
    })?;

    Ok(relative.to_string_lossy().replace('\\', "/"))
}

/// Returns whether one materialized file is hardlinked to one CAS object.
fn output_is_hardlinked_to_cas_object(
    cas_root: &Path,
    hash: Hash,
    output_path: &Path,
) -> ExampleResult<bool> {
    let source_path = cas_object_path_for_hash(cas_root, hash);
    if !source_path.is_file() || !output_path.is_file() {
        return Ok(false);
    }

    Ok(is_same_file(&source_path, output_path)?
        && fs::read(&source_path)? == fs::read(output_path)?)
}

/// Validates one materialized output file is hardlinked to its CAS object hash.
fn assert_materialized_output_hardlinked_to_cas(
    cas_root: &Path,
    hierarchy_root: &Path,
    lock: &mediapm::MediaLockFile,
    output_path: &Path,
) -> ExampleResult<bool> {
    let relative_path = managed_relative_path(hierarchy_root, output_path)?;
    let record = lock.managed_files.get(relative_path.as_str()).ok_or_else(|| {
        std::io::Error::other(format!(
            "managed output '{relative_path}' missing from lockfile tracking"
        ))
    })?;
    let hash = Hash::from_str(record.hash.as_str()).map_err(|error| {
        std::io::Error::other(format!(
            "managed output '{}' has invalid CAS hash '{}': {error}",
            relative_path, record.hash
        ))
    })?;

    if !output_is_hardlinked_to_cas_object(cas_root, hash, output_path)? {
        return Err(std::io::Error::other(format!(
            "materialized output '{}' is not hardlinked to CAS object '{}'",
            output_path.display(),
            record.hash
        ))
        .into());
    }

    Ok(true)
}

/// Computes logical and effective store-size totals from all persisted objects.
async fn summarize_store_sizes(cas_root: &Path) -> ExampleResult<StoreSizeStats> {
    let cas = FileSystemCas::open(cas_root).await?;
    let mut without_delta = 0u64;
    let mut with_delta = 0u64;

    for hash in collect_store_object_hashes(cas_root)? {
        let info = cas.info(hash).await?;
        without_delta = without_delta.saturating_add(info.content_len);
        with_delta = with_delta.saturating_add(info.payload_len);
    }

    Ok(StoreSizeStats { without_delta_bytes: without_delta, with_delta_bytes: with_delta })
}

/// Writes one local MP4 fixture file from the embedded binary bytes.
fn write_local_av_fixture(path: &Path) -> ExampleResult<Vec<u8>> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    fs::write(path, SAMPLE_AV_MP4_BYTES)?;
    Ok(SAMPLE_AV_MP4_BYTES.to_vec())
}

/// Writes one local metadata JSON fixture used by metadata variant bindings.
fn write_local_metadata_fixture(path: &Path) -> ExampleResult<Vec<u8>> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    let payload = serde_json::to_vec_pretty(&json!({
        "title": DEMO_METADATA_TITLE,
        "artist": DEMO_METADATA_ARTIST,
        "id": DEMO_METADATA_VIDEO_ID,
        "source": DEMO_METADATA_SOURCE_LITERAL,
        "video_ext": "mp4",
        "tagged_ext": "m4a",
    }))?;
    fs::write(path, &payload)?;
    Ok(payload)
}

/// Returns true when one byte payload contains one ASCII marker sequence.
fn bytes_contain_ascii(bytes: &[u8], marker: &[u8]) -> bool {
    bytes.windows(marker.len()).any(|window| window == marker)
}

/// Parses optional env-var text into a sync-enabled flag.
///
/// Empty/missing values default to `true` so direct `cargo run --example demo`
/// remains a full end-to-end execution.
fn sync_enabled_from_env_value(value: Option<&str>) -> bool {
    let Some(raw) = value else {
        return true;
    };

    let normalized = raw.trim().to_ascii_lowercase();
    !matches!(normalized.as_str(), "0" | "false" | "no" | "off")
}

/// Returns whether this example binary was compiled as a Cargo test target.
#[must_use]
fn running_as_test_binary() -> bool {
    cfg!(test)
}

/// Resolves sync execution mode from `MEDIAPM_DEMO_RUN_SYNC`.
fn demo_run_sync_enabled() -> bool {
    let override_value = std::env::var(DEMO_RUN_SYNC_ENV_VAR).ok();
    if override_value.is_some() {
        return sync_enabled_from_env_value(override_value.as_deref());
    }

    !running_as_test_binary()
}

/// Imports one source payload into the runtime CAS store and returns its hash.
async fn import_source_fixture_into_cas(
    cas: &FileSystemCas,
    source_bytes: &[u8],
) -> ExampleResult<Hash> {
    let hash = cas.put(source_bytes.to_vec()).await?;
    Ok(hash)
}

/// Builds one demo `mediapm.ncl` document that demonstrates a local ingest
/// pipeline (`import -> ffmpeg -> media-tagger -> rsgain`).
#[expect(
    clippy::too_many_lines,
    reason = "this item intentionally keeps end-to-end control flow together so ordering invariants remain explicit during maintenance"
)]
fn configure_document_for_local_tool_chain(
    workspace_root: &Path,
    source_hash: &str,
    metadata_hash: &str,
) -> ExampleResult<(usize, usize)> {
    let mediapm_ncl = workspace_root.join("mediapm.ncl");
    let mut document = load_mediapm_document(&mediapm_ncl)?;

    document.tools = BTreeMap::from([
        (
            "import".to_string(),
            ToolRequirement {
                version: None,
                tag: None,
                dependencies: ToolRequirementDependencies::default(),
                recheck_seconds: None,
                max_input_slots: None,
                max_output_slots: None,
            },
        ),
        (
            "ffmpeg".to_string(),
            ToolRequirement {
                version: None,
                tag: Some("latest".to_string()),
                dependencies: ToolRequirementDependencies::default(),
                recheck_seconds: None,
                max_input_slots: None,
                max_output_slots: None,
            },
        ),
        (
            "rsgain".to_string(),
            ToolRequirement {
                version: None,
                tag: Some("latest".to_string()),
                dependencies: ToolRequirementDependencies {
                    ffmpeg_version: Some("inherit".to_string()),
                    sd_version: Some("inherit".to_string()),
                },
                recheck_seconds: None,
                max_input_slots: None,
                max_output_slots: None,
            },
        ),
        (
            "sd".to_string(),
            ToolRequirement {
                version: None,
                tag: Some("latest".to_string()),
                dependencies: ToolRequirementDependencies::default(),
                recheck_seconds: None,
                max_input_slots: None,
                max_output_slots: None,
            },
        ),
        (
            "media-tagger".to_string(),
            ToolRequirement {
                version: None,
                tag: Some("latest".to_string()),
                dependencies: ToolRequirementDependencies {
                    ffmpeg_version: Some("inherit".to_string()),
                    sd_version: None,
                },
                recheck_seconds: None,
                max_input_slots: None,
                max_output_slots: None,
            },
        ),
    ]);

    let steps = vec![
        MediaStep {
            tool: MediaStepTool::Import,
            input_variants: Vec::new(),
            output_variants: BTreeMap::from([("video".to_string(), json!({ "kind": "result" }))]),
            options: BTreeMap::from([
                ("kind".to_string(), TransformInputValue::String(IMPORT_KIND_CAS_HASH.to_string())),
                ("hash".to_string(), TransformInputValue::String(source_hash.to_string())),
            ]),
        },
        MediaStep {
            tool: MediaStepTool::Ffmpeg,
            input_variants: vec!["video".to_string()],
            output_variants: BTreeMap::from([(
                "audio_m4a".to_string(),
                json!({ "kind": "primary", "idx": 0, "extension": "m4a" }),
            )]),
            options: BTreeMap::from([
                ("container".to_string(), TransformInputValue::String("mp4".to_string())),
                ("vn".to_string(), TransformInputValue::String("true".to_string())),
                ("codec_copy".to_string(), TransformInputValue::String("true".to_string())),
                ("map_metadata".to_string(), TransformInputValue::String("0".to_string())),
            ]),
        },
        MediaStep {
            tool: MediaStepTool::MediaTagger,
            input_variants: vec!["audio_m4a".to_string()],
            output_variants: BTreeMap::from([(
                "audio_tagged".to_string(),
                json!({ "kind": "primary" }),
            )]),
            options: BTreeMap::from([
                (
                    "recording_mbid".to_string(),
                    TransformInputValue::String("8f3471b5-7e6a-48da-86a9-c1c07a0f47ae".to_string()),
                ),
                ("write_all_images".to_string(), TransformInputValue::String("false".to_string())),
            ]),
        },
        MediaStep {
            tool: MediaStepTool::Rsgain,
            input_variants: vec!["audio_tagged".to_string()],
            output_variants: BTreeMap::from([("tagged".to_string(), json!({ "kind": "primary" }))]),
            options: BTreeMap::new(),
        },
    ];

    let configured_step_count = steps.len();

    document.media = BTreeMap::from([(
        DEMO_MEDIA_ID.to_string(),
        MediaSourceSpec {
            id: None,
            description: Some(
                "Local demo pipeline exercising import, ffmpeg, rsgain, and media-tagger"
                    .to_string(),
            ),
            title: Some(DEMO_METADATA_TITLE.to_string()),
            workflow_id: None,
            metadata: Some(BTreeMap::from([
                (
                    "title".to_string(),
                    MediaMetadataValue::Variant(MediaMetadataVariantBinding {
                        variant: DEMO_METADATA_VARIANT.to_string(),
                        metadata_key: DEMO_METADATA_TITLE_KEY.to_string(),
                        transform: None,
                    }),
                ),
                (
                    "artist".to_string(),
                    MediaMetadataValue::Variant(MediaMetadataVariantBinding {
                        variant: DEMO_METADATA_VARIANT.to_string(),
                        metadata_key: DEMO_METADATA_ARTIST_KEY.to_string(),
                        transform: None,
                    }),
                ),
                (
                    "video_id".to_string(),
                    MediaMetadataValue::Variant(MediaMetadataVariantBinding {
                        variant: DEMO_METADATA_VARIANT.to_string(),
                        metadata_key: DEMO_METADATA_VIDEO_ID_KEY.to_string(),
                        transform: None,
                    }),
                ),
                (
                    "source".to_string(),
                    MediaMetadataValue::Literal(DEMO_METADATA_SOURCE_LITERAL.to_string()),
                ),
                (
                    "video_ext".to_string(),
                    MediaMetadataValue::Variant(MediaMetadataVariantBinding {
                        variant: DEMO_METADATA_VARIANT.to_string(),
                        metadata_key: "video_ext".to_string(),
                        transform: Some(MediaMetadataRegexTransform {
                            pattern: "(.+)".to_string(),
                            replacement: ".$0".to_string(),
                        }),
                    }),
                ),
                (
                    "tagged_ext".to_string(),
                    MediaMetadataValue::Variant(MediaMetadataVariantBinding {
                        variant: DEMO_METADATA_VARIANT.to_string(),
                        metadata_key: "tagged_ext".to_string(),
                        transform: Some(MediaMetadataRegexTransform {
                            pattern: "(.+)".to_string(),
                            replacement: ".$0".to_string(),
                        }),
                    }),
                ),
            ])),
            variant_hashes: BTreeMap::from([(
                DEMO_METADATA_VARIANT.to_string(),
                metadata_hash.to_string(),
            )]),
            steps,
        },
    )]);

    let media_hierarchy_children = vec![HierarchyNode {
        path: DEMO_MEDIA_FOLDER_TEMPLATE.to_string(),
        kind: HierarchyNodeKind::Folder,
        id: None,
        media_id: None,
        variant: None,
        variants: Vec::new(),
        rename_files: Vec::new(),
        format: PlaylistFormat::M3u8,
        ids: Vec::new(),
        children: vec![
            HierarchyNode {
                path: "${media.metadata.artist} - ${media.metadata.title} [${media.id}].untagged${media.metadata.video_ext}".to_string(),
                kind: HierarchyNodeKind::Media,
                id: None,
                media_id: Some(DEMO_MEDIA_ID.to_string()),
                variant: Some("video".to_string()),
                variants: Vec::new(),
                rename_files: Vec::new(),
                format: PlaylistFormat::M3u8,
                ids: Vec::new(),
                children: Vec::new(),
            },
            HierarchyNode {
                path: "${media.metadata.artist} - ${media.metadata.title} [${media.id}]${media.metadata.tagged_ext}".to_string(),
                kind: HierarchyNodeKind::Media,
                id: Some(DEMO_PLAYLIST_TARGET_HIERARCHY_ID.to_string()),
                media_id: Some(DEMO_MEDIA_ID.to_string()),
                variant: Some("tagged".to_string()),
                variants: Vec::new(),
                rename_files: Vec::new(),
                format: PlaylistFormat::M3u8,
                ids: Vec::new(),
                children: Vec::new(),
            },
        ],
    }];

    document.hierarchy = vec![
        HierarchyNode {
            path: DEMO_LIBRARY_ROOT.to_string(),
            kind: HierarchyNodeKind::Folder,
            id: None,
            media_id: None,
            variant: None,
            variants: Vec::new(),
            rename_files: Vec::new(),
            format: PlaylistFormat::M3u8,
            ids: Vec::new(),
            children: media_hierarchy_children,
        },
        HierarchyNode {
            path: "playlists".to_string(),
            kind: HierarchyNodeKind::Folder,
            id: None,
            media_id: None,
            variant: None,
            variants: Vec::new(),
            rename_files: Vec::new(),
            format: PlaylistFormat::M3u8,
            ids: Vec::new(),
            children: vec![HierarchyNode {
                path: "local-demo.m3u8".to_string(),
                kind: HierarchyNodeKind::Playlist,
                id: None,
                media_id: None,
                variant: None,
                variants: Vec::new(),
                rename_files: Vec::new(),
                format: PlaylistFormat::M3u8,
                ids: vec![
                    PlaylistItemRef {
                        id: DEMO_PLAYLIST_TARGET_HIERARCHY_ID.to_string(),
                        path: PlaylistEntryPathMode::Relative,
                    },
                    PlaylistItemRef {
                        id: DEMO_PLAYLIST_TARGET_HIERARCHY_ID.to_string(),
                        path: PlaylistEntryPathMode::Absolute,
                    },
                ],
                children: Vec::new(),
            }],
        },
    ];

    // Expose all runtime-storage fields with explicit default values so the
    // written mediapm.ncl documents every runtime knob by default.
    document.runtime = MediaRuntimeStorage {
        // Runtime root for all managed state files.
        // Default: `.mediapm/` relative to the workspace root.
        mediapm_dir: Some(".mediapm".to_string()),
        // Materialized hierarchy root directory.
        // Default: workspace root containing `mediapm.ncl`.
        hierarchy_root_dir: Some(".".to_string()),
        // Staging directory relative to `runtime.mediapm_dir`.
        // Default: `<mediapm_dir>/tmp/`.
        mediapm_tmp_dir: Some("tmp".to_string()),
        // Ordered file-materialization method preference.
        // Default when omitted: hardlink -> symlink -> reflink -> copy.
        materialization_preference_order: Some(DEMO_MATERIALIZATION_PREFERENCE_ORDER.to_vec()),
        // User-owned conductor config path relative to workspace root.
        // Default: `mediapm.conductor.ncl`.
        conductor_config: Some("mediapm.conductor.ncl".to_string()),
        // Machine-managed conductor config path relative to workspace root.
        // Default: `mediapm.conductor.machine.ncl`.
        conductor_machine_config: Some("mediapm.conductor.machine.ncl".to_string()),
        // Volatile conductor state path relative to workspace root.
        // Default: `.mediapm/state.conductor.ncl`.
        conductor_state_config: Some(".mediapm/state.conductor.ncl".to_string()),
        // Conductor execution tmp path relative to workspace root.
        // Default: `runtime.mediapm_tmp_dir`.
        conductor_tmp_dir: Some(".mediapm/tmp".to_string()),
        // Conductor schema export directory relative to workspace root.
        // Default: `<mediapm_dir>/config/conductor`.
        conductor_schema_dir: Some(".mediapm/config/conductor".to_string()),
        // Explicit host default inherited env-var map.
        // Runtime still merges this map case-insensitively with host defaults.
        inherited_env_vars: Some(default_runtime_inherited_env_vars_for_host()),
        // Machine-managed mediapm state path relative to workspace root.
        // Default: `.mediapm/state.ncl`.
        media_state_config: Some(".mediapm/state.ncl".to_string()),
        // Dotenv credential source path relative to workspace root.
        // Default: `.mediapm/.env`.
        env_file: Some(".mediapm/.env".to_string()),
        // Embedded schema export directory policy.
        // `Some(Some(path))` keeps export enabled with an explicit default path.
        mediapm_schema_dir: Some(Some(".mediapm/config/mediapm".to_string())),
        // Enable global user tool cache to reuse downloaded tool binaries
        // across runs without re-downloading from the network.
        // Default when omitted: true.
        use_user_tool_cache: Some(true),
    };

    save_mediapm_document(&mediapm_ncl, &document)?;
    Ok((document.tools.len(), configured_step_count))
}

/// Runs the persistent demo and returns generated paths.
///
/// `run_sync = true` executes full tool reconciliation + workflow execution.
/// `run_sync = false` writes a complete showcase configuration and manifest
/// without external network/tool download requirements (used by automated
/// tests that still need to execute the real example entrypoint).
#[expect(
    clippy::too_many_lines,
    reason = "this demo keeps end-to-end orchestration and manifest wiring in one place for maintainability"
)]
async fn generate_demo_artifacts(run_sync: bool) -> ExampleResult<DemoRunPaths> {
    let root = reset_artifact_root()?;
    let workspace_root = root.clone();

    let source_path = workspace_root.join("input").join("sample-av.mp4");
    let source_bytes = write_local_av_fixture(&source_path)?;
    let metadata_path = workspace_root.join("input").join("sample-av.info.json");
    let metadata_bytes = write_local_metadata_fixture(&metadata_path)?;
    let source_has_video_track_marker = bytes_contain_ascii(&source_bytes, b"vide");
    let source_has_audio_track_marker = bytes_contain_ascii(&source_bytes, b"soun");

    let ingest_service = MediaPmService::new_in_memory_at(&workspace_root);
    let paths = ingest_service.paths().clone();
    let cas = FileSystemCas::open(paths.runtime_root.join("store")).await?;

    let source_hash = import_source_fixture_into_cas(&cas, &source_bytes).await?;
    let source_hash_text = source_hash.to_string();
    let metadata_hash = import_source_fixture_into_cas(&cas, &metadata_bytes).await?;
    let metadata_hash_text = metadata_hash.to_string();

    let auto_added_media_id = ingest_service.add_local_source(&source_path).await?;
    let auto_added_document = load_mediapm_document(&paths.mediapm_ncl)?;
    let auto_added_source = auto_added_document.media.get(&auto_added_media_id).ok_or_else(|| {
        std::io::Error::other(format!(
            "demo preflight add_local_source media '{auto_added_media_id}' missing from mediapm.ncl"
        ))
    })?;
    let auto_added_source_title =
        auto_added_source.title.clone().filter(|value| !value.trim().is_empty()).ok_or_else(
            || std::io::Error::other("demo preflight add_local_source produced empty title"),
        )?;
    let auto_added_source_description =
        auto_added_source.description.clone().filter(|value| !value.trim().is_empty()).ok_or_else(
            || std::io::Error::other("demo preflight add_local_source produced empty description"),
        )?;

    let (configured_tool_count, configured_step_count) = configure_document_for_local_tool_chain(
        &workspace_root,
        &source_hash_text,
        &metadata_hash_text,
    )?;

    let service = MediaPmService::new(SimpleConductor::new(cas), paths);

    // Auto-enable conductor profiling to the artifact root so every sync run
    // produces a per-step timing profile for latency investigation.
    // Users can override by setting MEDIAPM_CONDUCTOR_PROFILE_JSON before running.
    let profile_path = root.join("profile.json");
    if std::env::var_os(mediapm_conductor::ENV_PROFILE_OUTPUT_PATH).is_none() {
        // SAFETY: set before tokio workers are spawned; written once and
        // not mutated during the concurrent sync execution.
        unsafe {
            std::env::set_var(mediapm_conductor::ENV_PROFILE_OUTPUT_PATH, &profile_path);
        }
    }

    let maybe_summary = if run_sync { Some(service.sync_library().await?) } else { None };
    let cas_root = service.paths().runtime_root.join("store");
    let store_size_stats = summarize_store_sizes(&cas_root).await?;
    let materialization_preference_order = DEMO_MATERIALIZATION_PREFERENCE_ORDER
        .iter()
        .map(|method| method.as_label().to_string())
        .collect::<Vec<_>>();

    let materialized_primary = service
        .paths()
        .hierarchy_root_dir
        .join("music videos")
        .join(format!("{DEMO_METADATA_ARTIST} - {DEMO_METADATA_TITLE} [{DEMO_MEDIA_ID}]"))
        .join(format!("{DEMO_METADATA_ARTIST} - {DEMO_METADATA_TITLE} [{DEMO_MEDIA_ID}].m4a"));
    let materialized_secondary = service
        .paths()
        .hierarchy_root_dir
        .join("music videos")
        .join(format!("{DEMO_METADATA_ARTIST} - {DEMO_METADATA_TITLE} [{DEMO_MEDIA_ID}]"))
        .join(format!(
            "{DEMO_METADATA_ARTIST} - {DEMO_METADATA_TITLE} [{DEMO_MEDIA_ID}].untagged.mp4"
        ));

    let lock = load_lockfile(&service.paths().mediapm_state_ncl)?;
    let (materialized_primary_hardlinked_to_cas, materialized_secondary_hardlinked_to_cas) =
        if maybe_summary.is_some() {
            let hierarchy_root = &service.paths().hierarchy_root_dir;
            (
                assert_materialized_output_hardlinked_to_cas(
                    &cas_root,
                    hierarchy_root,
                    &lock,
                    &materialized_primary,
                )?,
                assert_materialized_output_hardlinked_to_cas(
                    &cas_root,
                    hierarchy_root,
                    &lock,
                    &materialized_secondary,
                )?,
            )
        } else {
            (false, false)
        };

    let manifest = DemoManifest {
        generated_unix_epoch_seconds: unix_timestamp_seconds(),
        artifact_root: display_path(&root),
        workspace_root: display_path(&workspace_root),
        media_id: DEMO_MEDIA_ID.to_string(),
        auto_added_media_id,
        auto_added_source_title,
        auto_added_source_description,
        source_file_path: display_path(&source_path),
        source_hash: source_hash_text,
        source_has_video_track_marker,
        source_has_audio_track_marker,
        configured_tool_count,
        configured_step_count,
        materialization_preference_order,
        materialized_primary_path: display_path(&materialized_primary),
        materialized_secondary_path: display_path(&materialized_secondary),
        materialized_primary_exists: materialized_primary.exists(),
        materialized_secondary_exists: materialized_secondary.exists(),
        materialized_primary_hardlinked_to_cas,
        materialized_secondary_hardlinked_to_cas,
        sync_executed: maybe_summary.is_some(),
        lock_managed_files_count: lock.managed_files.len(),
        lock_tool_registry_count: lock.tool_registry.len(),
        executed_instances: maybe_summary.as_ref().map_or(0, |summary| summary.executed_instances),
        cached_instances: maybe_summary.as_ref().map_or(0, |summary| summary.cached_instances),
        rematerialized_instances: maybe_summary
            .as_ref()
            .map_or(0, |summary| summary.rematerialized_instances),
        materialized_paths: maybe_summary.as_ref().map_or(0, |summary| summary.materialized_paths),
        removed_paths: maybe_summary.as_ref().map_or(0, |summary| summary.removed_paths),
        warning_count: maybe_summary.as_ref().map_or(0, |summary| summary.warnings.len()),
        profile_path: display_path(&profile_path),
        mediapm_ncl_path: display_path(&service.paths().mediapm_ncl),
        conductor_user_ncl_path: display_path(&service.paths().conductor_user_ncl),
        conductor_machine_ncl_path: display_path(&service.paths().conductor_machine_ncl),
        mediapm_state_ncl_path: display_path(&service.paths().mediapm_state_ncl),
        library_root_path: display_path(&service.paths().hierarchy_root_dir),
        store_size_without_delta_bytes: store_size_stats.without_delta_bytes,
        store_size_with_delta_bytes: store_size_stats.with_delta_bytes,
        store_size_ratio_with_delta_over_without: store_size_stats.ratio_with_delta_over_without(),
    };

    let manifest_path = root.join("manifest.json");
    write_json_file(&manifest_path, &manifest)?;

    Ok(DemoRunPaths {
        artifact_root: root,
        workspace_root,
        manifest_path,
        library_root: service.paths().hierarchy_root_dir.clone(),
    })
}

#[tokio::main]
/// Runs the persistent demo and prints generated artifact paths.
async fn main() -> ExampleResult<()> {
    let run_sync = demo_run_sync_enabled();
    let paths = generate_demo_artifacts(run_sync).await?;
    println!("generated artifacts root: {}", paths.artifact_root.display());
    println!("generated workspace root: {}", paths.workspace_root.display());
    println!("generated library root: {}", paths.library_root.display());
    println!("manifest: {}", paths.manifest_path.display());
    println!("sync executed: {run_sync}");
    Ok(())
}

#[cfg(test)]
mod tests {
    /// Verifies demo artifact generation writes one complete import
    /// workflow manifest when runtime sync is intentionally skipped.
    #[tokio::test]
    async fn generate_demo_artifacts_writes_manifest_and_import_metadata() {
        let run = super::generate_demo_artifacts(false).await.expect("demo artifact generation");

        assert!(run.manifest_path.exists(), "manifest should be written");
        assert!(run.workspace_root.exists(), "workspace root should exist");

        let manifest_text = std::fs::read_to_string(&run.manifest_path).expect("read manifest");
        let manifest_json: serde_json::Value =
            serde_json::from_str(&manifest_text).expect("manifest JSON");

        assert_eq!(
            manifest_json.get("configured_tool_count").and_then(serde_json::Value::as_u64),
            Some(5),
            "demo should configure five managed tools including import"
        );
        assert_eq!(
            manifest_json.get("configured_step_count").and_then(serde_json::Value::as_u64),
            Some(4),
            "demo should configure four workflow steps including import"
        );
        let without_delta = manifest_json
            .get("store_size_without_delta_bytes")
            .and_then(serde_json::Value::as_u64)
            .expect("manifest should include store_size_without_delta_bytes");
        let with_delta = manifest_json
            .get("store_size_with_delta_bytes")
            .and_then(serde_json::Value::as_u64)
            .expect("manifest should include store_size_with_delta_bytes");
        let ratio = manifest_json
            .get("store_size_ratio_with_delta_over_without")
            .and_then(serde_json::Value::as_f64)
            .expect("manifest should include store_size_ratio_with_delta_over_without");
        let expected_ratio =
            if without_delta == 0 { 1.0 } else { with_delta as f64 / without_delta as f64 };
        assert!(
            (ratio - expected_ratio).abs() <= f64::EPSILON,
            "manifest ratio should match with/without store-size math"
        );
        assert_eq!(
            manifest_json.get("source_has_video_track_marker").and_then(serde_json::Value::as_bool),
            Some(true),
            "source fixture should expose a video marker"
        );
        assert_eq!(
            manifest_json.get("source_has_audio_track_marker").and_then(serde_json::Value::as_bool),
            Some(true),
            "source fixture should expose an audio marker"
        );
        assert!(
            manifest_json
                .get("source_hash")
                .and_then(serde_json::Value::as_str)
                .is_some_and(|hash| hash.starts_with("blake3:")),
            "manifest should record a blake3-prefixed CAS hash"
        );
        assert_eq!(
            manifest_json
                .get("materialization_preference_order")
                .and_then(serde_json::Value::as_array)
                .map(|value| {
                    value.iter().filter_map(serde_json::Value::as_str).collect::<Vec<_>>()
                }),
            Some(vec!["hardlink", "symlink", "reflink", "copy"]),
            "manifest should expose explicit default materialization order"
        );
        assert!(
            manifest_json
                .get("auto_added_source_title")
                .and_then(serde_json::Value::as_str)
                .is_some_and(|value| !value.trim().is_empty()),
            "manifest should record non-empty auto-populated title"
        );
        assert!(
            manifest_json
                .get("auto_added_source_description")
                .and_then(serde_json::Value::as_str)
                .is_some_and(|value| !value.trim().is_empty()),
            "manifest should record non-empty auto-populated description"
        );

        let demo_config_path = run.workspace_root.join("mediapm.ncl");
        let demo_config =
            std::fs::read_to_string(&demo_config_path).expect("read generated mediapm.ncl");

        assert!(
            demo_config.contains("tool = \"import\""),
            "demo should ingest source data via import"
        );
        assert!(
            !demo_config.contains("tool = \"yt-dlp\""),
            "demo should not route local sample ingest through yt-dlp"
        );
        assert!(
            demo_config.contains("codec_copy = \"true\""),
            "demo ffmpeg step should keep stream-copy enabled for fast local runs"
        );
        assert!(
            demo_config.contains("materialization_preference_order")
                && demo_config.contains("\"hardlink\"")
                && demo_config.contains("\"symlink\"")
                && demo_config.contains("\"reflink\"")
                && demo_config.contains("\"copy\""),
            "demo runtime config should explicitly include default materialization order"
        );
        assert!(
            !demo_config.contains("audio_codec = \"libmp3lame\""),
            "demo ffmpeg step should avoid re-encode-specific codec settings"
        );
        assert!(
            !demo_config.contains("strict_identification"),
            "demo should rely on managed media-tagger input defaults for strict identification"
        );
        assert!(
            demo_config.contains("music videos")
                && demo_config
                    .contains("${media.metadata.artist} - ${media.metadata.title} [${media.id}]")
                && demo_config.contains("${media.id}")
                && demo_config.contains("${media.metadata.video_ext}")
                && demo_config.contains("${media.metadata.tagged_ext}"),
            "demo hierarchy output should use Jellyfin-style media-id layout with metadata-driven extensions"
        );
    }

    /// Ensures artifact root stays stable for docs and scripts.
    #[test]
    fn artifact_root_is_stable() {
        let text = super::display_path(&super::artifact_root());
        assert!(text.ends_with("src/mediapm/examples/.artifacts/demo"));
    }

    /// Verifies sync-mode parser defaults to true and recognizes explicit false
    /// tokens used by automated test execution.
    #[test]
    fn sync_enabled_env_parser_handles_false_tokens() {
        assert!(super::sync_enabled_from_env_value(None));
        assert!(super::sync_enabled_from_env_value(Some("true")));
        assert!(!super::sync_enabled_from_env_value(Some("false")));
        assert!(!super::sync_enabled_from_env_value(Some("OFF")));
        assert!(!super::sync_enabled_from_env_value(Some("0")));
    }

    /// Ensures unset sync mode defaults to config-only when compiled as a
    /// test-target binary.
    #[test]
    fn demo_run_sync_defaults_to_config_only_in_test_binary() {
        let previous = std::env::var(super::DEMO_RUN_SYNC_ENV_VAR).ok();
        // SAFETY: test mutates one process env key in a controlled scope and
        // restores the previous value before exit.
        unsafe {
            std::env::remove_var(super::DEMO_RUN_SYNC_ENV_VAR);
        }

        let enabled = super::demo_run_sync_enabled();

        // SAFETY: restore previous env var value for test isolation.
        unsafe {
            if let Some(value) = previous {
                std::env::set_var(super::DEMO_RUN_SYNC_ENV_VAR, value);
            }
        }

        assert!(!enabled, "test-target demo runs should default to config-only mode");
    }

    /// Ensures cleanup retries can remove readonly-marked demo artifact trees
    /// created by prior sync runs on Windows hosts.
    #[test]
    fn remove_dir_all_with_retry_handles_readonly_tree() {
        let temp = tempfile::tempdir().expect("tempdir");
        let tree_root = temp.path().join("readonly-tree");
        std::fs::create_dir_all(&tree_root).expect("create tree root");

        let nested = tree_root.join("nested").join("tool.bin");
        std::fs::create_dir_all(nested.parent().expect("parent")).expect("create nested parent");
        std::fs::write(&nested, b"demo").expect("write nested file");

        let mut file_permissions = std::fs::metadata(&nested).expect("metadata").permissions();
        file_permissions.set_readonly(true);
        std::fs::set_permissions(&nested, file_permissions).expect("set readonly on file");

        super::clear_readonly_bits_recursively(&tree_root);
        super::remove_dir_all_with_retry(&tree_root).expect("retrying remove should succeed");
        assert!(!tree_root.exists());
    }

    /// Ensures ratio rendering stays neutral for empty/objectless stores.
    #[test]
    fn store_size_ratio_uses_neutral_value_for_zero_denominator() {
        let stats = super::StoreSizeStats { without_delta_bytes: 0, with_delta_bytes: 0 };
        assert_eq!(stats.ratio_with_delta_over_without(), 1.0);
    }
}
