//! Runtime configuration document model.
//!
//! This module provides the simplified conductor configuration surface used by
//! runtime planning and CLI workflows.  Key simplifications relative to the
//! old three-document model:
//!
//! - No `Option` wrappers on config fields where sensible defaults exist;
//!   defaults are centralized in `crate::defaults`.
//! - Per-tool `runtime` (replaces the old separate `tool_configs` map) —
//!   runtime-execution tuning now lives inline on each tool.
//! - No `PlatformInheritedEnvVars` — simplified to a single flat map.
//! - No `fp-library` optics; versioning follows `mediapm-cas` pattern.

use std::collections::BTreeMap;
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

pub mod documents;
pub(crate) use documents::NickelDocument;
pub(crate) mod nickel_io;
pub mod versions;

/// Monotonic timestamp for impure (side-effect) operations.
///
/// Conductor uses this timestamp during execution planning to derive
/// per-tool-call-instance cache keys. The value represents when the step was
/// planned for execution by conductor, not when the step was generated by
/// mediapm workflow synthesis.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct ImpureTimestamp(u64);

impl ImpureTimestamp {
    /// Returns an `ImpureTimestamp` representing the current system time.
    ///
    /// Falls back to `UNIX_EPOCH` when the system clock is set before the
    /// epoch (extremely unlikely in practice).
    #[must_use]
    pub fn now() -> Self {
        let duration = SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default();
        Self(u64::try_from(duration.as_nanos()).unwrap_or(u64::MAX))
    }

    /// Returns the timestamp as Unix nanoseconds since epoch.
    #[must_use]
    pub fn as_unix_nanos(self) -> u128 {
        u128::from(self.0)
    }

    /// Constructs an `ImpureTimestamp` from Unix nanoseconds since epoch.
    #[must_use]
    pub fn from_unix_nanos(nanos: u128) -> Self {
        Self(u64::try_from(nanos).unwrap_or(u64::MAX))
    }
}

/// Optional per-output persistence override.
///
/// Controls whether a workflow step output is saved to CAS, and with what
/// level of detail.  `Bool(true)` saves normally, `Bool(false)` marks the
/// output as unsaved (volatile only), and `Full` requests full-data preference
/// hints during persistence.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OutputPolicy {
    /// Boolean save mode (`false` = unsaved, `true` = saved).
    Bool(bool),
    /// Full-data-preferred save mode.
    Full,
}

impl Default for OutputPolicy {
    fn default() -> Self {
        Self::Bool(true)
    }
}

/// Tool content map entry: relative path → CAS hash or inline content
/// description string.
pub type ToolContentMap = BTreeMap<String, String>;

/// External data entry: CAS hash → description + save mode.
///
/// Describes how a CAS-referenced blob that is NOT part of any tool content
/// map should be retained and persisted.  Entries are declared in config so
/// conductor GC does not prune these hashes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExternalDataEntry {
    /// Human-readable description of this external data.
    pub description: String,
    /// Save policy governing this blob.
    pub save_mode: crate::state::OutputSaveMode,
}

/// Kind of tool input.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ToolInputKind {
    /// Simple key-value string pair.
    #[default]
    String,
    /// File content addressed by CAS hash.
    Content,
    /// Environment variable passthrough.
    Env,
    /// JSON array of strings (e.g., `["--arg1", "--arg2"]`).
    StringList,
}

/// Specification for one tool input.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct ToolInputSpec {
    /// Declared value kind for this input.
    #[serde(default)]
    pub kind: ToolInputKind,
    /// Human-readable description of this input.
    #[serde(default)]
    pub description: String,
    /// Whether this input is required for every tool call.
    #[serde(default)]
    pub required: bool,
}

/// Default for `OutputCaptureSpec.save`: persist to CAS.
const fn default_save_output() -> bool {
    true
}

/// Capture/output spec for a step.
///
/// Describes how output bytes are captured from a tool execution:
/// - `stdout` / `stderr`: capture standard streams,
/// - `process_code`: capture exit code as text,
/// - `file:<path>`: capture bytes from a relative file path,
/// - `file_regex:<pattern>`: capture bytes from a file matching a regex.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OutputCaptureSpec {
    /// Logical output name.
    pub name: String,
    /// Capture source selector (`stdout`, `stderr`, `process_code`, `file:<path>`,
    /// `file_regex:<pattern>`, etc.).
    pub capture: String,
    /// Whether to persist this output to CAS. Defaults to `true`.
    #[serde(default = "default_save_output")]
    pub save: bool,
}

impl Default for OutputCaptureSpec {
    fn default() -> Self {
        Self { name: String::new(), capture: String::new(), save: true }
    }
}

/// Runtime configuration for a tool (replaces the old separate `tool_configs`
/// map in the V1 schema).
///
/// The `runtime` property on a tool holds fields that must NOT be part of the
/// tool-call-instance identity computation.  Changes to runtime fields affect
/// scheduling and sandbox materialization but do not invalidate cached outputs.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ToolRuntime {
    /// Content map: relative path → CAS hash or inline base64 payload.
    ///
    /// Keys ending with `/` designate directory extraction targets (ZIP
    /// payload).  Key `./` unpacks into the sandbox root.  Runtime rejects
    /// conflicts where two entries would write the same file path.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub content_map: ToolContentMap,
    /// Whether this tool performs impure (side-effecting) operations.
    ///
    /// Impure tools receive timestamp injection at planning time which makes
    /// each call unique and prevents cache hits across runs.
    #[serde(default)]
    pub impure: bool,
    /// Environment variables inherited by this tool's process.
    ///
    /// These are merged with runtime-wide inherited env vars and host defaults.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub inherited_env_vars: BTreeMap<String, String>,
    /// Maximum concurrent calls allowed for this tool.
    ///
    /// `0` means unlimited.
    #[serde(default)]
    pub max_concurrent_calls: usize,
    /// Maximum retry attempts for this tool after the first failed attempt.
    #[serde(default)]
    pub max_retries: usize,
}

/// Runtime configuration for the conductor itself (not per-tool).
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ConductorRuntimeConfig {
    /// Whether impure tool calls may be retried automatically.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retry_impure: Option<bool>,
    /// Platform-keyed inherited env var names.
    ///
    /// Maps platform name strings (e.g. "linux", "macos", "windows") to
    /// lists of environment variable *names* to inherit from the host process.
    /// These are resolved at `to_unified()` time against the current platform.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub platform_inherited_env_var_names: BTreeMap<String, Vec<String>>,
}

/// Kind of tool definition.
///
/// Only two kinds: builtin (built into conductor-builtins crates) or
/// executable (an external command).  Whether a tool is downloaded and cached
/// by conductor is orthogonal to its kind — that is controlled by the
/// runtime content map.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum ToolKindSpec {
    /// Built-in tool known to conductor-builtins crates.
    Builtin {
        /// Builtin name.
        name: String,
        /// Builtin semantic version.
        version: String,
    },
    /// External executable command (on PATH or with an absolute path).
    Executable {
        /// Executable command (path or name on PATH).
        command: Vec<String>,
        /// Environment variables for the process.
        #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
        env_vars: BTreeMap<String, String>,
        /// Accepted exit codes (empty = any non-negative).
        #[serde(default)]
        success_codes: Vec<i32>,
    },
}

/// Specification for a tool.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ToolSpec {
    /// Tool kind (builtin, executable).
    pub kind: ToolKindSpec,
    /// Logical tool name.
    pub name: String,
    /// Tool semantic version.
    pub version: String,
    /// Declared input specifications keyed by input name.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub inputs: BTreeMap<String, ToolInputSpec>,
    /// Default input values applied when workflow steps omit matching keys.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub default_inputs: BTreeMap<String, String>,
    /// Declared output specifications for this tool keyed by output name.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub outputs: BTreeMap<String, OutputCaptureSpec>,
    /// Runtime configuration (`content_map`, impure, concurrency, retry, etc.).
    #[serde(default)]
    pub runtime: ToolRuntime,
}

impl ToolSpec {
    /// Returns the fully qualified tool identifier: `name@version`.
    #[must_use]
    pub fn id(&self) -> String {
        format!("{}@{}", self.name, self.version)
    }
}

impl Default for ToolKindSpec {
    fn default() -> Self {
        Self::Executable { command: Vec::new(), env_vars: BTreeMap::new(), success_codes: vec![0] }
    }
}

/// Specification for a complete workflow DAG.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct WorkflowSpec {
    /// Logical workflow name (used for invocation).
    pub name: String,
    /// Human-readable display label.
    #[serde(default)]
    pub display_name: String,
    /// Human-readable workflow description.
    #[serde(default)]
    pub description: String,
    /// Whether this workflow contains impure (side-effecting) steps.
    #[serde(default)]
    pub impure: bool,
    /// Ordered list of workflow steps before topological sorting.
    #[serde(default)]
    pub steps: Vec<WorkflowStepSpec>,
}

/// Specification for one workflow step (tool call reference).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkflowStepSpec {
    /// Unique step identifier within one workflow.
    pub id: String,
    /// Referenced tool name (must match a declared `ToolSpec.name`).
    pub tool: String,
    /// Input values keyed by logical tool-input name.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub inputs: BTreeMap<String, String>,
    /// Per-output persistence policy overrides keyed by output name.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub outputs: BTreeMap<String, OutputCaptureSpec>,
    /// Override the tool's `max_retries` for this specific step.
    #[serde(default)]
    pub max_retries: usize,
    /// Explicit execution-order dependencies on prior step ids.
    ///
    /// Every `${step_output.<step_id>...}` reference in `inputs` must have a
    /// matching `depends_on` entry.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub depends_on: Vec<String>,
}

/// Returns platform-default inherited environment-variable names.
///
/// These names are merged into executable runtime environments before tool
/// environment overrides so callers can keep baseline process invariants
/// without repeating them per tool.
#[must_use]
pub fn default_runtime_inherited_env_vars() -> BTreeMap<String, String> {
    if cfg!(windows) {
        BTreeMap::from([
            ("PATH".to_string(), String::new()),
            ("SYSTEMROOT".to_string(), String::new()),
            ("USERNAME".to_string(), String::new()),
            ("WINDIR".to_string(), String::new()),
            ("TEMP".to_string(), String::new()),
            ("TMP".to_string(), String::new()),
        ])
    } else {
        BTreeMap::from([
            ("HOME".to_string(), String::new()),
            ("PATH".to_string(), String::new()),
            ("TMPDIR".to_string(), String::new()),
            ("USER".to_string(), String::new()),
        ])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verifies `ToolSpec.id()` produces the expected `name@version` format.
    #[test]
    fn tool_spec_id_format() {
        let spec = ToolSpec {
            kind: ToolKindSpec::Builtin { name: "echo".to_string(), version: "1.0.0".to_string() },
            name: "echo".to_string(),
            version: "1.0.0".to_string(),
            inputs: BTreeMap::new(),
            default_inputs: BTreeMap::new(),
            outputs: BTreeMap::new(),
            runtime: ToolRuntime::default(),
        };
        assert_eq!(spec.id(), "echo@1.0.0");
    }

    /// Verifies `ImpureTimestamp` round-trips through Unix nanoseconds.
    #[test]
    fn impure_timestamp_round_trip() {
        let now = ImpureTimestamp::now();
        let nanos = now.as_unix_nanos();
        let restored = ImpureTimestamp::from_unix_nanos(nanos);
        assert_eq!(now, restored);
    }

    /// Verifies default `OutputPolicy` is `Bool(true)`.
    #[test]
    fn output_policy_default_is_saved() {
        let policy = OutputPolicy::default();
        assert_eq!(policy, OutputPolicy::Bool(true));
    }

    /// Verifies default `ToolRuntime` has impure=false and zero retries.
    #[test]
    fn tool_runtime_defaults() {
        let rt = ToolRuntime::default();
        assert!(!rt.impure);
        assert_eq!(rt.max_retries, 0);
        assert!(rt.content_map.is_empty());
    }

    /// Verifies `default_runtime_inherited_env_vars` returns
    /// platform-appropriate inherited env var names.
    #[test]
    fn default_inherited_env_vars_are_platform_appropriate() {
        let vars = default_runtime_inherited_env_vars();
        assert!(!vars.is_empty(), "should have entries on all platforms");
        assert!(vars.contains_key("PATH"), "PATH must be present on all platforms");
        if cfg!(windows) {
            assert!(vars.contains_key("WINDIR"));
            assert!(vars.contains_key("USERNAME"));
        } else {
            assert!(vars.contains_key("HOME"));
            assert!(vars.contains_key("USER"));
            assert!(vars.contains_key("TMPDIR"));
        }
    }
}
