//! Tool provider: three-phase pipeline for resolving, fetching, and postprocessing
//! downloadable tool payloads (and generating launcher scripts for builtins).
//!
//! # Architecture
//!
//! Every tool (external download + launcher-based builtin) goes through three
//! sequential phases:
//!
//! 1. **Resolve** — gather metadata, resolve versions, determine sources.
//! 2. **Fetch** — download or generate bytes for each source.
//! 3. **Postprocess** — extract archives, repack, import to CAS, build content map.
//!
//! The entire module is gated behind the `tool-presets` feature since all types
//! reference progress types from `mediapm-utils` that are behind that gate.

#![cfg(feature = "tool-presets")]

use std::collections::BTreeMap;

use mediapm_utils::progress::ProviderProgressCallback;

// ---------------------------------------------------------------------------
// Archive format constants (private — inferred internally in phase 3)
// ---------------------------------------------------------------------------

const ARCHIVE_BINARY: &str = "binary";
const ARCHIVE_ZIP: &str = "zip";
const ARCHIVE_TAR_GZ: &str = "tar.gz";
const ARCHIVE_TAR_XZ: &str = "tar.xz";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// User-facing version specifier. Consumed in phase 1 (resolve), discarded
/// after concrete sources are determined.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum VersionSpec {
    /// Fetch the latest stable release.
    Latest,
    /// Resolve from a specific git commit hash.
    GitHash(String),
    /// Resolve from a specific git tag.
    GitTag(String),
    /// Resolve from a specific version string.
    Version(String),
}

/// How phase 2 produces bytes for one source.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SourceProducer {
    /// Fetch bytes from URL candidates (tried in order).
    Fetch { urls: Vec<String> },
    /// Generate launcher script bytes that dispatch a builtin tool.
    GenerateLauncher { builtin_id: String },
}

/// One resolved source after phase 1.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedSource {
    /// OS target label (e.g. `"linux"`, `"macos"`, `"windows"`).
    pub os: String,
    /// How phase 2 produces bytes for this source.
    pub producer: SourceProducer,
    /// Expected byte size, if known from HEAD probes.
    pub expected_size: Option<u64>,
}

/// Phase 1 output: everything needed for phase 2.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResolvedToolFetch {
    /// Logical tool identifier.
    pub tool_id: String,
    /// Per-platform source descriptors.
    pub sources: Vec<ResolvedSource>,
    /// Total number of items for progress tracking.
    pub total_items: u64,
}

/// Phase 2 output: bytes of one resolved source.
#[derive(Debug, Clone)]
pub struct DownloadedSource {
    /// OS target label.
    pub os: String,
    /// The producer that created these bytes (preserved from phase 1).
    pub producer: SourceProducer,
    /// Raw bytes of the payload.
    pub bytes: Vec<u8>,
    /// Expected byte size, if known.
    pub expected_size: Option<u64>,
}

/// Phase 2 output: all downloaded or generated bytes for one tool.
#[derive(Debug, Clone)]
pub struct DownloadedSources {
    /// Logical tool identifier.
    pub tool_id: String,
    /// Per-platform source bytes.
    pub entries: Vec<DownloadedSource>,
}

/// Phase 3 output: final content map and command selector for a tool.
#[derive(Debug, Clone)]
pub struct ProvisionResult {
    /// Content map: sandbox-relative path → CAS hash hex string.
    /// For archive formats the key is a trailing-slash directory entry
    /// (`{os}/`); for binary format it is a file-level entry (`{os}/{tool_id}`).
    pub content_map: BTreeMap<String, String>,
    /// Sandbox-relative path to the main executable, emitted as a
    /// `${context.os == "…" ? …/… : …}` template expression when multiple
    /// platforms are provisioned.
    pub command_selector: String,
}

// ██████████████████████████████████████████████████████████████████████████████
// Per-tool dispatchers
// ██████████████████████████████████████████████████████████████████████████████

pub(crate) mod archive;
pub(crate) mod echo;
pub(crate) mod export;
pub(crate) mod fs;
pub(crate) mod import;
/// Dispatches to the correct per-tool source resolver.
pub(crate) mod sd;

// ██████████████████████████████████████████████████████████████████████████████
// Phase 1 — Resolve
// ██████████████████████████████████████████████████████████████████████████████

/// Resolves metadata and source descriptors for the given tool.
///
/// # Errors
///
/// Returns [`ConductorError`] when the tool is unknown.
#[cfg(feature = "tool-presets")]
pub async fn resolve_tool_fetch(
    tool_id: &str,
    _version: Option<VersionSpec>,
    _progress_cb: Option<ProviderProgressCallback>,
) -> Result<ResolvedToolFetch, crate::error::ConductorError> {
    match tool_id {
        n if n.eq_ignore_ascii_case("sd") => Ok(sd::sources()),
        n if n.eq_ignore_ascii_case("echo") => Ok(echo::sources()),
        n if n.eq_ignore_ascii_case("archive") => Ok(archive::sources()),
        n if n.eq_ignore_ascii_case("export") => Ok(export::sources()),
        n if n.eq_ignore_ascii_case("fs") => Ok(fs::sources()),
        n if n.eq_ignore_ascii_case("import") => Ok(import::sources()),
        _ => Err(crate::error::ConductorError::Workflow(format!(
            "tool {tool_id}: no provider registered for resolution"
        ))),
    }
}

// ██████████████████████████████████████████████████████████████████████████████
// Phase 2 — Fetch
// ██████████████████████████████████████████████████████████████████████████████

/// Fetches (or generates) bytes for every source in `fetch`.
///
/// URL sources are tried in order; the first HTTP 200 wins. Launcher sources
/// generate shell/batch script bytes in memory. Uses `cache` for deduplication
/// of downloaded payloads.
///
/// # Errors
///
/// Returns [`ConductorError`] when all URL candidates fail or I/O fails.
#[cfg(feature = "tool-presets")]
pub async fn fetch_tool_sources(
    fetch: &ResolvedToolFetch,
    cache: &crate::cache_user_level::UserLevelCache,
    progress_cb: Option<ProviderProgressCallback>,
) -> Result<DownloadedSources, crate::error::ConductorError> {
    use mediapm_utils::progress::ProviderPhase;

    let mut entries = Vec::with_capacity(fetch.sources.len());
    let mut items_done = 0u64;
    let total = fetch.total_items;

    for source in &fetch.sources {
        match &source.producer {
            SourceProducer::Fetch { urls } => {
                let cache_key = format!("{}_{}", fetch.tool_id, source.os);
                let bytes = if let Some(cached) = cache.lookup_bytes(&cache_key).await {
                    cached
                } else {
                    let downloaded = fetch_bytes_from_candidates(
                        urls,
                        &fetch.tool_id,
                        &source.os,
                        &progress_cb,
                        items_done,
                        total,
                    )
                    .await?;
                    cache.store_bytes(&cache_key, &downloaded).await;
                    downloaded
                };
                entries.push(DownloadedSource {
                    os: source.os.clone(),
                    producer: SourceProducer::Fetch { urls: urls.clone() },
                    bytes,
                    expected_size: source.expected_size,
                });
            }
            SourceProducer::GenerateLauncher { builtin_id } => {
                let bytes = generate_launcher_script(source.os.as_str(), builtin_id);
                entries.push(DownloadedSource {
                    os: source.os.clone(),
                    producer: SourceProducer::GenerateLauncher { builtin_id: builtin_id.clone() },
                    bytes,
                    expected_size: None,
                });
            }
        }
        items_done += 1;
        if let Some(cb) = progress_cb.as_ref() {
            cb(mediapm_utils::progress::ProviderProgressSnapshot {
                phase: ProviderPhase::Fetch,
                items: (items_done, total),
                bytes: (0, 0),
            });
        }
    }

    Ok(DownloadedSources { tool_id: fetch.tool_id.clone(), entries })
}

/// Downloads bytes from URL candidates (tried in order).
#[cfg(feature = "tool-presets")]
async fn fetch_bytes_from_candidates(
    urls: &[String],
    tool_id: &str,
    os_label: &str,
    progress_cb: &Option<ProviderProgressCallback>,
    items_done: u64,
    total: u64,
) -> Result<Vec<u8>, crate::error::ConductorError> {
    use crate::error::ConductorError;
    use futures_util::StreamExt;
    use mediapm_utils::progress::ProviderPhase;

    const CONDUCTOR_USER_AGENT: &str = concat!("mediapm-conductor/", env!("CARGO_PKG_VERSION"));

    let client = reqwest::Client::builder()
        .user_agent(CONDUCTOR_USER_AGENT)
        .build()
        .map_err(|e| ConductorError::Workflow(format!("building HTTP client failed: {e}")))?;

    for url in urls {
        let request = client.get(url);
        match request.send().await {
            Ok(response) if response.status().is_success() => {
                let total_bytes = response.content_length();
                let mut downloaded = 0u64;
                let mut buffer = Vec::new();
                let mut stream = response.bytes_stream();
                while let Some(chunk_result) = stream.next().await {
                    let chunk = chunk_result
                        .map_err(|e| ConductorError::Workflow(format!("download error: {e}")))?;
                    downloaded += chunk.len() as u64;
                    buffer.extend_from_slice(&chunk);
                    if let Some(cb) = progress_cb {
                        cb(mediapm_utils::progress::ProviderProgressSnapshot {
                            phase: ProviderPhase::Fetch,
                            items: (items_done, total),
                            bytes: (downloaded, total_bytes.unwrap_or(0)),
                        });
                    }
                }
                return Ok(buffer);
            }
            Ok(response) => {
                tracing::warn!("HTTP {} for {}, skipping", response.status(), url);
            }
            Err(e) => {
                tracing::warn!("HTTP error for {url}: {e}, skipping");
            }
        }
    }

    Err(ConductorError::Workflow(format!(
        "tool {tool_id} os {os_label}: all {} download candidates failed",
        urls.len()
    )))
}

/// Generates a launcher script that dispatches `$MEDIAPM_EXECUTABLE {builtin_id} {args...}`.
#[cfg(feature = "tool-presets")]
fn generate_launcher_script(os: &str, builtin_id: &str) -> Vec<u8> {
    match os {
        "windows" => {
            format!("@echo off\r\n\"%MEDIAPM_EXECUTABLE%\" {builtin_id} %*\r\n").into_bytes()
        }
        _ => {
            // Linux / macOS — POSIX shell with `exec`.
            format!("#!/bin/sh\nexec \"${{MEDIAPM_EXECUTABLE}}\" {builtin_id} \"$@\"\n")
                .into_bytes()
        }
    }
}

// ██████████████████████████████████████████████████████████████████████████████
// Phase 3 — Postprocess
// ██████████████████████████████████████████████████████████████████████████████

/// Postprocesses downloaded sources: extract archives, import to CAS, build
/// content map and command selector.
///
/// For archive formats (ZIP, tar.gz, tar.xz) the extracted directory is
/// repacked into a single uncompressed ZIP and imported to CAS, producing
/// a single trailing-slash content-map key (`{os}/`). For binary format the
/// file is imported as a file-level entry (`{os}/{tool_id}`).
///
/// Archive format is inferred from the URL extension or content magic bytes.
///
/// # Errors
///
/// Returns [`ConductorError`] when extraction, packing, or CAS import fails.
#[cfg(feature = "tool-presets")]
pub async fn postprocess_tool_sources(
    downloaded: &DownloadedSources,
    cas: &impl mediapm_cas::CasApi,
    progress_cb: Option<ProviderProgressCallback>,
) -> Result<ProvisionResult, crate::error::ConductorError> {
    use mediapm_utils::progress::ProviderPhase;

    let temp_root = tempfile::tempdir().map_err(|source| {
        crate::error::ConductorError::io(
            "creating temp directory for tool extraction",
            std::path::PathBuf::new(),
            source,
        )
    })?;

    let mut content_map: BTreeMap<String, String> = BTreeMap::new();
    let mut per_os_exec: BTreeMap<String, String> = BTreeMap::new();
    let total = downloaded.entries.len() as u64;

    for (idx, source) in downloaded.entries.iter().enumerate() {
        let os_label = &source.os;
        let os_dir = temp_root.path().join(os_label);

        // Infer archive format from URL or treat as binary for launcher scripts.
        let archive_format = match &source.producer {
            SourceProducer::Fetch { urls } => {
                infer_archive_format(urls.first().map_or("", |s| s.as_str()))
            }
            SourceProducer::GenerateLauncher { .. } => ARCHIVE_BINARY,
        };

        let (os_cm, exec_path) = process_single_source(
            &source.bytes,
            archive_format,
            os_label,
            &downloaded.tool_id,
            &os_dir,
            cas,
        )
        .await?;

        content_map.extend(os_cm);
        per_os_exec.insert(os_label.to_string(), exec_path);

        if let Some(cb) = progress_cb.as_ref() {
            cb(mediapm_utils::progress::ProviderProgressSnapshot {
                phase: ProviderPhase::Postprocess,
                items: ((idx + 1) as u64, total),
                bytes: (source.bytes.len() as u64, 0),
            });
        }
    }

    let command_selector = build_os_conditional_selector(&per_os_exec);

    Ok(ProvisionResult { content_map, command_selector })
}

/// Infers archive format from a URL's file extension.
#[cfg(feature = "tool-presets")]
fn infer_archive_format(url: &str) -> &'static str {
    let url_path = url.split('?').next().unwrap_or(url);
    let filename = url_path.trim_end_matches('/').split('/').next_back().unwrap_or(url_path);
    if filename.ends_with(".tar.xz") {
        ARCHIVE_TAR_XZ
    } else if filename.ends_with(".tar.gz") || filename.ends_with(".tgz") {
        ARCHIVE_TAR_GZ
    } else if filename.ends_with(".zip") || filename == "zip" {
        ARCHIVE_ZIP
    } else {
        // No recognized extension or bare name → binary
        ARCHIVE_BINARY
    }
}

/// Processes one downloaded source: extract, repack, CAS import.
#[cfg(feature = "tool-presets")]
async fn process_single_source(
    bytes: &[u8],
    archive_format: &str,
    os_label: &str,
    tool_id: &str,
    os_dir: &std::path::Path,
    cas: &impl mediapm_cas::CasApi,
) -> Result<(BTreeMap<String, String>, String), crate::error::ConductorError> {
    use crate::error::ConductorError;
    use bytes::Bytes;

    std::fs::create_dir_all(os_dir).map_err(|source| {
        ConductorError::io(
            &format!("creating temp directory for {os_label} tool extraction"),
            os_dir,
            source,
        )
    })?;

    extract_archive(bytes, archive_format, os_dir)?;

    // ── binary-format rename ───────────────────────────────────────
    // `extract_binary` writes with a generic "tool"/"tool.exe" name; rename
    // to the actual `tool_id` so the downstream read finds the right file.
    if archive_format == ARCHIVE_BINARY {
        let generic_name = if cfg!(target_os = "windows") { "tool.exe" } else { "tool" };
        let generic_path = os_dir.join(generic_name);
        let tool_path = os_dir.join(tool_id);
        if generic_path != tool_path && generic_path.exists() {
            std::fs::rename(&generic_path, &tool_path).map_err(|source| {
                ConductorError::io(
                    &format!("renaming generic binary to '{tool_id}'"),
                    &generic_path,
                    source,
                )
            })?;
        }
    }

    if archive_format == ARCHIVE_BINARY {
        // ── binary format: single file entry ────────────────────────
        let tool_path = os_dir.join(tool_id);
        let file_bytes = std::fs::read(&tool_path).map_err(|source| {
            ConductorError::io(
                &format!("reading binary '{tool_id}' for CAS import"),
                &tool_path,
                source,
            )
        })?;
        let hash = cas.put(Bytes::from(file_bytes)).await.map_err(|e| ConductorError::Cas(e))?;
        let key = format!("{os_label}/{tool_id}");
        let mut cm = BTreeMap::new();
        cm.insert(key, hash.to_hex());
        Ok((cm, tool_id.to_string()))
    } else {
        // ── archive format: pack OS directory, single dir entry ─────
        let exec_path = find_os_executable(os_dir, tool_id).unwrap_or_else(|| tool_id.to_string());

        let zip_bytes = pack_directory_to_uncompressed_zip_bytes(os_dir)?;
        let hash = cas.put(Bytes::from(zip_bytes)).await.map_err(|e| ConductorError::Cas(e))?;
        let key = format!("{os_label}/");
        let mut cm = BTreeMap::new();
        cm.insert(key, hash.to_hex());
        Ok((cm, exec_path))
    }
}

// ---------------------------------------------------------------------------
// Archive extraction helpers
// ---------------------------------------------------------------------------

/// Extracts archive bytes to the given directory based on archive format.
#[cfg(feature = "tool-presets")]
fn extract_archive(
    bytes: &[u8],
    format: &str,
    target_dir: &std::path::Path,
) -> Result<(), crate::error::ConductorError> {
    use crate::error::ConductorError;
    match format {
        ARCHIVE_ZIP => extract_zip(bytes, target_dir),
        ARCHIVE_TAR_GZ => extract_tar_gz(bytes, target_dir),
        ARCHIVE_TAR_XZ => extract_tar_xz(bytes, target_dir),
        ARCHIVE_BINARY => extract_binary(bytes, target_dir),
        other => Err(ConductorError::Workflow(format!("unsupported archive format: {other}"))),
    }
}

#[cfg(feature = "tool-presets")]
fn extract_zip(
    bytes: &[u8],
    target_dir: &std::path::Path,
) -> Result<(), crate::error::ConductorError> {
    use crate::error::ConductorError;
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(bytes))
        .map_err(|e| ConductorError::Workflow(format!("ZIP open error: {e}")))?;

    for i in 0..archive.len() {
        let mut file = archive
            .by_index(i)
            .map_err(|e| ConductorError::Workflow(format!("ZIP entry error: {e}")))?;
        let out_path = target_dir.join(file.name());
        if file.name().ends_with('/') {
            std::fs::create_dir_all(&out_path)
                .map_err(|e| ConductorError::io("create directory", &out_path, e))?;
        } else {
            if let Some(parent) = out_path.parent() {
                std::fs::create_dir_all(parent)
                    .map_err(|e| ConductorError::io("create directory", parent, e))?;
            }
            let mut out = std::fs::File::create(&out_path)
                .map_err(|e| ConductorError::io("create file", &out_path, e))?;
            std::io::copy(&mut file, &mut out)
                .map_err(|e| ConductorError::io("write file", &out_path, e))?;
        }
    }
    Ok(())
}

#[cfg(feature = "tool-presets")]
fn extract_tar_gz(
    bytes: &[u8],
    target_dir: &std::path::Path,
) -> Result<(), crate::error::ConductorError> {
    use crate::error::ConductorError;
    let decoder = flate2::read::GzDecoder::new(bytes);
    let mut archive = tar::Archive::new(decoder);
    archive.unpack(target_dir).map_err(|e| ConductorError::io("extract tar.gz", target_dir, e))
}

#[cfg(feature = "tool-presets")]
fn extract_tar_xz(
    bytes: &[u8],
    target_dir: &std::path::Path,
) -> Result<(), crate::error::ConductorError> {
    use crate::error::ConductorError;
    let decoder = xz2::read::XzDecoder::new(bytes);
    let mut archive = tar::Archive::new(decoder);
    archive.unpack(target_dir).map_err(|e| ConductorError::io("extract tar.xz", target_dir, e))
}

#[cfg(feature = "tool-presets")]
fn extract_binary(
    bytes: &[u8],
    target_dir: &std::path::Path,
) -> Result<(), crate::error::ConductorError> {
    use crate::error::ConductorError;
    let exe_name = if cfg!(target_os = "windows") { "tool.exe" } else { "tool" };
    let out_path = target_dir.join(exe_name);
    std::fs::write(&out_path, bytes)
        .map_err(|e| ConductorError::io("write binary payload", &out_path, e))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&out_path, std::fs::Permissions::from_mode(0o755))
            .map_err(|e| ConductorError::io("set permissions", &out_path, e))?;
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Pack helpers
// ---------------------------------------------------------------------------

/// Packs one directory tree into uncompressed ZIP bytes.
#[cfg(feature = "tool-presets")]
fn pack_directory_to_uncompressed_zip_bytes(
    dir: &std::path::Path,
) -> Result<Vec<u8>, crate::error::ConductorError> {
    use crate::error::ConductorError;
    use zip::write::SimpleFileOptions;

    let mut buf = Vec::new();
    {
        let mut writer = zip::ZipWriter::new(std::io::Cursor::new(&mut buf));
        let options =
            SimpleFileOptions::default().compression_method(zip::CompressionMethod::Stored);

        pack_directory_entries(&mut writer, dir, dir, &options)?;

        writer.finish().map_err(|e| {
            ConductorError::Workflow(format!("failed to finalize zip archive: {e}"))
        })?;
    }
    Ok(buf)
}

/// Recursively adds directory entries to the zip writer.
#[cfg(feature = "tool-presets")]
fn pack_directory_entries(
    writer: &mut zip::ZipWriter<std::io::Cursor<&mut Vec<u8>>>,
    root: &std::path::Path,
    dir: &std::path::Path,
    options: &zip::write::SimpleFileOptions,
) -> Result<(), crate::error::ConductorError> {
    use crate::error::ConductorError;
    use std::io::Read;
    use std::io::Write;

    for entry in std::fs::read_dir(dir).map_err(|source| {
        ConductorError::io(&format!("reading directory '{}'", dir.display()), dir, source)
    })? {
        let entry = entry.map_err(|source| {
            ConductorError::io(
                &format!("reading directory entry in '{}'", dir.display()),
                dir,
                source,
            )
        })?;
        let path = entry.path();
        if path.is_dir() {
            pack_directory_entries(writer, root, &path, options)?;
        } else {
            let relative = path.strip_prefix(root).unwrap_or(&path).to_string_lossy().to_string();
            let mut file = std::fs::File::open(&path).map_err(|source| {
                ConductorError::io(
                    &format!("opening file '{}' for zip", path.display()),
                    &path,
                    source,
                )
            })?;
            writer.start_file(relative.clone(), *options).map_err(|e| {
                ConductorError::Workflow(format!("failed to start zip entry '{relative}': {e}"))
            })?;
            let mut contents = Vec::new();
            file.read_to_end(&mut contents).map_err(|source| {
                ConductorError::io(
                    &format!("reading file '{}' for zip", path.display()),
                    &path,
                    source,
                )
            })?;
            writer.write_all(&contents).map_err(|e| {
                ConductorError::Workflow(format!("failed to write zip entry '{relative}': {e}"))
            })?;
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// File finding helpers
// ---------------------------------------------------------------------------

/// Searches for an executable named `{tool_id}` or `{tool_id}.exe` inside
/// `os_dir` and returns its path relative to `os_dir`.
#[cfg(feature = "tool-presets")]
fn find_os_executable(os_dir: &std::path::Path, tool_id: &str) -> Option<String> {
    let candidates = [tool_id.to_string(), format!("{tool_id}.exe")];
    for name in &candidates {
        if let Some(rel) = find_file_relative(os_dir, os_dir, name) {
            return Some(rel.to_string_lossy().to_string());
        }
    }
    None
}

/// Recursively searches for a file with the given name, returning its path
/// relative to `root`.
#[cfg(feature = "tool-presets")]
fn find_file_relative(
    root: &std::path::Path,
    dir: &std::path::Path,
    target: &str,
) -> Option<std::path::PathBuf> {
    for entry in std::fs::read_dir(dir).ok()? {
        let entry = entry.ok()?;
        let path = entry.path();
        if path.is_dir() {
            if let found @ Some(_) = find_file_relative(root, &path, target) {
                return found;
            }
        } else if path.file_name().and_then(|n| n.to_str()) == Some(target) {
            return path.strip_prefix(root).ok().map(|p| p.to_path_buf());
        }
    }
    None
}

/// Builds a `${context.os == "linux" ? linux/sd : context.os == "macos" ? macos/sd : windows/sd}`
/// template string from the per-OS executable suffix map.
///
/// When only one OS is provisioned the template collapses to a plain path.
#[cfg(feature = "tool-presets")]
fn build_os_conditional_selector(per_os_exec: &BTreeMap<String, String>) -> String {
    if per_os_exec.is_empty() {
        return String::new();
    }
    let mut iter = per_os_exec.iter();
    let (first_os, first_path) = iter.next().expect("non-empty per_os_exec");
    if per_os_exec.len() == 1 {
        return format!("{first_os}/{first_path}");
    }
    let mut result = format!("${{context.os == \"{first_os}\" ? {first_os}/{first_path}");
    for (os, path) in iter.by_ref() {
        result.push_str(&format!(" : context.os == \"{os}\" ? {os}/{path}"));
    }
    result.push('}');
    result
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[cfg(feature = "tool-presets")]
mod tests {
    use std::io::Write;

    use mediapm_cas::InMemoryCas;

    use super::*;

    // ── Synthetic archive helpers ─────────────────────────────────────

    fn synthetic_zip(entries: &[(&str, &[u8])]) -> Vec<u8> {
        use zip::write::SimpleFileOptions;
        let cursor = std::io::Cursor::new(Vec::new());
        let mut writer = zip::ZipWriter::new(cursor);
        let options = SimpleFileOptions::default();
        for (name, content) in entries {
            writer.start_file(*name, options.clone()).unwrap();
            writer.write_all(content).unwrap();
        }
        let cursor = writer.finish().unwrap();
        cursor.into_inner()
    }

    fn synthetic_tar_gz(entries: &[(&str, &[u8])]) -> Vec<u8> {
        use flate2::Compression;
        use flate2::write::GzEncoder;
        let buf = Vec::new();
        let encoder = GzEncoder::new(buf, Compression::fast());
        let mut tar = tar::Builder::new(encoder);
        for (name, content) in entries {
            let mut header = tar::Header::new_gnu();
            header.set_path(name).unwrap();
            header.set_size(content.len() as u64);
            header.set_mode(0o644);
            header.set_cksum();
            tar.append(&header, *content).unwrap();
        }
        let encoder = tar.into_inner().unwrap();
        encoder.finish().unwrap()
    }

    fn synthetic_tar_xz(entries: &[(&str, &[u8])]) -> Vec<u8> {
        use xz2::write::XzEncoder;
        let buf = Vec::new();
        let encoder = XzEncoder::new(buf, 6);
        let mut tar = tar::Builder::new(encoder);
        for (name, content) in entries {
            let mut header = tar::Header::new_gnu();
            header.set_path(name).unwrap();
            header.set_size(content.len() as u64);
            header.set_mode(0o644);
            header.set_cksum();
            tar.append(&header, *content).unwrap();
        }
        let encoder = tar.into_inner().unwrap();
        encoder.finish().unwrap()
    }

    const EXEC_BYTES: &[u8] = b"#!/bin/sh\necho mocked\n";

    // ── infer_archive_format ──────────────────────────────────────────

    #[test]
    fn infer_format_from_url_extension() {
        assert_eq!(infer_archive_format("https://example.com/tool.tar.xz"), ARCHIVE_TAR_XZ);
        assert_eq!(infer_archive_format("https://example.com/tool.tar.gz"), ARCHIVE_TAR_GZ);
        assert_eq!(infer_archive_format("https://example.com/tool.tgz"), ARCHIVE_TAR_GZ);
        assert_eq!(infer_archive_format("https://example.com/tool.zip"), ARCHIVE_ZIP);
        assert_eq!(infer_archive_format("https://example.com/tool"), ARCHIVE_BINARY);
        assert_eq!(infer_archive_format("https://example.com/tool.exe"), ARCHIVE_BINARY);
    }

    // ── build_os_conditional_selector ─────────────────────────────────

    #[test]
    fn selector_empty_map_returns_empty_string() {
        assert_eq!(build_os_conditional_selector(&BTreeMap::new()), "");
    }

    #[test]
    fn selector_single_os_returns_plain_path() {
        let mut map: BTreeMap<String, String> = BTreeMap::new();
        map.insert("linux".into(), "sd".into());
        assert_eq!(build_os_conditional_selector(&map), "linux/sd");
    }

    #[test]
    fn selector_two_oses_produces_template() {
        let mut map: BTreeMap<String, String> = BTreeMap::new();
        map.insert("linux".into(), "sd".into());
        map.insert("macos".into(), "sd".into());
        let result = build_os_conditional_selector(&map);
        assert!(result.starts_with("${context.os == \""));
        assert!(result.contains("linux/sd"));
        assert!(result.contains("macos/sd"));
        assert!(result.ends_with('}'));
    }

    #[test]
    fn selector_three_oses_produces_full_template() {
        let mut map: BTreeMap<String, String> = BTreeMap::new();
        map.insert("linux".into(), "sd".into());
        map.insert("macos".into(), "sd".into());
        map.insert("windows".into(), "sd.exe".into());
        let result = build_os_conditional_selector(&map);
        assert!(result.contains("linux/sd"));
        assert!(result.contains("macos/sd"));
        assert!(result.contains("windows/sd.exe"));
        assert!(result.starts_with("${context.os == \"linux\""));
    }

    // ── find_file_relative ────────────────────────────────────────────

    #[test]
    fn find_file_at_root() {
        let dir = tempfile::tempdir().unwrap();
        let file_path = dir.path().join("sd");
        std::fs::write(&file_path, "").unwrap();
        assert_eq!(
            find_file_relative(dir.path(), dir.path(), "sd"),
            Some(std::path::PathBuf::from("sd"))
        );
    }

    #[test]
    fn find_file_in_nested_dir() {
        let dir = tempfile::tempdir().unwrap();
        let sub = dir.path().join("bin");
        std::fs::create_dir(&sub).unwrap();
        std::fs::write(sub.join("sd"), "").unwrap();
        assert_eq!(
            find_file_relative(dir.path(), dir.path(), "sd"),
            Some(std::path::PathBuf::from("bin/sd"))
        );
    }

    #[test]
    fn find_file_absent_returns_none() {
        let dir = tempfile::tempdir().unwrap();
        assert!(find_file_relative(dir.path(), dir.path(), "nonexistent").is_none());
    }

    // ── find_os_executable ────────────────────────────────────────────

    #[test]
    fn find_os_exec_direct_match() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("sd"), "").unwrap();
        assert_eq!(find_os_executable(dir.path(), "sd"), Some("sd".into()));
    }

    #[test]
    fn find_os_exec_finds_exe_variant() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("sd.exe"), "").unwrap();
        assert_eq!(find_os_executable(dir.path(), "sd"), Some("sd.exe".into()));
    }

    #[test]
    fn find_os_exec_not_found_returns_none() {
        let dir = tempfile::tempdir().unwrap();
        assert!(find_os_executable(dir.path(), "nonexistent").is_none());
    }

    // ── process_single_source (with InMemoryCas) ─────────────────────

    #[tokio::test]
    async fn process_zip_archive_linux_label() {
        let zip = synthetic_zip(&[("sd", EXEC_BYTES)]);
        let cas = InMemoryCas::default();
        let os_dir = tempfile::tempdir().unwrap();
        let (cmap, exec) =
            process_single_source(&zip, ARCHIVE_ZIP, "linux", "sd", os_dir.path(), &cas)
                .await
                .unwrap();
        assert_eq!(cmap.len(), 1);
        assert!(cmap.contains_key("linux/"));
        assert_eq!(exec, "sd");
    }

    #[tokio::test]
    async fn process_tar_gz_archive_macos_label() {
        let tgz = synthetic_tar_gz(&[("sd", EXEC_BYTES)]);
        let cas = InMemoryCas::default();
        let os_dir = tempfile::tempdir().unwrap();
        let (cmap, exec) =
            process_single_source(&tgz, ARCHIVE_TAR_GZ, "macos", "sd", os_dir.path(), &cas)
                .await
                .unwrap();
        assert_eq!(cmap.len(), 1);
        assert!(cmap.contains_key("macos/"));
        assert_eq!(exec, "sd");
    }

    #[tokio::test]
    async fn process_tar_xz_archive_windows_label() {
        let txz = synthetic_tar_xz(&[("sd.exe", EXEC_BYTES)]);
        let cas = InMemoryCas::default();
        let os_dir = tempfile::tempdir().unwrap();
        let (cmap, exec) =
            process_single_source(&txz, ARCHIVE_TAR_XZ, "windows", "sd", os_dir.path(), &cas)
                .await
                .unwrap();
        assert_eq!(cmap.len(), 1);
        assert!(cmap.contains_key("windows/"));
        assert_eq!(exec, "sd.exe");
    }

    #[tokio::test]
    async fn process_binary_format_produces_file_entry() {
        let cas = InMemoryCas::default();
        let os_dir = tempfile::tempdir().unwrap();
        let launcher_bytes = generate_launcher_script("linux", "echo@v1");
        let (cmap, exec) = process_single_source(
            &launcher_bytes,
            ARCHIVE_BINARY,
            "linux",
            "echo",
            os_dir.path(),
            &cas,
        )
        .await
        .unwrap();
        assert_eq!(cmap.len(), 1);
        assert!(cmap.contains_key("linux/echo"));
        assert_eq!(exec, "echo");
    }

    // ── generate_launcher_script ──────────────────────────────────────

    #[test]
    fn generate_windows_launcher() {
        let script = generate_launcher_script("windows", "echo@v1");
        let text = String::from_utf8_lossy(&script);
        assert!(text.contains("MEDIAPM_EXECUTABLE"));
        assert!(text.contains("echo@v1"));
        assert!(text.contains("%*"));
    }

    #[test]
    fn generate_unix_launcher() {
        let script = generate_launcher_script("linux", "echo@v1");
        let text = String::from_utf8_lossy(&script);
        assert!(text.contains("exec"));
        assert!(text.contains("MEDIAPM_EXECUTABLE"));
        assert!(text.contains("echo@v1"));
        assert!(text.contains("$@"));
    }

    #[test]
    fn generate_macos_launcher() {
        let script = generate_launcher_script("macos", "echo@v1");
        let text = String::from_utf8_lossy(&script);
        assert!(text.contains("exec"));
        assert!(text.contains("MEDIAPM_EXECUTABLE"));
        assert!(text.contains("echo@v1"));
    }

    // ── extract helpers ───────────────────────────────────────────────

    #[test]
    fn extract_zip_rejects_tar_xz_bytes() {
        let txz = synthetic_tar_xz(&[("x", &[0u8; 4])]);
        let dir = tempfile::tempdir().unwrap();
        assert!(extract_archive(&txz, ARCHIVE_ZIP, dir.path()).is_err());
    }

    #[test]
    fn extract_tar_gz_rejects_zip_bytes() {
        let zip = synthetic_zip(&[("x", &[0u8; 4])]);
        let dir = tempfile::tempdir().unwrap();
        assert!(extract_archive(&zip, ARCHIVE_TAR_GZ, dir.path()).is_err());
    }

    #[test]
    fn extract_tar_xz_rejects_zip_bytes() {
        let zip = synthetic_zip(&[("x", &[0u8; 4])]);
        let dir = tempfile::tempdir().unwrap();
        assert!(extract_archive(&zip, ARCHIVE_TAR_XZ, dir.path()).is_err());
    }

    #[test]
    fn extract_binary_writes_bytes_as_file() {
        let dir = tempfile::tempdir().unwrap();
        let data = b"binary content";
        extract_archive(data, ARCHIVE_BINARY, dir.path()).unwrap();
        let exe_name = if cfg!(target_os = "windows") { "tool.exe" } else { "tool" };
        let path = dir.path().join(exe_name);
        assert!(path.exists());
        assert_eq!(std::fs::read(path).unwrap(), data);
    }

    // ── pack_directory_to_uncompressed_zip_bytes ──────────────────────

    #[test]
    fn pack_directory_creates_zip_with_all_files() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("a.txt"), b"aaa").unwrap();
        std::fs::create_dir(dir.path().join("sub")).unwrap();
        std::fs::write(dir.path().join("sub").join("b.txt"), b"bbb").unwrap();

        let zip_bytes = pack_directory_to_uncompressed_zip_bytes(dir.path()).unwrap();
        let mut archive = zip::ZipArchive::new(std::io::Cursor::new(&zip_bytes)).unwrap();
        assert_eq!(archive.len(), 2);

        let mut names: Vec<String> =
            (0..archive.len()).map(|i| archive.by_index(i).unwrap().name().to_string()).collect();
        names.sort();
        assert_eq!(names, vec!["a.txt", "sub/b.txt"]);
    }

    // ── Property-based tests (proptest) ───────────────────────────────

    use proptest::prelude::*;

    proptest! {
        /// `infer_archive_format` is deterministic: same input always yields
        /// the same output.
        #[test]
        fn infer_archive_format_deterministic(url: String) {
            let result1 = infer_archive_format(&url);
            let result2 = infer_archive_format(&url);
            assert_eq!(result1, result2);
        }

        /// URLs with recognised extensions are classified correctly.
        #[test]
        fn infer_archive_format_known_patterns(
            stem in "[a-z]+",
            ext in ".tar.xz|.tar.gz|.tgz|.zip",
        ) {
            let url = format!("https://example.com/{stem}{ext}");
            let result = infer_archive_format(&url);
            if ext == ".tar.xz" {
                assert_eq!(result, ARCHIVE_TAR_XZ);
            } else if ext == ".tar.gz" || ext == ".tgz" {
                assert_eq!(result, ARCHIVE_TAR_GZ);
            } else if ext == ".zip" {
                assert_eq!(result, ARCHIVE_ZIP);
            }
        }

        /// `build_os_conditional_selector` includes every OS/path entry.
        #[test]
        fn build_os_conditional_selector_roundtrip(
            entries in prop::collection::btree_map(
                "(linux|macos|windows)".prop_filter("OS must be non-empty", |s| !s.is_empty()),
                "[a-zA-Z0-9._/-]+",
                0..4,
            )
        ) {
            let selector = build_os_conditional_selector(&entries);
            if entries.is_empty() {
                assert_eq!(selector, "", "empty map should produce empty string");
                return Ok(());
            }
            for (os, path) in &entries {
                let expected_fragment = format!("{os}/{path}");
                assert!(
                    selector.contains(&expected_fragment),
                    "selector {selector:?} should contain {expected_fragment:?}"
                );
            }
            if entries.len() == 1 {
                // Single entry collapses to a plain path (no template wrapper).
                let (os, path) = entries.iter().next().unwrap();
                assert_eq!(selector, format!("{os}/{path}"));
            } else {
                assert!(selector.starts_with("${context.os == \""),
                    "multi-OS selector should start with template syntax: {selector:?}");
                assert!(selector.ends_with('}'),
                    "multi-OS selector should end with '}}': {selector:?}");
            }
        }

        /// `find_file_relative` symmetry: if a file exists at `{dir}/{path}`,
        /// searching for its name finds it, and the returned relative path
        /// resolves back to the absolute path when joined with root.
        #[test]
        fn find_file_relative_symmetry(
            _dir_name in "[a-z]{1,8}",
            file_name in "[a-z]{1,8}\\.txt",
            depth in 0..3usize,
        ) {
            let dir = tempfile::tempdir().unwrap();
            let root = dir.path();

            // Build nested directory structure up to `depth`.
            let mut sub_path = std::path::PathBuf::new();
            for i in 0..depth {
                sub_path.push(format!("sub{i}"));
            }
            let target_dir = root.join(&sub_path);
            std::fs::create_dir_all(&target_dir).unwrap();

            // Create the target file.
            let abs_file_path = target_dir.join(&file_name);
            std::fs::write(&abs_file_path, b"content").unwrap();

            // Search for it.
            let found = find_file_relative(root, root, &file_name);
            prop_assert!(found.is_some(),
                "file {:?} at {:?} should be found under {:?}", file_name, abs_file_path, root);

            let relative = found.unwrap();
            // The relative path + root should equal the absolute file path.
            let reconstructed = root.join(&relative);
            prop_assert_eq!(reconstructed.clone(), abs_file_path.clone(),
                "reconstructed path {:?} should match {:?}", reconstructed, abs_file_path);
        }
    }
}
