//! Native mediapm metadata tagging pipeline.
//!
//! This module replaces the legacy external Picard step with an internal
//! `mediapm` flow:
//! 1. decode input audio and compute Chromaprint fingerprint,
//! 2. resolve MBIDs through AcoustID,
//! 3. fetch rich recording/release payloads through `musicbrainz_rs`,
//! 4. map metadata into `FFmetadata` key/value pairs,
//! 5. persist one `FFmetadata` document for downstream apply stages.
//!
//! Failure policy is controlled by `strict_identification`: when enabled,
//! unresolved identity or metadata-fetch failures abort the step; when disabled,
//! an empty `FFmetadata` document is written so downstream apply stages may
//! continue deterministically.
//! AcoustID lookup itself is only attempted when no recording MBID override is
//! supplied. Missing/empty lookup credentials are a hard error on that
//! autodetection path; when credentials are provided, lookup/authentication
//! failures are surfaced as hard errors.

#![allow(clippy::doc_markdown)]

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::{Context, bail};
use tokio::process::Command;

mod acoustid;
mod cover_art;
mod ffmetadata;
mod musicbrainz;
mod util;

#[cfg(test)]
mod tests;

use self::acoustid::{
    decode_and_fingerprint_audio, lookup_acoustid_match, require_acoustid_api_key_for_lookup,
    resolve_acoustid_api_key,
};
use self::cover_art::{
    CacheExpiryPolicy, MediaTaggerHttpCache, collect_musicbrainz_cover_art,
    insert_musicbrainz_image_tags, persist_cover_art_slot_artifacts,
};
use self::ffmetadata::parse_ffmetadata_global_map;
use self::musicbrainz::{build_ffmetadata_map, fetch_musicbrainz_payloads};
use self::util::{normalize_optional_text, resolve_ffmpeg_executable, write_ffmetadata_document};

/// Default AcoustID lookup endpoint used by the internal tagger.
pub const DEFAULT_ACOUSTID_ENDPOINT: &str = "https://api.acoustid.org/v2/lookup";
/// Default MusicBrainz API endpoint label used for diagnostics.
pub const DEFAULT_MUSICBRAINZ_ENDPOINT: &str = "https://musicbrainz.org/ws/2";

/// Target sample rate used for deterministic fingerprint extraction.
const FINGERPRINT_SAMPLE_RATE: u32 = 44_100;
/// Target channel count used for deterministic fingerprint extraction.
const FINGERPRINT_CHANNELS: u16 = 2;
/// Environment variable fallback for AcoustID API credentials.
const ACOUSTID_API_KEY_ENV: &str = "ACOUSTID_API_KEY";
/// Executable name used for decode/export metadata operations.
const FFMPEG_EXECUTABLE: &str = "ffmpeg";
/// Optional env-var override for ffmpeg executable used by internal tagger.
pub const MEDIA_TAGGER_FFMPEG_BIN_ENV: &str = "MEDIAPM_MEDIA_TAGGER_FFMPEG_BIN";
/// Maximum metadata entries emitted to `FFmetadata` output.
const MAX_FLATTENED_METADATA_ENTRIES: usize = 1_024;
/// Maximum flattened metadata value length to avoid runaway tags.
const MAX_FLATTENED_VALUE_LEN: usize = 4_096;
/// Default number of cover-art attachment slots prepared per invocation.
pub const DEFAULT_COVER_ART_SLOT_COUNT: usize = 4;
/// Default media-tagger HTTP cache expiry budget in seconds (one day).
pub const DEFAULT_CACHE_EXPIRY_SECONDS: i64 = 24 * 60 * 60;
/// Cache-index format marker for media-tagger JSONC metadata rows.
const MEDIA_TAGGER_CACHE_INDEX_VERSION: u32 = 1;
/// Default media-tagger metadata index file name under cache root.
const MEDIA_TAGGER_CACHE_INDEX_FILE_NAME: &str = "media-tagger.jsonc";
/// Retry count for transient media-tagger HTTP request failures.
const MEDIA_TAGGER_HTTP_RETRY_ATTEMPTS: usize = 3;
/// Initial retry backoff for transient media-tagger HTTP request failures.
const MEDIA_TAGGER_HTTP_RETRY_BASE_DELAY_MILLIS: u64 = 250;

/// Returns deterministic sandbox-artifact file name for one cover-art slot payload.
#[must_use]
pub(crate) fn cover_art_slot_image_member_name(slot_index: usize) -> String {
    format!("coverart-slot-{slot_index}.bin")
}

/// Returns deterministic sandbox-artifact file name for one cover-art slot flag.
#[must_use]
pub(crate) fn cover_art_slot_flag_member_name(slot_index: usize) -> String {
    format!("coverart-slot-{slot_index}.flag")
}

/// Runtime options for one internal media-tagger invocation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InternalMediaTaggerOptions {
    /// Optional input media path to inspect and tag.
    ///
    /// This is required only for fingerprint-based autodetection paths.
    pub input_path: Option<PathBuf>,
    /// Output `FFmetadata` path generated by this metadata-fetch stage.
    pub output_path: PathBuf,
    /// Optional AcoustID API key override.
    pub acoustid_api_key: Option<String>,
    /// AcoustID lookup endpoint.
    pub acoustid_endpoint: String,
    /// MusicBrainz API endpoint used in diagnostics.
    pub musicbrainz_endpoint: String,
    /// Optional media-tagger HTTP cache root directory.
    ///
    /// When provided, endpoint and cover-art payload responses are cached
    /// through one shared cache layout:
    /// - `<cache_dir>/store/` CAS payload objects,
    /// - `<cache_dir>/media-tagger.jsonc` key-to-hash metadata index.
    ///
    /// This keeps media-tagger cache semantics aligned with the workspace/user
    /// managed cache model and avoids dedicated per-tool directories inside
    /// `store/`.
    pub cache_dir: Option<PathBuf>,
    /// Cache expiry budget in seconds.
    ///
    /// Negative values disable cache expiry and keep rows indefinitely.
    pub cache_expiry_seconds: i64,
    /// Whether unresolved identity should fail the invocation.
    pub strict_identification: bool,
    /// Whether to emit extended `Picard`-compatible tags from available payloads.
    pub write_all_tags: bool,
    /// Whether to enrich metadata with `Picard`-compatible `coverart_*` tags.
    pub write_all_images: bool,
    /// Number of deterministic cover-art slots emitted for downstream apply.
    ///
    /// Managed workflow synthesis binds ffmpeg cover-image inputs to these
    /// slot files, so the internal tagger always writes all slot members:
    /// populated slots carry image bytes and "true" flags, unused slots carry
    /// empty payloads and empty flags.
    pub cover_art_slot_count: usize,
    /// Optional direct recording MBID override.
    pub recording_mbid: Option<String>,
    /// Optional direct release MBID override.
    pub release_mbid: Option<String>,
}

/// Executes one full internal tagging pipeline.
///
/// # Errors
///
/// Returns an error when metadata identification/fetching fails in strict mode,
/// when fallback metadata output cannot be written, or when upstream tool/API
/// calls fail in a way that prevents deterministic output generation.
pub async fn run_internal_media_tagger(options: InternalMediaTaggerOptions) -> anyhow::Result<()> {
    if let Some(input_path) = options.input_path.as_ref()
        && !input_path.exists()
    {
        bail!("input media path '{}' does not exist", input_path.display());
    }

    let output_path = options.output_path.clone();
    let fallback_input = options.input_path.clone();
    match run_internal_media_tagger_impl(options).await {
        Ok(()) => Ok(()),
        Err(error) => {
            let fallback_map = fallback_ffmetadata_map(fallback_input.as_deref()).await;
            if let Err(write_error) = write_ffmetadata_document(&output_path, &fallback_map) {
                return Err(error.context(format!(
                    "failed to persist fallback ffmetadata output '{}' after tagging error: {write_error}",
                    output_path.display()
                )));
            }

            Err(error)
        }
    }
}

/// Executes one full internal tagging pipeline without fallback-output handling.
#[expect(
    clippy::too_many_lines,
    reason = "this item intentionally keeps end-to-end tagging flow explicit for maintainability"
)]
async fn run_internal_media_tagger_impl(options: InternalMediaTaggerOptions) -> anyhow::Result<()> {
    let resolved_input = options
        .input_path
        .as_ref()
        .map(|input_path| input_path.canonicalize().unwrap_or_else(|_| input_path.clone()));
    let media_tagger_cache = MediaTaggerHttpCache::new(
        options.cache_dir.clone(),
        CacheExpiryPolicy::from_seconds(options.cache_expiry_seconds),
    );
    let mut detected_recording_mbid = normalize_optional_text(options.recording_mbid.as_deref());
    let mut detected_release_mbid = normalize_optional_text(options.release_mbid.as_deref());

    if detected_recording_mbid.is_none() {
        let Some(resolved_input) = resolved_input.as_ref() else {
            bail!(
                "input media is required when --recording-mbid is not provided (fingerprint autodetection path)"
            );
        };

        let acoustid_api_key = require_acoustid_api_key_for_lookup(resolve_acoustid_api_key(
            options.acoustid_api_key.as_deref(),
        ))?;
        let fingerprint_payload = decode_and_fingerprint_audio(resolved_input)
            .await
            .context("decoding media for fingerprinting")?;
        let match_result = lookup_acoustid_match(
            &options.acoustid_endpoint,
            &acoustid_api_key,
            &fingerprint_payload.fingerprint,
            fingerprint_payload.duration_seconds,
        )
        .await
        .with_context(|| {
            format!(
                "resolving recording identity through AcoustID endpoint '{}'",
                options.acoustid_endpoint
            )
        })?;

        detected_recording_mbid = detected_recording_mbid.or(match_result.recording_mbid);
        detected_release_mbid = detected_release_mbid.or(match_result.release_mbid);
    }

    let Some(recording_mbid) = detected_recording_mbid else {
        if options.strict_identification {
            bail!(
                "could not resolve recording MBID (set --recording-mbid or provide AcoustID API key via --acoustid-api-key/{ACOUSTID_API_KEY_ENV})"
            );
        }

        let fallback_map = fallback_ffmetadata_map(resolved_input.as_deref()).await;
        write_ffmetadata_document(&options.output_path, &fallback_map)?;
        return Ok(());
    };

    let metadata_payload = fetch_musicbrainz_payloads(
        &recording_mbid,
        detected_release_mbid.as_deref(),
        &media_tagger_cache,
    )
    .await
    .with_context(|| {
        format!(
            "fetching MusicBrainz entities from '{}' for recording '{}'",
            options.musicbrainz_endpoint, recording_mbid
        )
    });

    let metadata_payload = match metadata_payload {
        Ok(payload) => payload,
        Err(error) => {
            if options.strict_identification {
                return Err(error);
            }
            let fallback_map = fallback_ffmetadata_map(resolved_input.as_deref()).await;
            write_ffmetadata_document(&options.output_path, &fallback_map)?;
            return Ok(());
        }
    };

    let mut ffmetadata_map = build_ffmetadata_map(&metadata_payload, options.write_all_tags)
        .context("building FFmetadata mapping from MusicBrainz payload")?;

    let mut selected_cover_art = Vec::new();
    if options.write_all_images {
        selected_cover_art = collect_musicbrainz_cover_art(&metadata_payload, &media_tagger_cache)
            .await
            .context("collecting MusicBrainz cover-art entries")?;
        insert_musicbrainz_image_tags(&mut ffmetadata_map, &selected_cover_art);
    }

    if let Some(input_path) = resolved_input.as_deref() {
        let existing_metadata = extract_existing_ffmetadata_map(input_path).await?;
        if !existing_metadata.is_empty() {
            let mut merged = existing_metadata;
            for (key, value) in ffmetadata_map {
                merged.insert(key, value);
            }
            ffmetadata_map = merged;
        }
    }

    if ffmetadata_map.is_empty() {
        if options.strict_identification {
            bail!("resolved metadata payload did not produce any FFmetadata entries");
        }
        let fallback_map = fallback_ffmetadata_map(resolved_input.as_deref()).await;
        write_ffmetadata_document(&options.output_path, &fallback_map)?;
        return Ok(());
    }

    persist_cover_art_slot_artifacts(
        &options.output_path,
        &selected_cover_art,
        options.cover_art_slot_count,
        &media_tagger_cache,
    )
    .await
    .context("writing media-tagger cover-art slot artifacts")?;

    write_ffmetadata_document(&options.output_path, &ffmetadata_map)
}

/// Builds fallback FFmetadata content from existing input media metadata.
///
/// When input media is available, fallback output should preserve existing tags
/// to avoid destructive metadata clears in downstream ffmpeg apply stages.
async fn fallback_ffmetadata_map(input_path: Option<&Path>) -> BTreeMap<String, String> {
    let Some(input_path) = input_path else {
        return BTreeMap::new();
    };

    extract_existing_ffmetadata_map(input_path).await.unwrap_or_default()
}

/// Extracts current global metadata from one media file through ffmpeg
/// FFmetadata export and decodes it into a key/value map.
async fn extract_existing_ffmetadata_map(
    input_path: &Path,
) -> anyhow::Result<BTreeMap<String, String>> {
    let ffmpeg_executable = resolve_ffmpeg_executable();
    let output = Command::new(&ffmpeg_executable)
        .arg("-v")
        .arg("error")
        // Probe just enough for container metadata so we avoid wasting time
        // on large stream tables when the FFmetadata muxer only needs tags.
        .arg("-probesize")
        .arg("32k")
        .arg("-analyzeduration")
        .arg("0")
        .arg("-i")
        .arg(input_path)
        // Skip codec initialization: the FFmetadata muxer reads only
        // container-level tags and does not need to decode any streams.
        .arg("-vn")
        .arg("-an")
        .arg("-sn")
        .arg("-dn")
        .arg("-f")
        .arg("ffmetadata")
        .arg("-")
        .output()
        .await
        .with_context(|| {
            format!(
                "running '{ffmpeg_executable}' to extract existing metadata from '{}'",
                input_path.display()
            )
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!(
            "ffmpeg metadata extraction failed for '{}' with status {}: {stderr}",
            input_path.display(),
            output.status
        );
    }

    let text = String::from_utf8(output.stdout).with_context(|| {
        format!(
            "ffmpeg metadata extraction output for '{}' was not valid UTF-8",
            input_path.display()
        )
    })?;

    Ok(parse_ffmetadata_global_map(&text))
}
