//! Filesystem path layout helpers for Phase 3 `mediapm` state.
//!
//! This module centralizes where `mediapm` keeps user policy, conductor-facing
//! Nickel documents, lock state, and staging directories.
//! Keeping path decisions in one place prevents accidental drift between CLI,
//! sync service, and tests.

use std::path::{Path, PathBuf};

use crate::config::MediaRuntimeStorage;

/// Canonical path bundle for one `mediapm` workspace root.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MediaPmPaths {
    /// Root directory that contains all `mediapm` files.
    pub root_dir: PathBuf,
    /// User-edited `mediapm` policy/config Nickel document.
    pub mediapm_ncl: PathBuf,
    /// Conductor user Nickel document used by Phase 3 orchestration.
    pub conductor_user_ncl: PathBuf,
    /// Conductor machine Nickel document used by Phase 3 orchestration.
    pub conductor_machine_ncl: PathBuf,
    /// Conductor volatile runtime state document path used by Phase 3 orchestration.
    pub conductor_state_config: PathBuf,
    /// Phase 3 lock file that tracks materialized outputs and safety metadata.
    pub lock_jsonc: PathBuf,
    /// Runtime dotenv file used to load local credential overrides.
    pub env_file: PathBuf,
    /// Runtime root for `mediapm`-owned state under the workspace root.
    pub runtime_root: PathBuf,
    /// Embedded Nickel schema export directory for `mediapm.ncl` contracts.
    ///
    /// `None` means schema export is disabled by runtime policy.
    pub schema_export_dir: Option<PathBuf>,
    /// Temporary staging directory used by atomic sync.
    pub tmp_dir: PathBuf,
    /// Materialized media library root.
    pub library_dir: PathBuf,
    /// Tool-specific runtime assets generated by `mediapm`.
    pub tools_dir: PathBuf,
}

impl MediaPmPaths {
    /// Computes canonical Phase 3 paths from one workspace root.
    #[must_use]
    pub fn from_root(root_dir: impl Into<PathBuf>) -> Self {
        let root_dir = root_dir.into();
        let runtime_root = root_dir.join(".mediapm");

        Self {
            mediapm_ncl: root_dir.join("mediapm.ncl"),
            conductor_user_ncl: root_dir.join("mediapm.conductor.ncl"),
            conductor_machine_ncl: root_dir.join("mediapm.conductor.machine.ncl"),
            conductor_state_config: runtime_root.join("state.ncl"),
            lock_jsonc: runtime_root.join("lock.jsonc"),
            env_file: runtime_root.join(".env"),
            schema_export_dir: Some(runtime_root.join("config")),
            tmp_dir: runtime_root.join("tmp"),
            library_dir: root_dir.clone(),
            tools_dir: runtime_root.join("tools"),
            runtime_root,
            root_dir,
        }
    }

    /// Returns the default path layout rooted at the current working directory.
    #[must_use]
    pub fn from_current_dir() -> Self {
        Self::from_root(Path::new("."))
    }

    /// Resolves runtime storage overrides from `mediapm.ncl`.
    ///
    /// Resolution rules:
    /// - `runtime.mediapm_dir` is resolved relative to the outermost
    ///   `mediapm.ncl` directory when provided as a relative path,
    /// - `runtime.library_dir` is resolved relative to the outermost
    ///   `mediapm.ncl` directory when provided as a relative path,
    /// - `runtime.tmp_dir` is resolved relative to the effective
    ///   runtime root when provided as a relative path,
    /// - `runtime.conductor_config` and
    ///   `runtime.conductor_machine_config` resolve relative to the
    ///   outermost `mediapm.ncl` directory when provided as relative paths,
    /// - `runtime.conductor_state` resolves relative to the outermost
    ///   `mediapm.ncl` directory when provided as a relative path,
    /// - `runtime.lockfile` resolves relative to the outermost
    ///   `mediapm.ncl` directory when provided as a relative path,
    /// - `runtime.env_file` resolves relative to the outermost
    ///   `mediapm.ncl` directory when provided as a relative path,
    /// - omitted fields keep defaults of config root for library output and
    ///   `tmp/` under `.mediapm/`.
    #[must_use]
    pub fn with_runtime_storage(&self, runtime_storage: &MediaRuntimeStorage) -> Self {
        let config_dir = self.mediapm_ncl.parent().unwrap_or(&self.root_dir);

        let runtime_root = runtime_storage
            .mediapm_dir
            .as_deref()
            .map(|raw| resolve_path(config_dir, raw))
            .unwrap_or_else(|| self.runtime_root.clone());

        let library_dir = runtime_storage
            .library_dir
            .as_deref()
            .map(|raw| resolve_path(config_dir, raw))
            .unwrap_or_else(|| config_dir.to_path_buf());

        let tmp_dir = runtime_storage
            .tmp_dir
            .as_deref()
            .map(|raw| resolve_path(&runtime_root, raw))
            .unwrap_or_else(|| runtime_root.join("tmp"));

        let conductor_user_ncl = runtime_storage
            .conductor_config
            .as_deref()
            .map(|raw| resolve_path(config_dir, raw))
            .unwrap_or_else(|| self.conductor_user_ncl.clone());

        let conductor_machine_ncl = runtime_storage
            .conductor_machine_config
            .as_deref()
            .map(|raw| resolve_path(config_dir, raw))
            .unwrap_or_else(|| self.conductor_machine_ncl.clone());

        let conductor_state_config = runtime_storage
            .conductor_state
            .as_deref()
            .map(|raw| resolve_path(config_dir, raw))
            .unwrap_or_else(|| runtime_root.join("state.ncl"));

        let lock_jsonc = runtime_storage
            .lockfile
            .as_deref()
            .map(|raw| resolve_path(config_dir, raw))
            .unwrap_or_else(|| runtime_root.join("lock.jsonc"));

        let env_file = runtime_storage
            .env_file
            .as_deref()
            .map(|raw| resolve_path(config_dir, raw))
            .unwrap_or_else(|| runtime_root.join(".env"));

        let schema_export_dir = match &runtime_storage.schema_config_dir {
            None => Some(runtime_root.join("config")),
            Some(None) => None,
            Some(Some(raw)) => Some(resolve_path(config_dir, raw)),
        };

        Self {
            root_dir: self.root_dir.clone(),
            mediapm_ncl: self.mediapm_ncl.clone(),
            conductor_user_ncl,
            conductor_machine_ncl,
            conductor_state_config,
            lock_jsonc,
            env_file,
            schema_export_dir,
            runtime_root: runtime_root.clone(),
            tmp_dir,
            library_dir,
            tools_dir: runtime_root.join("tools"),
        }
    }
}

/// Resolves one path value against a base directory unless it is absolute.
#[must_use]
fn resolve_path(base_dir: &Path, raw: &str) -> PathBuf {
    let candidate = PathBuf::from(raw);
    if candidate.is_absolute() { candidate } else { base_dir.join(candidate) }
}

#[cfg(test)]
mod tests {
    use crate::config::MediaRuntimeStorage;

    use super::MediaPmPaths;

    /// Ensures default runtime paths keep lock/tmp under `.mediapm` while
    /// library is rooted beside the top-level `mediapm.ncl`.
    #[test]
    fn default_paths_use_dot_mediapm_root() {
        let root = tempfile::tempdir().expect("tempdir");
        let paths = MediaPmPaths::from_root(root.path());

        assert_eq!(paths.runtime_root, root.path().join(".mediapm"));
        assert_eq!(paths.library_dir, root.path());
        assert_eq!(paths.tmp_dir, root.path().join(".mediapm").join("tmp"));
        assert_eq!(paths.conductor_state_config, root.path().join(".mediapm").join("state.ncl"));
        assert_eq!(paths.lock_jsonc, root.path().join(".mediapm").join("lock.jsonc"));
        assert_eq!(paths.env_file, root.path().join(".mediapm").join(".env"));
        assert_eq!(paths.schema_export_dir, Some(root.path().join(".mediapm").join("config")));
    }

    /// Ensures `library_dir` remains config-root relative while `tmp_dir`
    /// remains runtime-root relative.
    #[test]
    fn runtime_storage_overrides_resolve_with_split_roots() {
        let root = tempfile::tempdir().expect("tempdir");
        let base = MediaPmPaths::from_root(root.path());
        let runtime_storage = MediaRuntimeStorage {
            mediapm_dir: Some(".mediapm-runtime".to_string()),
            library_dir: Some("library-custom".to_string()),
            tmp_dir: Some("tmp-custom".to_string()),
            conductor_config: Some("configs/custom.conductor.ncl".to_string()),
            conductor_machine_config: Some("configs/custom.conductor.machine.ncl".to_string()),
            conductor_state: Some("state/custom.state.ncl".to_string()),
            inherited_env_vars: None,
            lockfile: Some("state/custom.lock.jsonc".to_string()),
            env_file: Some("state/custom.env".to_string()),
            schema_config_dir: Some(Some("schemas/mediapm".to_string())),
            use_user_download_cache: None,
        };

        let resolved = base.with_runtime_storage(&runtime_storage);

        assert_eq!(resolved.runtime_root, root.path().join(".mediapm-runtime"));
        assert_eq!(resolved.library_dir, root.path().join("library-custom"));
        assert_eq!(resolved.tmp_dir, root.path().join(".mediapm-runtime").join("tmp-custom"));
        assert_eq!(
            resolved.conductor_user_ncl,
            root.path().join("configs").join("custom.conductor.ncl")
        );
        assert_eq!(
            resolved.conductor_machine_ncl,
            root.path().join("configs").join("custom.conductor.machine.ncl")
        );
        assert_eq!(
            resolved.conductor_state_config,
            root.path().join("state").join("custom.state.ncl")
        );
        assert_eq!(resolved.lock_jsonc, root.path().join("state").join("custom.lock.jsonc"));
        assert_eq!(resolved.env_file, root.path().join("state").join("custom.env"));
        assert_eq!(resolved.schema_export_dir, Some(root.path().join("schemas/mediapm")));
    }
}
