//! Deterministic planning from declarative configuration.
//!
//! The planner is pure: it computes effects without performing side effects.
//! This makes plans cacheable, testable, and reviewable before any filesystem
//! mutation occurs.

use std::path::{Path, PathBuf};

use anyhow::{Result, anyhow};
use serde::Serialize;

use crate::{
    configuration::config::{AppConfig, VariantSelection},
    domain::canonical::canonicalize_uri,
};

/// Ordered set of effects required to reconcile desired state.
///
/// `Plan` is deliberately simple: an ordered list of effect declarations. The
/// ordering contract is important because it keeps output stable across runs.
#[derive(Clone, Debug, Serialize, PartialEq, Eq)]
pub struct Plan {
    /// Deterministically-sorted effect list.
    pub effects: Vec<Effect>,
}

impl Plan {
    /// Return `true` when no side effects are required.
    pub fn is_empty(&self) -> bool {
        self.effects.is_empty()
    }
}

/// Side-effect declarations generated by planning.
///
/// Effects encode *intentional actions* rather than low-level operations. The
/// executor may choose platform-specific mechanisms (symlink vs hardlink) while
/// preserving effect-level semantics.
#[derive(Clone, Debug, Serialize, PartialEq, Eq)]
#[serde(tag = "effect", rename_all = "snake_case")]
pub enum Effect {
    /// Ensure a source file has been imported into the object store.
    EnsureImported { canonical_uri: String, source_path: String },
    /// Ensure a link-like artifact exists at `link_path` for selected variant.
    EnsureLink { canonical_uri: String, link_path: String, selection: VariantSelection },
}

/// Build a deterministic plan from config + current working directory context.
///
/// The same config + workspace snapshot should always yield the same ordered
/// effect list. This property is foundational for dry-run trust and stable CI
/// checks.
pub fn build_plan(config: &AppConfig, cwd: &Path) -> Result<Plan> {
    let mut effects = Vec::new();

    for source in &config.sources {
        let canonical_uri = canonicalize_uri(&source.uri, cwd)?;
        let source_path = canonical_uri.to_file_path().map_err(|_| {
            anyhow!("source URI must be a local file URI: {}", canonical_uri.as_str())
        })?;

        effects.push(Effect::EnsureImported {
            canonical_uri: canonical_uri.into_string(),
            source_path: source_path.to_string_lossy().to_string(),
        });
    }

    for link in &config.links {
        let canonical_uri = canonicalize_uri(&link.from_uri, cwd)?;
        let link_path = normalize_target_path(cwd, &link.path);

        effects.push(Effect::EnsureLink {
            canonical_uri: canonical_uri.into_string(),
            link_path: link_path.to_string_lossy().to_string(),
            selection: link.select.clone(),
        });
    }

    effects.sort_by_key(effect_sort_key);

    Ok(Plan { effects })
}

/// Render a concise human-readable plan summary.
///
/// This rendering is intentionally opinionated but compact, optimized for human
/// dry-run review rather than machine consumption.
pub fn render_plan_human(plan: &Plan) -> String {
    if plan.effects.is_empty() {
        return "No actions required.".to_owned();
    }

    let mut lines = Vec::with_capacity(plan.effects.len() + 1);
    lines.push(format!("Planned {} effect(s):", plan.effects.len()));

    for effect in &plan.effects {
        match effect {
            Effect::EnsureImported { canonical_uri, source_path } => {
                lines.push(format!("- import {canonical_uri} from {source_path}"))
            }
            Effect::EnsureLink { canonical_uri, link_path, selection } => lines.push(format!(
                "- link {link_path} -> {canonical_uri} ({})",
                match &selection.variant_hash {
                    Some(hash) => format!("variant={hash}"),
                    None => format!("prefer={:?}", selection.prefer),
                }
            )),
        }
    }

    lines.join("\n")
}

fn effect_sort_key(effect: &Effect) -> String {
    match effect {
        Effect::EnsureImported { canonical_uri, source_path } => {
            format!("0|{canonical_uri}|{source_path}")
        }
        Effect::EnsureLink { canonical_uri, link_path, .. } => {
            format!("1|{canonical_uri}|{link_path}")
        }
    }
}

fn normalize_target_path(cwd: &Path, input: &str) -> PathBuf {
    let target = PathBuf::from(input);
    if target.is_absolute() { target } else { cwd.join(target) }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::build_plan;
    use crate::configuration::config::AppConfig;

    #[test]
    fn plan_is_deterministic() {
        let config: AppConfig = serde_json::from_value(json!({
            "sources": [{ "uri": "src/main.rs" }],
            "links": [{ "path": "library/main.rs", "from_uri": "src/main.rs" }]
        }))
        .expect("test config should deserialize");

        let cwd = std::env::current_dir().expect("cwd should resolve");
        let plan_a = build_plan(&config, &cwd).expect("plan A should build");
        let plan_b = build_plan(&config, &cwd).expect("plan B should build");

        assert_eq!(plan_a, plan_b);
    }
}
