//! Document I/O helpers for loading, saving, and compiling conductor Nickel documents.
//!
//! These are thin wrappers around versioned codec functions with consistent
//! error mapping, file-existence guards, and change-guarded writes.

use std::path::Path;

use crate::error::ConductorError;
use crate::model::config::{
    MachineNickelDocument, StateNickelDocument, UserNickelDocument,
    compile_total_configuration_sources, decode_machine_document, decode_state_document,
    decode_user_document, encode_machine_document, encode_state_document, encode_user_document,
};

/// Shared loading logic for all Nickel document types.
///
/// Checks existence, reads bytes from disk, skips whitespace-only content,
/// and passes through the versioned decoder.
fn load_document<T>(
    path: &Path,
    display_name: &str,
    decode: fn(&[u8]) -> Result<T, ConductorError>,
    default: T,
) -> Result<T, ConductorError> {
    if !path.exists() {
        return Ok(default);
    }

    let bytes = std::fs::read(path)
        .map_err(|source| ConductorError::io(format!("reading {display_name}"), path, source))?;

    if bytes.iter().all(u8::is_ascii_whitespace) {
        return Ok(default);
    }

    decode(&bytes)
}

/// Loads `conductor.ncl` through versioned decoder, returning default when absent.
pub(super) fn load_user_document(path: &Path) -> Result<UserNickelDocument, ConductorError> {
    load_document(path, "conductor.ncl", decode_user_document, UserNickelDocument::default())
}

/// Loads `conductor.machine.ncl` through versioned decoder, returning default when absent.
pub(super) fn load_machine_document(path: &Path) -> Result<MachineNickelDocument, ConductorError> {
    load_document(
        path,
        "conductor.machine.ncl",
        decode_machine_document,
        MachineNickelDocument::default(),
    )
}

/// Loads one state document path through versioned decoder, returning default
/// when absent.
pub(super) fn load_state_document(path: &Path) -> Result<StateNickelDocument, ConductorError> {
    load_document(path, "state document", decode_state_document, StateNickelDocument::default())
}

/// Saves `conductor.machine.ncl` using versioned encoder.
pub(super) fn save_machine_document(
    path: &Path,
    document: &MachineNickelDocument,
) -> Result<(), ConductorError> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|source| ConductorError::Io {
            operation: "creating parent directory for conductor.machine.ncl".to_string(),
            path: parent.to_path_buf(),
            source,
        })?;
    }

    let bytes = with_generated_banner(
        encode_machine_document(document.clone())?,
        concat!(
            "# @generated by mediapm-conductor CLI\n",
            "# This file is machine-managed. Prefer editing conductor.ncl for user intent.\n\n",
        ),
    );
    write_if_changed(path, &bytes, "writing conductor.machine.ncl")
}

/// Compiles merged user/machine/state configuration into deterministic JSON
/// output without mutating runtime state.
pub(super) fn compile_effective_configuration(
    user_ncl: &Path,
    machine_ncl: &Path,
    state_ncl: &Path,
) -> Result<serde_json::Value, ConductorError> {
    let user = load_user_document(user_ncl)?;
    let machine = load_machine_document(machine_ncl)?;
    let state = load_state_document(state_ncl)?;

    let user_source = String::from_utf8(encode_user_document(user)?).map_err(|source| {
        ConductorError::Serialization(format!(
            "encoding conductor.ncl for compile inspection produced invalid UTF-8: {source}"
        ))
    })?;
    let machine_source = String::from_utf8(encode_machine_document(machine)?).map_err(|source| {
        ConductorError::Serialization(format!(
            "encoding conductor.machine.ncl for compile inspection produced invalid UTF-8: {source}"
        ))
    })?;
    let state_source = String::from_utf8(encode_state_document(state)?).map_err(|source| {
        ConductorError::Serialization(format!(
            "encoding state document for compile inspection produced invalid UTF-8: {source}"
        ))
    })?;

    compile_total_configuration_sources(&user_source, &machine_source, &state_source)
}

/// Prefixes generated-file ownership banner bytes when not already present.
#[must_use]
fn with_generated_banner(mut bytes: Vec<u8>, banner: &str) -> Vec<u8> {
    if bytes.starts_with(banner.as_bytes()) {
        return bytes;
    }

    let mut merged = banner.as_bytes().to_vec();
    merged.append(&mut bytes);
    merged
}

/// Writes bytes only when file contents change.
fn write_if_changed(path: &Path, bytes: &[u8], operation: &str) -> Result<(), ConductorError> {
    if let Ok(existing) = std::fs::read(path)
        && existing == bytes
    {
        return Ok(());
    }

    std::fs::write(path, bytes).map_err(|source| ConductorError::Io {
        operation: operation.to_string(),
        path: path.to_path_buf(),
        source,
    })
}
